### ISSUE TITLE
XeTeX package missing xdvipdfmx dependency

### ISSUE THREAD

**Issue by IcedQuinn** [void-linux/void-packages#44421] opened 2023-06-14 02:46 UTC
### Is this a new report?

Yes

### System Info

Void 6.1.31_1 x86_64 AuthenticAMD notuptodate rrmFFFFFFFF

### Package(s) Affected

texlive-XeTeX-20210325_5

### Expected behaviour

With stock pdftex:

```
icedquinn@astaraline ~/Z/p/vcdiff (trunk)> pdftex demo.tex
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021/VoidLinux) (preloaded format=pdftex)
 restricted \write18 enabled.
entering extended mode
(./demo.tex [1{/usr/share/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] )</us
r/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on demo.pdf (1 page, 12116 bytes).
Transcript written on demo.log.
```

### Actual behaviour

```
icedquinn@astaraline ~/Z/p/vcdiff (trunk)> xetex demo.tex
This is XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2021/VoidLinux) (preloaded format=xetex)
 restricted \write18 enabled.
entering extended mode
(./demo.tex)
*\bye
[1]sh: 1: /usr/bin/xdvipdfmx: not found

Error 32512 (driver return code) generating output;
file demo.pdf may not be valid.
Transcript written on demo.log.
```

### Steps to reproduce

- Install XeTeX
- Attempt to compile a plain TeX file
- It will succeed with pdftex, while it fails with xetex.

**Comment by classabbyamp** [comment] 2023-06-14 03:00
duplicate of #43674

**Closed** 2023-06-14 03:00 UTC
Labels: bug, duplicate
