### ISSUE TITLE
Package Request: OpenJFX

### ISSUE THREAD

**Issue by OtakuSenpai** [void-linux/void-packages#3710] opened 2018-10-12 16:43 UTC
OpenJFX is OpenJDK's implementation of JavaFX.
http://openjdk.java.net/projects/openjfx/getting-started.html

**Comment by cr6git** [comment] 2018-10-12 18:02
duplicate of https://github.com/void-linux/void-packages/issues/3197

**Closed** 2018-10-13 07:36 UTC
Labels: request
