### ISSUE TITLE
gnome-shell: Cannot focus on apps or app bar

### ISSUE THREAD

**Issue by darmon77** [void-linux/void-packages#30125] opened 2021-04-10 17:39 UTC
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3976

**Comment by notthewave** [comment] 2021-04-10 18:49
@Gottox you tested it before didn’t you? Apparently it "worked great", so I assume this problem didn’t occur to you.

If that’s in fact the case, there might be some easy fix or this.

**Comment by paper42** [comment] 2021-04-10 18:51
Is this happening to you? Please fill the issue template. I have a dual screen setup with Intel integrated graphics like in the issue you posted and I didn't notice this happening.

**Comment by Gottox** [comment] 2021-04-10 18:53
Can't reproduce here. Can you give more information about your setup?

**Comment by Gottox** [comment] 2021-04-10 18:56
Also please use proper titles. This has only clickbait level qualities :stuck_out_tongue_closed_eyes:

**Comment by darmon77** [comment] 2021-04-10 19:18
> Is this happening to you? Please fill the issue template. I have a dual screen setup with Intel integrated graphics like in the issue you posted and I didn't notice this happening.

My problem is exactly the one described in gnome.
A not completely stable package. It is not advisable to update.
Testing and seeing their behavior in beta is a better idea, for some users to work and others not.

**Comment by Gottox** [comment] 2021-04-10 19:25
Sorry, but I can't help if I can't reproduce the issue. Upstream has a hard time too. Could you provide any more informations?

**Comment by Gottox** [comment] 2021-04-10 19:28
@darmon77  Could you try to start with a fresh `.config` directory and see if the issue is still present?

**Comment by Gottox** [comment] 2021-04-10 19:35
Also does this happen with Xorg too?

**Comment by notthewave** [comment] 2021-04-10 20:50
![5E611786-1B70-45CD-AE13-EF845DCD7C59](https://user-images.githubusercontent.com/74874782/114283189-c5b18380-9a48-11eb-8b67-78b720d23e3b.jpeg)
Some basic system info provided by neofetch 😜

I’m on musl

Issue was also present on Xorg after Xorg-fonts and driver install.

Removed everything (inc contents of $HOME). Starting with:
base-system 
grub
opendoas

Will install: 
Gnome
Mesa
Mesa-intel-dri
lf

TEST:
Wayland issue present.
...
Install: 
Gnome-apps

TEST2:
Wayland issue present.
...
Next up Xorg

Install:
Xorg

Result: same issue on Xorg
...

Monitor swap:
1680x1050

Still...

Gottox do you have a glibc system?

**Comment by notthewave** [comment] 2021-04-10 21:12
Since I have a Tablet:
Pen and Touch input misbehave as well...

**Comment by darmon77** [comment] 2021-04-10 21:26
It sure is a gnome-shell problem with libinput, I'm going to do the tests.
This should have been seen in testing before the update.

**Comment by paper42** [comment] 2021-04-10 21:38
@notthewave I have thinkpad x220 (without touch) and glibc. @darmon77 do you have musl too? The touch input was ok when I was testing gnome 40 before it was merged, I don't have my touchscreen laptop right now.

**Comment by notthewave** [comment] 2021-04-10 21:54
So I installed libinput-gestures or whatever and I behaves differently. And I can’t map monitors correctly anymore.

**Comment by darmon77** [comment] 2021-04-10 22:00
@paper42 my anomalous behavior is in musl.
I am installing two gnome dbg (glibc & musl) to reproduce the error.
I will comment on everything necessary

**Comment by Gottox** [comment] 2021-04-11 05:34
Thanks for the report. I'm currently guessing it's bug that is triggered on musl systems. Nevertheless, I can't see why yet.

**Comment by Gottox** [comment] 2021-04-11 12:03
Update: I'm able to reproduce the issue now. Afaics, the bug should be somewhere in gnome-shell or mutter. First I suspected gtk4, but running the gtk4 demo doesn't result in hanky behavior.

**Comment by Gottox** [comment] 2021-04-11 12:05
https://youtu.be/bvfcDb9hm5U

**Closed** 2021-04-11 18:44 UTC
Labels: bug
