### ISSUE TITLE
Package request: helix

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-packages#35413] opened 2022-02-05 01:03 UTC
A kakoune / neovim inspired editor, written in Rust.

homepage: https://helix-editor.com/
changelog: https://github.com/helix-editor/helix/blob/master/CHANGELOG.md
source: https://github.com/helix-editor/helix
license: Mozilla Public License 2.0

pkgbuild archlinux: https://github.com/archlinux/svntogit-community/tree/packages/helix/trunk

![helix](https://github.com/helix-editor/helix/raw/master/screenshot.png)

**Comment by paper42** [comment] 2022-02-05 02:02
duplicate of #33881

**Closed by paper42** 2022-02-05 02:02 UTC
