### ISSUE TITLE
ibus failed to insert character through unicode or insert emoji

### ISSUE THREAD

**Issue by funk443** [void-linux/void-packages#43536] opened 2023-04-20 03:17 UTC
### Is this a new report?

Yes

### System Info

Void 6.1.21_1 x86_64 AuthenticAMD notuptodate rFFFFF

### Package(s) Affected

ibus-1.5.28_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?
Probably related to this: 
https://github.com/ibus/ibus/issues/2476

### Expected behaviour

After pressing the keybinding for inserting a char using unicode, enter `0041` should output `A`.
Or after pressing the keybinding for inserting a emoji, enter `smile` and press space bar should output `😊`.

### Actual behaviour

Nothing was outputted.

The output from ibus-daemon:
```

(ibus-ui-gtk3:30847): IBUS-WARNING **: 11:12:55.699: panel.vala:307: XDG_CURRENT_DESKTOP is not exported in your desktop session.

(ibus-ui-gtk3:30847): IBUS-WARNING **: 11:12:55.699: panel.vala:310: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-extension-gtk3:30848): IBUS-CRITICAL **: 11:12:55.784: ibus_serializable_deserialize_object: assertion 'g_type_is_a (type, IBUS_TYPE_SERIALIZABLE)' failed

(ibus-extension-gtk3:30848): IBUS-CRITICAL **: 11:12:55.784: ibus_serializable_deserialize_object: assertion 'g_type_is_a (type, IBUS_TYPE_SERIALIZABLE)' failed

(ibus-extension-gtk3:30848): IBUS-CRITICAL **: 11:12:55.784: ibus_serializable_deserialize_object: assertion 'g_type_is_a (type, IBUS_TYPE_SERIALIZABLE)' failed

(ibus-extension-gtk3:30848): IBUS-CRITICAL **: 11:12:55.784: ibus_serializable_deserialize_object: assertion 'g_type_is_a (type, IBUS_TYPE_SERIALIZABLE)' failed

(ibus-extension-gtk3:30848): IBUS-CRITICAL **: 11:12:55.784: ibus_serializable_deserialize_object: assertion 'g_type_is_a (type, IBUS_TYPE_SERIALIZABLE)' failed

(ibus-extension-gtk3:30848): IBUS-CRITICAL **: 11:12:55.784: ibus_serializable_deserialize_object: assertion 'g_type_is_a (type, IBUS_TYPE_SERIALIZABLE)' failed

;; Omitted many lines of exact same errors


(ibus-extension-gtk3:30848): IBUS-CRITICAL **: 11:12:55.871: ibus_emojier_update_emoji_to_data_dict: assertion 'data != NULL' failed

(ibus-extension-gtk3:30848): IBUS-CRITICAL **: 11:12:55.871: ibus_emojier_update_annotation_to_emojis_dict: assertion 'data != NULL' failed

(ibus-extension-gtk3:30848): IBUS-CRITICAL **: 11:12:55.871: ibus_emojier_update_category_to_emojis_dict: assertion 'data != NULL' failed

(ibus-extension-gtk3:30848): IBUS-CRITICAL **: 11:12:55.871: ibus_emojier_update_emoji_to_data_dict: assertion 'data != NULL' failed

(ibus-extension-gtk3:30848): IBUS-CRITICAL **: 11:12:55.871: ibus_emojier_update_annotation_to_emojis_dict: assertion 'data != NULL' failed

(ibus-extension-gtk3:30848): IBUS-CRITICAL **: 11:12:55.871: ibus_emojier_update_category_to_emojis_dict: assertion 'data != NULL' failed

;; Omitted many lines of this alternating pattern of these three errors
```

### Steps to reproduce

1. Start ibus-daemon (using `ibus-daemon -vrxR`)
2. Switch to unicode input mode (default keybinding is `Ctrl-Shift-u`
3. Enter `0041` then press `Space`
4. Switch to emoji input mode (default keybinding is `Super-.`)
5. Enter `smile` then press `Space`

**Comment by oreo639** [comment] 2023-04-20 06:41
> Switch to unicode input mode (default keybinding is `Ctrl-Shift-u`
> Enter 0041 then press Space

Works for me.

> Switch to emoji input mode (default keybinding is `Super-.`)

Thanks for pointing that out. I can also reproduce the issue using `/usr/libexec/ibus-ui-emojier`.
Emojis should show up properly with this patch: https://github.com/void-linux/void-packages/pull/43537

**Comment by fujiwarat** [comment] 2023-05-01 03:34
Duplicate of #2476

**Comment by classabbyamp** [comment] 2023-05-01 03:48
#43537

**Closed by classabbyamp** 2023-05-01 03:48 UTC
Labels: bug
