### ISSUE TITLE
Cinnamon start menu is nonfunctional on a fresh cinnamon install

### ISSUE THREAD

**Issue by llimllib** [void-linux/void-packages#23383] opened 2020-07-03 19:57 UTC
### System

* xuname:  `Void 5.3.9_1 x86_64 GenuineIntel uptodate rFF`
* package:  
  * I'm guessing `cinnamon-4.6.1_2:` and `cinnamon-settings-daemon-4.6.2_1` are relevant packages. For whatever it's worth, here are all cinnamon packages (`xbps-query -p pkgver -s cinnamon`)

```
cinnamon-4.6.1_2: cinnamon-4.6.1_2
cinnamon-control-center-4.6.0_1: cinnamon-control-center-4.6.0_1
cinnamon-desktop-4.6.0_1: cinnamon-desktop-4.6.0_1
cinnamon-menus-4.6.0_1: cinnamon-menus-4.6.0_1
cinnamon-screensaver-4.6.0_1: cinnamon-screensaver-4.6.0_1
cinnamon-session-4.6.1_1: cinnamon-session-4.6.1_1
cinnamon-settings-daemon-4.6.2_1: cinnamon-settings-daemon-4.6.2_1
cinnamon-translations-4.6.0_1: cinnamon-translations-4.6.0_1
libcinnamon-control-center-4.6.0_1: libcinnamon-control-center-4.6.0_1
```

### Expected behavior

Clicking on an app in the start menu opens the relevant app

### Actual behavior

Clicking on an app in the start menu does nothing

### Steps to reproduce the behavior

Click on any app in the start menu

Running `/usr/bin/cinnamon-settings` from a terminal successfully opens the settings panel which appears to be fully functional.

This is a brand new installation, I am still on my first boot, and the only possibly relevant thing I have done so far was to update the system (with `xbps-install -Su`). That update did update several cinnamon packages, which could conceivably be the cause of the issue?

I did not find any relevant logs, and `dmesg` does not have anything that looks relevant.

The issue did not persist through reboot; everything seems to work fine now.

**Comment by jchook** [comment] 2021-01-10 23:54
I also experience issues with a fresh install and update of void-musl-cinnamon. The glibc version works perfectly.

Using the pre-installed cinnamon 4.2.4, the application menu crashes.

After update, using cinnamon 4.6.7, it crashes on login.

![image](https://user-images.githubusercontent.com/193530/104138777-6625d800-5374-11eb-80df-6c4d8d2648f7.png)

I found an issue on the Cinnamon issue tracker: https://github.com/linuxmint/cinnamon/issues/7882. As suggested, I re-opened the issue but they closed it: https://github.com/linuxmint/cinnamon/issues/9838

**Comment by ericonr** [comment] 2021-02-20 18:52
Ok, I couldn't reproduce this at all from a clean musl installation, using the installer. Is that what you did?

@llimllib @jchook

**Comment by ericonr** [comment] 2021-02-20 19:02
I do believe this was an issue with previous cinnamon versions, but the latest cjs seems to be working ok.

**Comment by llimllib** [comment] 2021-02-22 15:16
I'm sorry, I don't remember, it was too long ago - you're welcome to close the issue if you couldn't reproduce

**Comment by ericonr** [comment] 2021-02-22 15:38
No problem. Thanks for answering!

**Closed** 2021-02-22 15:38 UTC
