### ISSUE TITLE
Python QtQml import fails (breaks qutebrowser)

### ISSUE THREAD

**Issue by aidam38** [void-linux/void-packages#9698] opened 2019-03-11 20:16 UTC
### System

* xuname:  
Void 4.19.27_1 x86_64 GenuineIntel uptodate rrrmDFFFF
* package:  
python3-PyQt5-quick-5.11.3_3 (specifically the QtQml and QtNetwork Python libraries)

### Expected behavior
The following import, and programs requiring it (e.g. **qutebrowser**) works:
```
$ python3 -c 'from PyQt5 import QtCore,QtQml'
```

### Actual behavior
I get this error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib/python3.6/site-packages/PyQt5/QtNetwork.so: symbol _ZN17QPasswordDigestor15deriveKeyPbkdf2EN18QCryptographicHash9AlgorithmERK10QByteArrayS4_iy version Qt_5 not defined in file libQt5Network.so.5 with link time reference
```
### Steps to reproduce the behavior
Have the python3-PyQt5-quick-5.11.3_3 installed and run the command `python3 -c 'from PyQt5 import QtCore,QtQml'`.

**Comment by ninewise** [comment] 2019-03-14 17:19
Could you list which qt5 packages you have installed (`xbps-query -s Qt5`).

**Comment by aidam38** [comment] 2019-03-14 21:23
Here:
```
[*] karchive-5.56.0_1                      Qt5 addon providing access to numerous types of archives
[*] kcoreaddons-5.56.0_1                   Qt5 addon library with a collection of non-GUI utilities
[*] libdbusmenu-qt5-0.9.3+16.04.20160218_2 Library that provides a Qt5 implementation of the DBusMenu spec
[*] phonon-qt5-4.9.1_1                     The multimedia framework for KDE
[*] polkit-qt5-0.112.0_3                   Qt-style PolicyKit API (Qt5)
[*] poppler-qt5-0.74.0_1                   PDF rendering library - Qt5 bindings
[*] python-PyQt5-5.11.3_3                  Python2 bindings for the Qt5 toolkit
[*] python-PyQt5-tools-5.11.3_3            Python2 bindings for the Qt5 toolkit - designer, help modules
[*] python-sip-PyQt5-4.19.13_3             Python2 SIP bindings (PyQt5 version)
[*] python3-PyQt5-5.11.3_3                 Python3 bindings for the Qt5 toolkit
[*] python3-PyQt5-devel-tools-5.11.3_3     Python3 bindings for the Qt5 toolkit - development tools
[*] python3-PyQt5-opengl-5.11.3_3          Python3 bindings for the Qt5 toolkit - opengl module
[*] python3-PyQt5-quick-5.11.3_3           Python3 bindings for the Qt5 toolkit - quick module
[*] python3-PyQt5-sql-5.11.3_3             Python3 bindings for the Qt5 toolkit - sql module
[*] python3-PyQt5-webchannel-5.11.3_3      Python3 bindings for the Qt5 toolkit - webchannel module
[*] python3-PyQt5-webengine-5.11.3_3       Python3 bindings for the Qt5 toolkit - webengine module
[*] python3-PyQt5-webkit-5.11.3_3          Python3 bindings for the Qt5 toolkit - webkit module
[*] python3-sip-PyQt5-4.19.13_3            Python3 SIP bindings (PyQt5 version)
[*] qt5-5.11.3_5                           Cross-platform application and UI framework (QT5)
[*] qt5-declarative-5.11.3_5               Cross-platform application and UI framework (QT5) - Declarative component
[*] qt5-declarative-devel-5.11.3_5         Cross-platform application and UI framework (QT5) - Declarative component (development)
[*] qt5-devel-5.11.3_5                     Cross-platform application and UI framework (QT5) - Development files
[*] qt5-host-tools-5.11.3_5                Cross-platform application and UI framework (QT5) - Tools required when cross compiling
[*] qt5-location-5.11.3_5                  Cross-platform application and UI framework (QT5) - Location and Positioning components
[*] qt5-networkauth-5.11.3_5               Cross-platform application and UI framework (QT5) - NetworkAuth component
[*] qt5-networkauth-devel-5.11.3_5         Cross-platform application and UI framework (QT5) - NetworkAuth component (development)
[*] qt5-plugin-sqlite-5.11.3_5             Cross-platform application and UI framework (QT5) - SQLite plugin
[*] qt5-qmake-5.11.3_5                     Cross-platform application and UI framework (QT5) - Qmake Makefile generator tool
[*] qt5-quickcontrols-5.11.3_5             Cross-platform application and UI framework (QT5) - Quick UI controls
[*] qt5-script-5.11.3_5                    Cross-platform application and UI framework (QT5) - Scriptable classes
[*] qt5-sensors-5.11.3_5                   Cross-platform application and UI framework (QT5) - Sensors component
[*] qt5-serialport-5.11.3_5                Cross-platform application and UI framework (QT5) - Serial port component
[*] qt5-svg-5.11.3_5                       Cross-platform application and UI framework (QT5) - Svg component
[*] qt5-tools-5.11.3_5                     Cross-platform application and UI framework (QT5) - Development tools
[*] qt5-translations-5.11.3_5              Cross-platform application and UI framework (QT5) - Translations
[*] qt5-webchannel-5.11.3_5                Cross-platform application and UI framework (QT5) - WebChannel component
[*] qt5-webengine-5.11.3_5                 Cross-platform application and UI framework (QT5) - WebEngine component
[*] qt5-webengine-devel-5.11.3_5           Cross-platform application and UI framework (QT5) - WebEngine component (development)
[*] qt5-webkit-5.212.0_2                   A cross-platform application and UI framework (Qt5) - WebKit2 component
[*] qt5-webkit-devel-5.212.0_2             A cross-platform application and UI framework (Qt5) - WebKit2 component (development)
[*] qt5-x11extras-5.11.3_5                 Cross-platform application and UI framework (QT5) - X11 extras
[*] qt5-xmlpatterns-5.11.3_5               Cross-platform application and UI framework (QT5) - XML components
[*] qtchooser-66_1                         Qt4/Qt5 version chooser
```

**Comment by ninewise** [comment] 2019-03-14 22:07
Hmm, can't reproduce here, and fwiw you've got more packages installed.

**Comment by aidam38** [comment] 2019-03-14 22:27
I've tried uninstalling not python3 packages, didn't help... It just happened to me all of a sudden and now I'm afraid to update packages on my other computer worried it will happen again. Should I just try brute force reinstalling all the packages listed above (using some sort of script probably; let me know, if you have one)?

**Comment by aidam38** [comment] 2019-03-31 06:59
Hi, this solved my issue :-D
```
xbps-query -s PyQt5 | awk '{print $2}' > pyqt
echo "qutebrowser" >> pyqt
sudo xbps-remove -F $(cat pyqt)
sudo xbps-install -Syu $(cat pyqt)
```
I guess it was just a weird anomaly and we can close this now.

**Comment by ninewise** [comment] 2019-03-31 10:07
Oh right, I didn't have the script at hand and forgot to reply. Great this got it fixed.

(I can't close this)

**Closed** 2019-03-31 10:13 UTC
