### ISSUE TITLE
No tray icons for Electron apps

### ISSUE THREAD

**Issue by notramo** [void-linux/void-packages#11624] opened 2019-05-11 05:53 UTC
### System

* xuname:  
 `Void 4.19.37_1 x86_64 GenuineIntel uptodate rFFFFFF`
* package:  
  `riot-desktop` (don't know which version)

### Expected behavior
Riot Desktop, and other Electron apps has system tray support.

### Actual behavior
No system tray icon for Electron apps.
A few months ago it worked (I don't know exactly).
(GTK and QT apps still have working tray icons.)
### Steps to reproduce the behavior
Launch any Electron app that should have system tray support.

**Comment by pbui** [comment] 2019-05-22 14:58
Hmm.  I just ran the slack-desktop client, which is also an Electron app, and its tray icon displays normally (I'm using polybar with i3wm).  I'm not sure if this is a general problem.

**Comment by pbui** [comment] 2019-05-22 15:01
I also just ran riot-desktop, and once again, I was able to see a tray icon... I'm thinking this might be a local user configuration issue.

**Comment by notramo** [comment] 2019-05-22 15:02
I am using i3-bar.

**Comment by Bendodroid** [comment] 2019-06-11 09:09
Check if `libappindicator` packages are installed. See: https://github.com/vector-im/riot-web/issues/9477

**Comment by DoctorSubtilis** [comment] 2019-06-25 14:26
With 1.2.2 the problem was **not fixed** for us (Kubuntu 18.04).  
![riot bug (no tray icon)](https://user-images.githubusercontent.com/20089138/60106698-ef12f980-9765-11e9-8316-86c04f0fb84f.png)

**Comment by glaubersm** [comment] 2019-07-07 15:53
I have the same problem on Void + KDE Plasma desktop environment.
Discord (installed via flatpak), Riot and Skype are some apps affected.

**Comment by bugger11** [comment] 2019-07-15 20:39
> Check if `libappindicator` packages are installed. See: [vector-im/riot-web#9477](https://github.com/vector-im/riot-web/issues/9477)

Thank you for that. 

I am on Arch Linux with KDE. I first installed  `libappindicator-gtk3` but that did not resolve the issue. So I reluctantly tried installing `libappindicator-sharp` (which pulls in mono), and that did resolve the issue. But I would prefer not to have to install mono. Is mono really a dependency now?

**Comment by ProjectMoon** [comment] 2020-04-05 17:04
I'm having this issue on KDE on X11. In Wayland, the indicators work fine. Both Riot and Signal Desktop output a complaint about dbus when starting up on X11, but not on Wayland.

The error is: `Unable to get the session bus: Unknown or unsupported transport “disabled” for address “disabled:”`

I don't know if it's the same root cause as other people in this issue, but maybe it is helpful.

**Comment by ProjectMoon** [comment] 2020-04-09 20:03
It should also be noted they work fine in Sway, if Sway is run via `dbus-run-session`. So it seems like some kind of issue with starting dbus properly when logging in to KDE for some reason.

**Comment by lschmelting** [comment] 2020-05-25 16:27
As @ProjectMoon suggested in the issue referenced above, i am now using dbus-run-session. The icon of riot-desktop is still missing. i want to note that the icon of telegram-desktop works fine (is that application also electron based?) 
Terminal Output launching riot-desktop:
```
node[7908]: pthread_create: Invalid argument
No update_base_url is defined: auto update is disabled
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```

**Comment by ProjectMoon** [comment] 2020-05-25 17:23
What system tray application are you using?

**Comment by ProjectMoon** [comment] 2020-05-25 20:33
I am able to reproduce this issue with both Awesome window manager and stalonetray (standalone sys tray). I use `nm-applet` as a control. Starting `nm-applet` makes it appear in these X-based trays, but starting Riot does not make it appear in the tray. However, Riot does appear in Waybar (usually used with Sway) and KDE. Off the top of my head, this sounds like some kind of dependency issue, where a library that is is needed for integration with these trays is not present. Not sure if it would need to be a build-time dependency or runtime only.

**Comment by ProjectMoon** [comment] 2020-05-26 10:45
It might also be some incompatibility with these trays and newer versions of electron. Hard to say.

**Comment by Johnnynator** [comment] 2020-05-26 13:58
>  i want to note that the icon of telegram-desktop works fine (is that application also electron based?)
Telegram is Qt based.

**Comment by ProjectMoon** [comment] 2020-06-02 20:40
This looks like a more up-to-date upstream issue for this problem: https://github.com/vector-im/riot-web/issues/12518

Summary basically is: Electron 8 is based on a newer version of Chromium, which changes how the tray icon works. I guess KDE handles that, while other sys trays do not.

**Comment by ProjectMoon** [comment] 2020-06-02 21:16
For anyone not able to see the tray icon, perhaps try using https://git.sr.ht/~steef/snixembed. I have not had any luck in getting it to work yet, but at least one person in the upstream issue said it solved their problem.

**Comment by ProjectMoon** [comment] 2020-06-02 22:36
OK, after much testing, snixembed is the "solution" here. It works with awesome wm and stalonetray. I will create an XBPS package for snixembed.

This is an upstream issue though, in the window managers. They need to update themselves to support the StatusNotifierItem APIs for Electron 8+ applications to work properly with the system tray.

**Comment by ProjectMoon** [comment] 2020-06-04 22:15
`snixembed` is now available in the Void repositories. Anyone using i3, awesome, etc should try installing and configuring it to get Riot's icon to show up in the system tray.

**Comment by lschmelting** [comment] 2020-06-06 16:17
I can comfirm that the icon is showing up again using dwm window manager.

**Comment by 2xsaiko** [comment] 2020-06-08 20:45
Does executing

    source "$HOME/.dbus/session-bus/$(cat /var/lib/dbus/machine-id)-${DISPLAY:1}"
    export DBUS_SESSION_BUS_ADDRESS

and then running the program through the terminal make the icon appear? I have a similar issue, not sure if it's related, but that makes it work.

In my case, DBUS_SESSION_BUS_ADDRESS doesn't get set which causes Discord and Spotify to not be able to send notifications, create a tray icon, and provide media player controls.

Obviously, that's a workaround but I'm not sure how to get that variable to be auto exported.

Using SDDM and Plasma desktop with X11.

**Comment by ProjectMoon** [comment] 2020-06-08 20:53
There are two different issues, both with similar symptoms:
 * Using SDDM to log in to KDE X11 does not set the DBUS_RUN_SESSION variable. This can be fixed by running KDE in `dbus-run-session` or something similar.
* Electron dropped support for XEmbed. This is what `snixembed` fixes. However, some people re-ported the XEmbed to the newer versions of Electron, so `snixembed` shouldn't be necessary that long.

**Comment by Fluffkin** [comment] 2020-06-09 16:40
@2xsaiko Yes the source / export trick does work for me
My problem is AppImage programs not finding libappindicator on dbus (not the snixembed problem)

> In my case, DBUS_SESSION_BUS_ADDRESS doesn't get set which causes Discord and Spotify to not be able to send notifications, create a tray icon, and provide media player controls.
> 
> Obviously, that's a workaround but I'm not sure how to get that variable to be auto exported.

It's a cludge, but you can edit the desktop file in /usr/share/xsessions and add "dbus-run-session" to the Exec line. So mine is now "Exec=dbus-run-session /usr/bin/startplasma-x11".

**Comment by ProjectMoon** [comment] 2020-06-09 17:00
It should be noted that will be patched into the KDE 5.19 release.

**Comment by Johnnynator** [comment] 2020-06-09 17:25
KDE 5.19 Should land in the repo somewhen tromorrow (if I don't see anything broken)

**Comment by Fluffkin** [comment] 2020-06-15 12:55
KDE 5.19 Doesn't seem to fix the problem for me.

"Riot" and "Wire" won't show a systray icon unless I run the session with "dbus-run-session" (which worked fine in 5.18), but adding dbus-run-session to the startplasma-x11 exec line now seems to cause other problems in KDE.

**Comment by ericonr** [comment] 2020-12-13 21:46
I believe this can be closed?

**Comment by Johnnynator** [comment] 2020-12-13 21:51
Yeah, I suppose so.

**Closed by Johnnynator** 2020-12-13 21:51 UTC
Labels: bug, electron 🤮
