### ISSUE TITLE
Can libgccjit be included in the --enable-languages of gcc?

### ISSUE THREAD

**Issue by xianwenchen** [void-linux/void-packages#29080] opened 2021-02-26 21:00 UTC
libgccjit is an experimental just-in-time (jit) library.

To enable it, one only needs to add jit to the `--enable-languages` option when configuring it [0].

Having libgccjit is good because it is a tool that has potentials. 

One potential is that the gccemacs branch is probably going to be merged into emacs 28 in the future [1]. libgccjit is required by the gccemacs. gccemacs uses libgccjit to compile emacs lisp to greatly speed up emacs lisp.

[0] https://gcc.gnu.org/onlinedocs/jit/internals/index.html#working-on-the-jit-library

[1] https://akrl.sdf.org/gccemacs.html#org45ca34b

**Comment by ericonr** [comment] 2021-02-26 21:28
Duplicate of #24240 

Being packaged in #28785

**Closed by ericonr** 2021-02-26 21:28 UTC
