### ISSUE TITLE
Package request: kio-fuse

### ISSUE THREAD

**Issue by QuadPiece** [void-linux/void-packages#36431] opened 2022-03-31 17:04 UTC
Repo: [kio-fuse](https://github.com/KDE/kio-fuse)

kio-fuse provides fuse compatibility for kio. Without this package non-KDE applications generally cannot access remote files via tings like the dolphin manager.

For example if you use the dolphin file manager to access a server over sftp and then attempt to play a video file with mpv, it will fail if kio-fuse is not available.

**Comment by classabbyamp** [comment] 2022-06-25 07:48
duplicate of #34071

**Closed by classabbyamp** 2022-06-25 07:48 UTC
Labels: request
