### ISSUE TITLE
Something wrong with nvidia340 when installing qt5-devel-5.14.2

### ISSUE THREAD

**Issue by AngryPhantom** [void-linux/void-packages#21993] opened 2020-05-15 19:23 UTC
# System
Fresh install of Void Linux with XFCE + nvidia340 driver

* xuname: Void 5.4.41_1 x86_64 AuthenticAMD uptodate rrFFF

* packages: nvidia340-340.108_3 or qt5-devel-5.14.2_3

### Steps to reproduce the behavior
Install **qt5-devel** package (needed to compile the upstream version of octoxbps)

### Expected behavior
Should be installed

### Actual behavior
```
sudo xbps-install qt5-devel
nvidia340-340.108_3: broken, unresolvable shlib `libnvidia-ml.so.1'
Transaction aborted due to unresolved shlibs.
```

**Comment by st3r4g** [comment] 2020-05-15 19:33
seems a duplicate of https://github.com/void-linux/void-packages/issues/20252

**Comment by AngryPhantom** [comment] 2020-05-15 19:44
@st3r4g 

Oh... So do I have to do this?

```
xbps-remove nvidia340
xbps-install libglvnd
xbps-install nvidia340 libglvnd-devel
```

**Comment by AngryPhantom** [comment] 2020-05-15 19:45
Will it break again somehow after kernel/dkms update ?..

**Comment by st3r4g** [comment] 2020-05-15 19:49
That's a manual hack that I tried on a temporary chroot, once you manage to install `libglvnd-devel` things should be ok, and it shouldn't break on update. But really this is a bug so keep the issue open regardless

**Comment by AngryPhantom** [comment] 2020-05-15 19:57
@st3r4g Thank you very much.

**Comment by AngryPhantom** [comment] 2020-05-15 19:58
But do other devs know of this problem? Someone who maintains that metapackage I mean.

**Comment by fosslinux** [comment] 2020-05-16 04:48
Well, they will be, now that you have opened this bug report :)

**Comment by ericonr** [comment] 2021-01-20 20:29
No longer relevant.

**Closed by ericonr** 2021-01-20 20:29 UTC
