### ISSUE TITLE
xbps-alternatives for tar don't seem to work

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#18692] opened 2020-01-31 17:13 UTC
Trying to build `linux5.4` here now fails with `--owner=0` not supported. This is because when I enter the chroot the alternative for `tar` is still `bsdtar`, despite `tar` (gtar) being in the hostmakedepends. So it seems that the automatic switching to the most recently installed alternative does no longer work right.

**Comment by Chocimier** [comment] 2020-01-31 20:39
We probably do not want bsdtar to be tar, because of incomplatible arguments.

> automatic switching to the most recently installed alternative does no longer work right

I would prefer just installing another provider not to change manually selected alternative.

**Comment by pullmoll** [comment] 2020-02-05 17:40
See also #18827 which seems a problem of that kind.
Something did change about xbps-alternatives in the recent updates?

**Comment by q66** [comment] 2020-02-05 17:55
The problem is here is that @xtraeme recently made tar an alternative, for both bsdtar and GNU tar (whose binary is now called gtar)- As bsdtar is a bootstrap package, the alternative is set to it by default, and it will not switch anything when you install GNU tar on top.

**Comment by yopito** [comment] 2020-02-07 05:48
fixed in 9816b3d831a9e3ed744865fdd139a138a7ce904e .  
My test case: packaging kdevelop 5.5.0 that was affected the same way is now fine

**Comment by xtraeme** [comment] 2020-02-07 09:26
FTR, this issue has been fixed in xbps master: https://github.com/void-linux/xbps/commit/94b56d753927672bb4a0128fff22f7ca3a129b2f

**Closed** 2020-02-07 09:25 UTC
Labels: bug
