### ISSUE TITLE
qt5-webengine: broken on musl

### ISSUE THREAD

**Issue by joeblo1** [void-linux/void-packages#2368] opened 2018-09-04 20:04 UTC
### System

* xuname:  Void 4.18.5_1 x86_64-musl GenuineIntel uptodate rDDDDDF
  *output of ``xuname`` (part of xtools)*
* package:  falkon
  *affected package(s) including the version*

### Expected behavior
...to not flicker? :P 

### Actual behavior
flickering black non-stop

### Steps to reproduce the behavior
Happened after update, have cleared mesa shaders & falkon folder in ~/.cache already, don't know if its just me or not. Sorry I'm not super knowledgeable about this stuff. I have tried creating another user to see if that would change anything but it did not.

**Comment by joeblo1** [comment] 2018-09-04 20:08
Found this 'gdb' thing in another thread related to falkon, hope this output helps. Anything else I can do?

```
GNU gdb (GDB) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from falkon...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/falkon 
[New LWP 19310]
qt5ct: using qt5ct plugin
[New LWP 19311]
[New LWP 19312]
[New LWP 19317]

Thread 2 "QXcbEventReader" received signal ?, Unknown signal.
[Switching to LWP 19310]
__cp_end () at src/thread/x86_64/syscall_cp.s:29
29	src/thread/x86_64/syscall_cp.s: No such file or directory.
(gdb)
```

**Comment by Johnnynator** [comment] 2018-09-04 20:16
That gdb output is rather useless. Also your GPU may be intresting.

**Comment by joeblo1** [comment] 2018-09-04 20:16
QXcb.... huh... this must have something to do with glide64mk2 not working in mupen64plus then! 
#2369

**Comment by joeblo1** [comment] 2018-09-04 20:17
```
00:00.0 Host bridge [0600]: Intel Corporation Core Processor DRAM Controller [8086:0044] (rev 02)
	Subsystem: Hewlett-Packard Company Device [103c:172a]
	Kernel modules: intel_agp
00:02.0 VGA compatible controller [0300]: Intel Corporation Core Processor Integrated Graphics Controller [8086:0046] (rev 02)
	DeviceName: 32
	Subsystem: Hewlett-Packard Company Device [103c:172a]
	Kernel driver in use: i915
	Kernel modules: i915
```

Does this help?

**Comment by Hoshpak** [comment] 2018-09-04 20:26
I don't think this error and the one with the emulator are related, the emulator just needs a rebuild. It would be interesting if you get the same issues with `qutebrowser` and the `webengine` backend. This way we could at least know if this only happens with falkon or the underlying webengine is causing issues.

**Comment by joeblo1** [comment] 2018-09-04 20:29
Okay, I will try qutebrowser. I tried doing a rebuild of falkon but that didn't work. I haven't yet tried a rebuild of mupen64plus though.

**Comment by joeblo1** [comment] 2018-09-04 20:31
Yep, a bunch of errors like this:
ERROR: Renderer process crashed
ERROR: Renderer process crashed
ERROR: Renderer process crashed
ERROR: Renderer process crashed

"error loading data" on the web bar. In Falkon it says "Failed loading page"

**Comment by Hoshpak** [comment] 2018-09-04 20:45
You could try to start it with `QT_QUICK_backend=software`. That helped with an earlier bug in mesa which should have been resolved in the meantime.

Unfortunately, the qt-webengine often causes issues on musl. I hope some other people running musl systems will find the time to try it on their systems so we can at least see if it's related to a specific hardware configuration or not. You could use chromium in the meantime, that's usually well tested on musl systems.

**Comment by joeblo1** [comment] 2018-09-04 20:52
Firefox seems to work for now, thank you though. I really prefer Falkon over everything else, but Firefox works for now. QT_QUICK_backend=software does not seem to change the issue on falkon & qutebrowser either...

**Comment by newbluemoon** [comment] 2018-09-05 05:48
Tested on x86_64-musl (mesa-ati-dri) and on armv7l-musl (mesa-vc4-dri), both systems fully updated, same result as above. :(

**Comment by Hoshpak** [comment] 2018-09-05 09:40
I installed a VM with the musl version in the meantime. Since issues like that on musl are often caused by the smaller default stack size on musl, I recompiled musl with the `bigstack` option. However that also didn't change anything. So it seems to be yet another issue.

**Comment by joeblo1** [comment] 2018-09-07 11:50
No pull-requests that may fix this yet? :<

**Comment by Hoshpak** [comment] 2018-09-07 12:27
Don't expect one anytime soon. The webengine has been broken on musl for most of the time and nobody even knows what the exact issue is yet. The people taking care of browsers have more than enough to do to ensure that Firefox and Chromium both work on musl (particularly Chromium needs heavy patching with each update).

**Comment by joeblo1** [comment] 2018-09-07 12:33
Do you think alpine linux has already encountered this issue? Perhaps we can ask them

**Comment by joeblo1** [comment] 2018-09-07 12:38
Why hasn't QT5 been updated in the Void repos? We're still at 5.10, perhaps upgrading to 5.11 would solve the issue since webengine is part of QT5 I think... but I assume a bunch of patches may have to be written, I don't really know. If I had more info I might be able to try writing the patches myself, is there a reason we're still at 5.10?

**Comment by MirceaMx** [comment] 2018-09-07 12:42
Please read: https://github.com/void-linux/void-packages/issues/1952

**Comment by joeblo1** [comment] 2018-09-07 12:42
thanks MirceaMx.

**Comment by MirceaMx** [comment] 2018-09-07 12:43
You're very welcome.

**Comment by maxice8** [comment] 2018-12-27 09:34
qt5 was updated ? what is the status on this ?

**Comment by Johnnynator** [comment] 2018-12-27 18:43
@maxice8 the tests before the merge showed that it still was broken.

**Comment by pullmoll** [comment] 2018-12-27 18:46
We should probably revbump it for qt5-5.11.3 and can use e.g. qtcreator1 to see if it works.

**Comment by Cogitri** [comment] 2018-12-28 12:43
FWIW, this also happened on my computer with plex-media-player.

**Comment by MrSenshi** [comment] 2019-04-15 15:43
It seems like the issue does not exist in Alpine, it has been patched. 
https://git.alpinelinux.org/aports/tree/community/qt5-qtwebengine?h=master

**Comment by Johnnynator** [comment] 2019-04-15 15:54
@MrSenshi Yes, We are aware of this, but the last time I tried with these patches I either missed one ore broke smth else, but it still resulted in a broken qt5-webengine. I haven't had much time since then to debug it or run another clean build since it takes ages to build. I will try to get back to the qt5.12 update in the next few weeks.

**Comment by Eluminae** [comment] 2019-09-24 09:17
I'm still suffering of this crashes. Is there any news about it ? Can we help in someway ? It seems a qt issue, but are the devs aware of this ?

**Comment by Johnnynator** [comment] 2019-09-24 09:36
The problem most likely resides in chromium, which does not support (and probably never will) musl, so we (and other musl distros have the fun to patch it all the time). Qt5 also doesn't officially support musl. Also Alpine Linux also struggles with qt5-webengine https://gitlab.alpinelinux.org/alpine/aports/issues/10405

> I'm still suffering of this crashes. Is there any news about it ? Can we help in someway ?

Sure, send us a patch that fixes it :). But well otherwise there is probably nothing you can do currently.

**Comment by Cogitri** [comment] 2019-09-24 10:35
Yup, and the chromium codebase is a pretty complex beast, so I've settled with using QtWebengine stufff in Flatpak for now :/

**Comment by stef** [comment] 2019-11-09 18:16
i managed to fix this in alpine with this: https://github.com/alpinelinux/aports/pull/11922/files

**Comment by Hoshpak** [comment] 2019-11-10 10:08
Thanks, that looks promising. Could anyone test it with out qt5 package and create a PR? Maybe @q66 ? I just don't have the time to do a full qt5 build right now.

**Comment by q66** [comment] 2019-11-11 00:32
I suggest we add this for 5.14 or next incremental release of 5.13, whichever comes sooner

**Comment by Johnnynator** [comment] 2019-11-12 00:23
I did apply the patch on qt5.14 (+ some other chromium patches) and it seems to work

https://i.imgur.com/0jpOBet.png

**Comment by mintsuki** [comment] 2019-11-12 04:42
Hi, I have the same issue here. Is it possible for this patch to be applied to a 5.13.x revision? If not, how long would it be until 5.14 is released?

**Comment by Johnnynator** [comment] 2019-11-12 10:27
The 5.14 release is end of November. So proably won't land in the repo before Early December.
https://wiki.qt.io/Qt_5.14_Release

If anyone wanna fix it for 5.13 feel free to do so, you will most likely also need this patch  https://github.com/Johnnynator/void-packages/blob/a8e26ae892253abe46c6e5277c54208457e277db/srcpkgs/qt5-webengine/patches/sandbox-sched_getparam.patch

**Comment by mintsuki** [comment] 2019-11-12 23:47
This works for me on musl, I opened a pull request, hope everything is alright.

**Comment by mintsuki** [comment] 2019-11-13 20:19
Thanks for merging, the package still does not seem to have reached the void x86_64-musl repository as the builtbot seems to have gotten stuck. It works on x86_64-glibc though.

https://build.voidlinux.org/builders/x86_64-musl_builder/builds/24013/steps/shell_3/logs/stdio

It keeps saying `=> WARNING: qt5-script-dbg-5.13.2_2: binpkg is being created, waiting for 1s...`

**Comment by mintsuki** [comment] 2019-11-14 00:40
Apparently it managed to finish building now after so many hours :)

**Comment by mintsuki** [comment] 2019-11-14 02:32
Even after applying this patch, qt5-webengine crashes on certain webpages, such as https://riot.im/app/
I did not have time to take a more in depth look, and I don't know if this issue will also affect 5.14, in which case it might be worth looking into.
I also don't know if perhaps opening another issue for this would be more appropriate.

**Comment by ericonr** [comment] 2020-05-11 22:13
@mintsuki what's your GPU? There's a bug with 5.14, on Intel HD 4000/3000, where it crashes on pages like old.reddit.com .

@Johnnynator can this one be closed? webengine doesn't seem to have any musl specific issues anymore.

**Comment by Johnnynator** [comment] 2020-05-11 23:45
Yeah, this specific issue should be fully resolved with qt5.14 in the repo.

**Closed by Johnnynator** 2020-05-11 23:45 UTC
Labels: bug
