### ISSUE TITLE
Bug in glib update 2.74.0

### ISSUE THREAD

**Issue by bugcrazy** [void-linux/void-packages#39390] opened 2022-09-20 16:34 UTC
### Is this a new report?

Yes

### System Info

Void 5.18.19_1 x86_64 AuthenticAMD notuptodate rrrmDDDDDDDDDDDDDDDDDDDDFFFFFF

### Package(s) Affected

glib-2.74.0_1.x86_64.xbps

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=266466

https://github.com/lxqt/lxqt-build-tools/commit/4991811d9212ec1176af6d1cbe88aa37efad4836

### Expected behaviour

The updated package should maintain compatibility with applications that use it, but do not start, after updated.

### Actual behaviour

Due to changes in the source code in the last version, applications do not start, they are broken.

FreeBSD bugzilla and LXQT commit explain a little of the problem.

### Steps to reproduce

Open chromium at the terminal

Returns this error, it is not started, other applications do not return error, simply do not start:

[19642:19642:0920/025933.330207:ERROR:browser_main_loop.cc(267)] GLib: g_log_set_writer_func() called multiple times

**Comment by paper42** [comment] 2022-09-20 16:58
> Returns this error, it is not started, other applications do not return error, simply do not start:

I can not reproduce the issue with chromium, what are "other applications"?

**Comment by bugcrazy** [comment] 2022-09-20 17:47
> > Returns this error, it is not started, other applications do not return error, simply do not start:
> 
> I can not reproduce the issue with chromium, what are "other applications"?

These are these software, do not start: lxdm; firefox; abiword; falkon; bleachbit; devedeng, any application that uses GTK3 and GTK4 or gnome software.

**Comment by lxlml** [comment] 2022-09-20 18:01
I also have a issue where GIMP where i get a seg fault when using the text tool is due to glib.

From this [report](https://gitlab.gnome.org/GNOME/gimp/-/issues/8631), downgrading glib fixes the [problem](https://youtu.be/4oA8mhTbjiQ?t=41).

**Comment by paper42** [comment] 2022-09-20 18:23
I can not reproduce even a single issue from the ones you listed, but this seems to be a widespread issue, so I will revert the glib update.

**Comment by paper42** [comment] 2022-09-20 18:34
@lxlml can you reproduce the issue with some of the software @bugcrazy listed?

**Comment by lxlml** [comment] 2022-09-20 18:41
Firefox and bleachbit are fine on both my laptop and desktop

Desktop 
Void 5.19.9_1 x86_64 GenuineIntel notuptodate rrmDFFFFFFFFFF
de x-cinnamon

Laptop
Void 5.19.9_1 x86_64 AuthenticAMD notuptodate rrmFFFFFFFFFF
de Gnome Wayland

**Comment by paper42** [comment] 2022-09-20 18:49
I would like to wait a bit for other people to confirm this issue, so far only you have an issue with gimp (that I can't reproduce) and @bugcrazy has an issue with a lot of software (that noone else could reproduce so far).

**Comment by mojamuto** [comment] 2022-09-20 21:46
firefox and bleachbit are working fine on my computers, I only have the gimp problem that lxlml mentions.

**Comment by paper42** [comment] 2022-09-20 22:16
not reproducible and if firefox and chromium were broken, we would get much more reports than one 24 hours after the update, closing

**Closed by paper42** 2022-09-20 22:16 UTC
Labels: bug, needs-testing
