### ISSUE TITLE
Package request: mulvad vpn

### ISSUE THREAD

**Issue by sae13** [void-linux/void-packages#41757] opened 2023-01-20 13:48 UTC
### Package name

mullvad

### Package homepage

mullvad.net

### Description

It has .Deb package I extract it in /opt but it does not work

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

No

**Comment by paper42** [comment] 2023-01-20 16:08
Duplicate of #21154

**Closed** 2023-01-20 16:08 UTC
Labels: request
