### ISSUE TITLE
 rxvt-unicode copy/paste 

### ISSUE THREAD

**Issue by doleovit** [void-linux/void-packages#30958] opened 2021-05-17 20:35 UTC
### System

* xuname:  
  Void 5.11.21_1 x86_64 GenuineIntel notuptodate rrFF

* package:  
  rxvt-unicode-9.26_12

### Expected behavior

.Xresources, example:
 
*.keysym.Control-c: eval:selection_to_clipboard
*.keysym.Control-v: eval:paste_clipboard

copy/paste. worked before the update.

same with:

*.keysym.Shift-Control-V: eval:paste_clipboard
*.keysym.Shift-Control-C: eval:selection_to_clipboard 

### Actual behavior

after the update to 9.26 this no longer works. maybe some "perl-thing"?

anyway, thanks @ the entire team. it's been a long time since the last irc chat.

**Comment by ericonr** [comment] 2021-05-17 21:08
@leahneukirchen

**Comment by leahneukirchen** [comment] 2021-05-18 15:24
Can't reproduce, I used

```
urxvt -pe eval -name foo -xrm 'URxvt.keysym.Control-v: eval:paste_clipboard' -xrm 'URxvt.keysym.Control-c: eval:selection_to_clipboard'
```

and it worked as intented.

**Comment by doleovit** [comment] 2021-05-19 11:45
your interactive command worked. so i did some trial/error attempts. again. in addition to:

```
*.keysym.Control-c: eval:selection_to_clipboard
*.keysym.Control-v: eval:paste_clipboard
```

i had

```
*.keysym.Control-Meta-c: builtin-string:
*.keysym.Control-Meta-v: builtin-string:
```
in [.xresources](https://github.com/doleovit/voidbspwm/commit/2e05faf886ef38c040e4cf168742d3c72d3d43d2#diff-9a38bcf40e368ac00497ad8865c138ae9d0144f9c2dc8bf13bfff1af0e16f72eR32).

after

```
!*.keysym.Control-Meta-c: builtin-string:
!*.keysym.Control-Meta-v: builtin-string:
```
```
$ xrdb -merge ~/.Xresources
```
and
 
```
*.keysym.Control-Meta-c: builtin-string:
*.keysym.Control-Meta-v: builtin-string:
```
```
$ xrdb -merge ~/.Xresources
```

`ctrl+c` and `ctrl+v`  is working again. 

a causal connection with the settings above - no idea. the old unedited `.xresources` file and the current `.xresources` file are identical (diff, cmp). thus it had nothing to do with faulty settings & right after the urxvt - update,  i've run `xrdb -merge`.. + a reboot. anyway, thx for your article on `xsecurelock`, which i discovered + implemented one day before the update. synchronicity. thx 4 

everything, 
d.

**Comment by doleovit** [comment] 2021-05-19 14:51
sry. this was not **the** solution. after a reboot, everything was like before. again trial/error. 

"result" (?): this syntax in `.xresources`:
```
*.keysym.Control-c: eval:selection_to_clipboard
*.keysym.Control-v: eval:paste_clipboard
```

doesn't work consistently anymore since the last update.

```
URxvt.keysym.Control-c: eval:selection_to_clipboard
URxvt.keysym.Control-v: eval:paste_clipboard
```
is working - even after another reboot. strange behavior.

**Comment by doleovit** [comment] 2021-05-19 21:58
after more than a year, i know that i knew nothing about my terminal emulator. maybe i wasn't interested enough to dive deeper into urxvt. but there was so much other work to do. `appres URxvt` , `appres urxvt`, `appres Xft` .. and whatnot (horrible) + the man "book" showed me a better picture which resources apply, in which order & as a result: "do not use wildcards all over the place". this worked before the update, but i guess the current behavior is more correct. frustrating. you think you learned something, but it turns out - nope. linux can be like f.. zen. "keep your anfängergeist (beginner's mind)". 

i don't know if this issue can ble closed now, or not.  i'll have to leave that to you. good night and sry for wasting time.

**Comment by leahneukirchen** [comment] 2021-05-19 22:05
I'm not sure it's an actual regression or just some configuration change that gets interpreted differently. But since the feature works, I'll close this for now.

**Closed by leahneukirchen** 2021-05-19 22:05 UTC
