### ISSUE TITLE
qutebrowser draws entire window black

### ISSUE THREAD

**Issue by wes1138** [void-linux/void-packages#3625] opened 2018-10-10 17:52 UTC
### System

* xuname:

Void 4.18.12_2 x86_64 GenuineIntel notuptodate rFFF

The "notuptodate" is due to the packages I downgraded so that I can use my
browser to communicate this issue.  `xbps-install -Mun`:

    MesaLib-devel-18.2.2_2 update x86_64 https://alpha.de.repo.voidlinux.org/current 2433407 178180
    libEGL-18.2.2_2 update x86_64 https://alpha.de.repo.voidlinux.org/current 232784 82304
    libGL-18.2.2_2 update x86_64 https://alpha.de.repo.voidlinux.org/current 21757108 6082256
    libGLES-18.2.2_2 update x86_64 https://alpha.de.repo.voidlinux.org/current 52616 10712
    libOSMesa-18.2.2_2 update x86_64 https://alpha.de.repo.voidlinux.org/current 7581496 2167168
    libgbm-18.2.2_2 update x86_64 https://alpha.de.repo.voidlinux.org/current 55784 19648
    libglapi-18.2.2_2 update x86_64 https://alpha.de.repo.voidlinux.org/current 198784 19356
    libxatracker-18.2.2_2 update x86_64 https://alpha.de.repo.voidlinux.org/current 3501984 1150116
    mesa-intel-dri-18.2.2_2 update x86_64 https://alpha.de.repo.voidlinux.org/current 13384529 3224328

* package:  
  The packages listed above in `xbps-install -Mun` output seem to be causing
  the issue, but it is `qutebrowser` that I notice is affected (qutebrowser
  from the latest commit, as well as the currently packaged version).

### Expected behavior

qutebrowser draws window contents.

### Actual behavior

qutebrowser draws window entirely black.

### Steps to reproduce the behavior

Run qutebrowser (from source tree or from the void package) with the above
`*18.2.2_2*` packages installed.

### Remarks

I tried this with the intel driver (`xf86-video-intel`) as well as the
modesetting driver with identical results.

I thought for a moment that issue #3597 might be related -- similar sounding
description, same packages were to blame, and perhaps the common thread of
`qt5*` -- but that has now been resolved o_O

**Comment by maxice8** [comment] 2018-10-10 18:31
can't reproduce it here

**Comment by wes1138** [comment] 2018-10-10 20:41
Thanks for looking into it.  Here is a bit more system info in case it will be
helpful.  Computer is an X220T.  Graphics card:

`lspci`:

    ...
    00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
	...

qutebrowser does not notice anything is wrong (no unusual log messages).  Also
nothing unusual in xorg logs.  Window manager is i3-gaps.

**Comment by wes1138** [comment] 2018-10-10 20:52
I have taken the window manager out of the equation (issue persists if I exec
browser from .xinitrc).  Sorry for spamming the comments.  Let me know if
there is anything else I can do to help.

**Comment by chriscamacho** [comment] 2018-10-10 23:47
I've noticed this before with QT applications using Intel hardware (and possibly others)

if I run openscad I get a blank window

however if I run

LIBGL_ALWAYS_SOFTWARE=1 openscad

it works fine, this was previously working (well) however this is not the first time this bug has happened (eventually resolving itself after an update)

possibly as a result of recent mesa update ??

**Comment by wes1138** [comment] 2018-10-11 01:05
That worked!  Thanks Chris!

So far, performance doesn't seem too bad when running qutebrowser this way.
Just wondering: did you notice a big performance hit in openscad?

**Comment by chriscamacho** [comment] 2018-10-11 01:19
not particularly but its a flat shaded bunch of triangles (not 1000's in a 3d scene in say a game)

NB this is not a fix just a workaround !

**Comment by TeddyDD** [comment] 2018-10-11 11:10
I can confirm, back screen on Intel integrated graphics.

Probably the same issue as here #1033

Software rendering works
`env QT_QUICK_BACKEND=software qutebrowser`

**Comment by non-Jedi** [comment] 2018-10-11 22:08
I originally filed #1033 and am getting same problem again. Possible that a recent update to mesa undid whatever fixed it before?

**Comment by chriscamacho** [comment] 2018-10-12 20:06
oh the horror, also noticed 2048-qt is effected by this.....

**Comment by chriscamacho** [comment] 2018-10-22 13:15
On my system, qutebrowser, 2048-qt and OpenSCAD are now working as of a recent update of mesa....

**Comment by TeddyDD** [comment] 2018-10-22 14:13
It's fixed for me as well. See ya next time mesa update will break qutebrowser

**Closed** 2018-10-29 18:51 UTC
