### ISSUE TITLE
Package Request: Wire Desktop 

### ISSUE THREAD

**Issue by Seeder101** [void-linux/void-packages#5215] opened 2018-11-29 11:14 UTC
Hi void community. 
if kindly and possible to package the wire desktop client it would be nice.  it's an electron app here is the source code https://github.com/wireapp/wire-desktop it provides a binary as well. 
the license is GPL v3 

Thanks

**Comment by youngjinpark20** [comment] 2019-03-09 07:09
closed with https://github.com/void-linux/void-packages/pull/9543

**Comment by maxice8** [comment] 2019-03-09 20:30
@youngjinpark20 add

closes #ISSUENUM

in the commit, so the issue is closed when the commit is merged.

**Closed by maxice8** 2019-03-09 20:30 UTC
Labels: electron 🤮, request
