### ISSUE TITLE
Package request: Brave

### ISSUE THREAD

**Issue by notramo** [void-linux/void-packages#5444] opened 2018-12-05 21:13 UTC
https://brave.com/

**Comment by CameronNemo** [comment] 2018-12-06 00:43
Is this open source?

**Comment by Duncaen** [comment] 2018-12-06 01:01
Yes opensource, once based on electron, now a chormium fork, both ways have a very high maintenance burden for void.

https://github.com/brave/brave-browser
https://github.com/brave/brave-core

**Comment by PrinceKael** [comment] 2019-04-09 07:12
I was about to raise a package request for this but then I found this. Has anyone started on this? I'd do it myself because I have spare time but I don't really know how to do it. Does my comment "bump" this thread or should I make a new one?

**Comment by Anachron** [comment] 2019-04-09 07:23
There seems to be a release each and every single day.

Build instructions:
https://github.com/brave/brave-browser/wiki/Linux-Development-Environment

**Comment by yakthungba** [comment] 2019-04-11 10:59
It doesn't feel right to use Chromium as an alternative to Firefox. It would be really cool to have this browser, more privacy friendly than Chromium.

**Comment by m1m3-50** [comment] 2019-04-26 06:56
I am trying to build a proper package using xbps-src for at least past month. So far I got stuck with 5+GB binary (due to not stripped dependencies). I'd be more than happy if somebody wanted to help me with it. I tried to get some more info on their official [subreddit](https://www.reddit.com/r/brave_browser/comments/b7zgo3/compiling_from_source_and_binary_size/) already.

@Anachron, I believe it'd be best to only put **Release** versions into repository, these do not come daily :)

**Comment by Jackojc** [comment] 2020-01-26 19:04
Any updates on this?

**Comment by the-maldridge** [comment] 2020-01-27 02:15
There's really a moratorium on any more forks of the big two browsers right now.  The effort and upkeep to package, cross compile, and then debug the resulting binaries is a significant maintenance burden for all involved, all for behavior that can usually be obtained by starting up a more standard browser with some flags set (note this point is not specific to this request).

While its not impossible for yet another chromium fork to be accepted, it is very very unlikely.  Please keep this in mind when considering attempting to become a maintainer of a browser fork.

**Comment by CameronNemo** [comment] 2020-01-27 06:10
@the-maldridge Thoughts on applying some of those privacy or security flags OOTB?

**Comment by the-maldridge** [comment] 2020-01-27 06:37
Void's policy has long been understood to not patch or alter the upstream provided configuration of software.  We distribute as close to what upstream provides as possible.

**Comment by hfel** [comment] 2020-01-30 01:19
Brave is quite unique in its user-controlled ads system, ability to directly support content creators, cryptocurrency and built-in Tor mode, something that cannot be summoned by setting flags or installing extensions on Chromium alone.

**Comment by anjandev** [comment] 2020-04-04 02:05
I want to try brave as well on my void system. However, I think the concerns by the core team are valid. May I suggest that we create a seperate git repository with a brave template for xbps-src that people can build themselves?

**Comment by the-maldridge** [comment] 2020-04-04 02:07
You may suggest it, but it won't happen.  Void has a single repo, which is the one that xbps-src reads from.  This is a fundamental difference in goals between Void and other projects such as Arch with its AUR.

For software outside of the repos I would suggest using technologies like AppImage or keeping the software in /usr/local, which xbps won't interfere with.

**Comment by anjandev** [comment] 2020-04-04 02:10
@the-maldridge I was just suggesting a template file that people can copy to their `srcpkgs` folder.

**Comment by the-maldridge** [comment] 2020-04-04 02:17
I think the problem you'd run into with that is that Brave is a firefox sized package.  Its not just a single file you can copy around, its a file and a stack of associated patches, and potentially even patched libraries.  You're welcome to try if it interests you, but its a huge undertaking to package an entire browser, and even more so to package something that's been forked and patched already.

**Comment by gspe** [comment] 2020-05-21 08:49
@the-maldridge @Duncaen 
Why not replace Opera with Brave?
1. better license:
  - Opera has `license="custom:Proprietary"`
  - Brave has `license="MPL-2.0"`
2. better privacy and security for end user
  - Opera is closed source
  - Brave is open source 

For better comparison take a look at this video:
https://www.youtube.com/watch?v=PedU3mNm-3Y

**Comment by Duncaen** [comment] 2020-05-21 09:25
There is no point in replacing, this is not about size of the resulting package.

The objections are more about brave being another chromium fork, meaning it requires heavy patching, maintenance and hours of compile time.

**Comment by hfel** [comment] 2020-05-21 15:40
> There is no point in replacing, this is not about size of the resulting package.
> 
> The objections are more about brave being another chromium fork, meaning it requires heavy patching, maintenance and hours of compile time.

Can you explain to the technically illiterate in this matter why being a chromium fork which one would presume is still released by the developers in a form where all the necessary components are present requires more maintenance than non-forks-of-chromium?

**Comment by the-maldridge** [comment] 2020-05-21 15:49
Being a chromium fork means it inherits all the problems that chromium had and brings its own with it.  Hours of compile time, needing to be patched regularly with custom code, and significant maintenance overhead are all issues that exist within Chromium itself.  Brave iirc also brings a surprisingly hostile developer team which we have no intentions of engaging.

**Comment by Duncaen** [comment] 2020-05-21 15:54
There can be 100 requests for brave, the problem is you have to find someone who actually wants to maintain the package and then you can start trying to convince us if its worth to be included in the repositories or not.

There is no point in arguing about brave anymore until someone actually manages to get a working build from source.

**Comment by hfel** [comment] 2020-05-21 16:13
Thank you both for the thorough explanations, I understand the issues now. Although not directly on topic and just out of curiosity, is Firefox easier to maintain than chromium?

**Comment by Duncaen** [comment] 2020-05-21 16:23
They are both not easy to maintain, IMHO firefox is a little bit easier because it builds faster, but the increasing usage of rust makes it harder from release to release because now you also need fix issues in random cargo crates and each new crate slows down the build times again.

**Comment by the-maldridge** [comment] 2020-10-04 00:36
As this will not be accepted, I'm going to close this ticket and other tickets can be deduped against it.

**Closed by the-maldridge** 2020-10-04 00:36 UTC
Labels: request

**Comment by unihernandez22** [comment] 2020-10-04 22:23
And why doesn't you maintain it from binary release??

**Comment by Anachron** [comment] 2020-10-05 05:08
@unihernandez22 because it requires us to ship the bundled library versions which may break other packages that are already packaged.

**Comment by unihernandez22** [comment] 2020-10-16 20:12
> @unihernandez22 because it requires us to ship the bundled library versions which may break other packages that are already packaged.

What? I'm using a binary package and it works fine for me

**Comment by q66** [comment] 2020-10-16 20:36
we don't package prebuilt binaries of open source software

**Comment by Logarithmus** [comment] 2020-11-05 21:28
> we don't package prebuilt binaries of open source software

Why? It allows to avoid the burden of rebuilding everything over and over from scratch.
We can mark it as `x86_64` only package.

**Comment by Duncaen** [comment] 2020-11-05 21:43
binary packages block our repository if we can rebuild them if a dependency breaks abi.

And now, take a look at braves binary, imho its pretty likely that its going to break at some point: 

```
tmp$ ldd ./brave
        linux-vdso.so.1 (0x00007fff79762000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f198ad25000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f198ad04000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f198acf9000)
        libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007f198ac9a000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f198ab6e000)
        libnss3.so => /usr/lib/libnss3.so (0x00007f198aa39000)
        libnssutil3.so => /usr/lib/libnssutil3.so (0x00007f198aa04000)
        libsmime3.so => /usr/lib/libsmime3.so (0x00007f198a9da000)
        libnspr4.so => /usr/lib/libnspr4.so (0x00007f198a990000)
        libatk-1.0.so.0 => /usr/lib/libatk-1.0.so.0 (0x00007f198a968000)
        libatk-bridge-2.0.so.0 => /usr/lib/libatk-bridge-2.0.so.0 (0x00007f198a932000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f198a7f0000)
        libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x00007f198a7e9000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f198a7be000)
        libcups.so.2 => /usr/lib/libcups.so.2 (0x00007f198a721000)
        libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007f198a6ce000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f198a6a1000)
        libdrm.so.2 => /usr/lib/libdrm.so.2 (0x00007f198a68d000)
        libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x00007f198a4ca000)
        libxkbcommon.so.0 => /usr/lib/libxkbcommon.so.0 (0x00007f198a488000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f198a343000)
        libXcomposite.so.1 => /usr/lib/libXcomposite.so.1 (0x00007f198a33e000)
        libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x00007f198a339000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f198a324000)
        libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007f198a11c000)
        libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x00007f198a10f000)
        libgtk-3.so.0 => /usr/lib/libgtk-3.so.0 (0x00007f1989975000)
        libgdk-3.so.0 => /usr/lib/libgdk-3.so.0 (0x00007f1989875000)
        libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x00007f1989864000)
        libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x00007f1989814000)
        libcairo.so.2 => /usr/lib/libcairo.so.2 (0x00007f19896db000)
        libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0 (0x00007f19896b4000)
        libgbm.so.1 => /usr/lib/libgbm.so.1 (0x00007f19896a2000)
        libasound.so.2 => /usr/lib/libasound.so.2 (0x00007f19895a4000)
        libatspi.so.0 => /usr/lib/libatspi.so.0 (0x00007f198956d000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f1989553000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f198938e000)
        /lib64/ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x00007f1995f0c000)
        libffi.so.7 => /usr/lib/libffi.so.7 (0x00007f1989382000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f198930c000)
        libplc4.so => /usr/lib/libplc4.so (0x00007f1989305000)
        libplds4.so => /usr/lib/libplds4.so (0x00007f1989300000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f19892f9000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f19892f1000)
        libavahi-common.so.3 => /usr/lib/libavahi-common.so.3 (0x00007f19892e3000)
        libavahi-client.so.3 => /usr/lib/libavahi-client.so.3 (0x00007f19892cf000)
        libgnutls.so.30 => /usr/lib/libgnutls.so.30 (0x00007f1989103000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f1988eec000)
        libcrypt.so.1 => /usr/lib/libcrypt.so.1 (0x00007f1988eb0000)
        libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007f1988eaa000)
        libmount.so.1 => /usr/lib/libmount.so.1 (0x00007f1988e4b000)
        libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f1988e33000)
        libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f1988c29000)
        libXi.so.6 => /usr/lib/libXi.so.6 (0x00007f1988c15000)
        libcairo-gobject.so.2 => /usr/lib/libcairo-gobject.so.2 (0x00007f1988c09000)
        libepoxy.so.0 => /usr/lib/libepoxy.so.0 (0x00007f1988add000)
        libfribidi.so.0 => /usr/lib/libfribidi.so.0 (0x00007f1988abe000)
        libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f19889ec000)
        libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x00007f19889d3000)
        libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007f198898b000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f19888d9000)
        libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x00007f19886d6000)
        libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0x00007f19886c9000)
        libwayland-cursor.so.0 => /usr/lib/libwayland-cursor.so.0 (0x00007f19886c0000)
        libwayland-egl.so.1 => /usr/lib/libwayland-egl.so.1 (0x00007f19886bb000)
        libwayland-client.so.0 => /usr/lib/libwayland-client.so.0 (0x00007f19886a9000)
        libthai.so.0 => /usr/lib/libthai.so.0 (0x00007f198849f000)
        libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0x00007f19883f8000)
        libEGL.so.1 => /usr/lib/libEGL.so.1 (0x00007f19883e7000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f19883b2000)
        libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x00007f19883ab000)
        libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x00007f198839c000)
        libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f1988315000)
        libwayland-server.so.0 => /usr/lib/libwayland-server.so.0 (0x00007f1988300000)
        libp11-kit.so.0 => /usr/lib/libp11-kit.so.0 (0x00007f19881d0000)
        libidn2.so.0 => /usr/lib/libidn2.so.0 (0x00007f19881ad000)
        libunistring.so.2 => /usr/lib/libunistring.so.2 (0x00007f1987e2c000)
        libtasn1.so.6 => /usr/lib/libtasn1.so.6 (0x00007f1987e16000)
        libnettle.so.8 => /usr/lib/libnettle.so.8 (0x00007f1987dd7000)
        libhogweed.so.6 => /usr/lib/libhogweed.so.6 (0x00007f1987d8e000)
        libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f1987d11000)
        libblkid.so.1 => /usr/lib/libblkid.so.1 (0x00007f1987cbd000)
        libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f1987c93000)
        libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007f1987c8a000)
        libbz2.so.1 => /usr/lib/libbz2.so.1 (0x00007f1987c77000)
        libdatrie.so.1 => /usr/lib/libdatrie.so.1 (0x00007f1987a6f000)
        libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007f19879b6000)
        libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007f1987984000)
```

**Comment by unihernandez22** [comment] 2020-11-06 15:31
> binary packages block our repository if we can't rebuild them if a dependency breaks abi.

So, if they block your repository, you couldn't have any binary package. Not even privative software.

**Comment by Duncaen** [comment] 2020-11-06 15:35
> So, if they block your repository, you couldn't have any binary package. Not even privative software.

There are two things, first that most don't have even closely as many dependencies as brave and second, they are contained in a different repository, because of some limitations in the repository tooling, staging happens on a per repository basis.

And yes both are bad, proprietary software is going to break and binary packages are going to break.

**Comment by Animeshz** [comment] 2021-11-22 08:22
There's somebody maintaining a [brave-bin pkg](https://gitlab.com/ElPresidentePoole/brave-bin), it works perfectly fine. Had to clone that at srcpkgs and run usual pkg command.

**Comment by Animeshz** [comment] 2021-11-22 08:29
My review of brave in just one day:

The default UI style is nice, modern and small does not take huge space in tab n search-bar like firefox, full-screen on a window manager setup works perfectly nice and the tabs don't hide (it were in firefox and when getting mouse to top shows tabs temporarily and resizes the window with jerk), also hovering over the tabs give rise to x button which in firefox I had to first foreground that tab (happens after 11+ tabs opened).

Also the tor mode is quick, UI does not restart as the connection is made unlike the torbrowser-launcher where whatever was written in the search bar or tabs created just gets lost when tor connects to a route. Keybinds are also better, ctrl+shift+p for print, {ctrl,alt}+shift+n for private/tor, alt+e for showing the menu up/down for navigating or s to directly jump to settings, ctrl+f or / works for getting search bar sliding on to the screen, also the find on any page highlights all occurences of the search word unlike firefox defaults which again search bar comes with jerk, and only highlights one occurence at a time. I just couldn't go back to firefox now. I'm not sure about other chromium browsers but the bundled features as pointed by the @fn-ix also holds for making it my primary browser from today.
