### ISSUE TITLE
Firefox password fields and file URLs broken by multiprocess setting

### ISSUE THREAD

**Issue by svenper** [void-linux/void-packages#12885] opened 2019-07-07 14:18 UTC
### System

* xuname:  
  `Void 5.2.4_1 x86_64-musl GenuineIntel notuptodate hold rrnFFFFFFFFF`
* package:  
  firefox-68.0.1_1
  firefox-esr-60.8.0_1

### Expected behavior

1. Selecting password input fields do not crash the tab.
2. `file://` URLs do not crash.

### Actual behavior

When `browser.tabs.remote.autostart` is set to `true` (the default) :
1. Selecting password input fields crash the tab.
2. `file://` URLs crash.

### Steps to reproduce the behavior

```
rm -rf /tmp/firefox-void-debug
mkdir /tmp/firefox-void-debug
gdb --args /usr/bin/firefox --profile /tmp/firefox-void-debug --no-remote --new-instance --save-recordings --private-window 'https://bug1451466.bmoattachments.org/attachment.cgi?id=8965047' 2>&1 | tee /tmp/firefox.log
```

**Comment by svenper** [comment] 2019-07-18 02:15
Setting the multi-process `browser.tabs.remote.autostart` to false in `about:config` is a workaround.

The same issue affects `file:///` URLs, and can be worked around in the same way.

**Comment by jnbr** [comment] 2019-07-19 22:41
I can not reproduce the crash with password fields.
Can you provide more information regarding the file URLs? Some logs could be useful.

In case anyone else experiences this issue, feel free to leave a comment.

**Comment by svenper** [comment] 2019-07-19 23:38
@jnbr What arch are you on?

```
(firefox:29867): Gtk-WARNING **: 01:31:54.165: Theme parsing error: gtk.css:3:2: Invalid name of pseudo-class
1563579114583   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1563579114583   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1563579114583   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1563579114583   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
Sandbox: seccomp sandbox violation: pid 29952, tid 29952, syscall 16, args 2 21523 140724365074336 0 140324000936204 16.
(/usr/lib/firefox/firefox:29952): Gtk-WARNING **: 01:31:55.298: Theme parsing error: gtk.css:3:2: Invalid name of pseudo-class
Sandbox: seccomp sandbox violation: pid 29975, tid 29975, syscall 16, args 2 21523 140733141244480 0 140434539462924 16.
(/usr/lib/firefox/firefox:29975): Gtk-WARNING **: 01:31:55.511: Theme parsing error: gtk.css:3:2: Invalid name of pseudo-class
JavaScript error: chrome://browser/content/aboutPrivateBrowsing.js, line 11: ReferenceError: RPMIsWindowPrivate is not defined
Sandbox: seccomp sandbox violation: pid 30030, tid 30030, syscall 16, args 2 21523 140729510399344 0 139633561719052 16.
(/usr/lib/firefox/firefox:30030): Gtk-WARNING **: 01:31:56.019: Theme parsing error: gtk.css:3:2: Invalid name of pseudo-class
console.warn: nsLoginManager: "searchLogins: `formSubmitURL` or `httpRealm` is recommended"
[Parent 29867, Gecko_IOThread] WARNING: pipe error (65): Connection reset by peer: file /builddir/firefox-68.0/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
[Parent 29867, Gecko_IOThread] WARNING: pipe error (87): Connection reset by peer: file /builddir/firefox-68.0/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
[Parent 29867, Gecko_IOThread] WARNING: pipe error (80): Connection reset by peer: file /builddir/firefox-68.0/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
###!!! [Parent][MessageChannel] Error: (msgtype=0x1E0074,name=PBrowser::Msg_StopIMEStateManagement) Channel error: cannot send/recv
###!!! [Parent][MessageChannel] Error: (msgtype=0x1E008F,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
###!!! [Parent][MessageChannel] Error: (msgtype=0x1E008F,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
[Parent 29867, Gecko_IOThread] WARNING: pipe error (69): Connection reset by peer: file /builddir/firefox-68.0/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
```

The mentions of chromium are interesting. It was running when I started firefox.

**Comment by jnbr** [comment] 2019-07-20 10:12
Thanks for the logs.

> @jnbr What arch are you on?

I use x86_64 and x86_64-musl, but there are more variables. e.g. different gsetting backends.

**Comment by svenper** [comment] 2019-07-20 13:51
What else to look for? I don't have gnome installed so maybe something from that is missing. This is what I do **not** have installed:
[`sudo xbps-install -Sn gnome | sort -h | awk '{print $1}' | sed -E 's/-[0-9._]+$//g'`](https://gist.githubusercontent.com/svenper/57955132851b69d01858326c45bd0d9b/raw)

**Comment by svenper** [comment] 2019-07-20 17:28
[full firefox gdb output, from start to crash to finish](https://gist.githubusercontent.com/svenper/0b767fcd280381b6b4f29f05ea555032/raw)

**Comment by jnbr** [comment] 2019-07-21 23:36
Unfortunately, the gdb output contains no information about why the tab crashed.

Please provide more information about your system:
- Which graphic driver do you use?
- xorg or wayland?

It could be related to running out of shared memory. Please show the output of `df /dev/shm`

**Comment by svenper** [comment] 2019-07-22 00:16
* mesa-intel-dri-19.1.2_1
* xorg-server-1.20.5_1
* bspwm-0.9.7_1

```
Filesystem     1K-blocks   Used Available Use% Mounted on
tmpfs            4069536 394364   3675172  10% /dev/shm
```

**Comment by jnbr** [comment] 2019-07-23 09:16
Shared memory shouldn't be an issue according to these numbers.
The graphics stack is identical to mine, so this doesn't seem to be the case either.

I'm not sure on how to debug this. I will push the update for firefox-68.0.1 later today, I don't expect it to fix your issues but it might be worth a try.

**Comment by svenper** [comment] 2019-07-25 18:27
68.0.1 still crashes, log is practically same as before.

```
console.warn: nsLoginManager: "searchLogins: `formSubmitURL` or `httpRealm` is recommended"
[Parent 2016, Gecko_IOThread] WARNING: pipe error (72): Connection reset by peer: file /builddir/firefox-68.0.1/ipc/chromium/src/chrome/common/ipc_channel_posix
.cc, line 358
[Parent 2016, Gecko_IOThread] WARNING: pipe error (89): Connection reset by peer: file /builddir/firefox-68.0.1/ipc/chromium/src/chrome/common/ipc_channel_posix
.cc, line 358
[Parent 2016, Gecko_IOThread] WARNING: pipe error (82): Connection reset by peer: file /builddir/firefox-68.0.1/ipc/chromium/src/chrome/common/ipc_channel_posix
.cc, line 358

###!!! [Parent][MessageChannel] Error: (msgtype=0x1E0074,name=PBrowser::Msg_StopIMEStateManagement) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x1E008F,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x1E008F,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
```

**Comment by svenper** [comment] 2019-07-30 13:43
`firefox-esr-60.8.0_1` has the same problem, with a [sligthly more verbose log](https://gist.github.com/svenper/a771c0617cce793e6fde35e57eabcc35/raw).

**Comment by svenper** [comment] 2019-08-26 02:24
Other things that give the same crash are losing the connection or attempting to load domains that don't exist.

**Comment by PureTryOut** [comment] 2019-09-20 22:03
Just a note, this is a Musl issue. It's happening on [Alpine Linux](https://gitlab.alpinelinux.org/alpine/aports/issues/10451) and [Gentoo Musl](https://github.com/gentoo/musl/issues/44#issuecomment-377793438) too.

**Comment by svenper** [comment] 2019-09-28 02:28
[IMDB](https://www.imdb.com/) loads with some visuals for a while but eventually crashes, which seems to break the pattern of http{s,} pages working fine.

**Comment by anarchpenguin** [comment] 2019-10-21 02:09
> Just a note, this is a Musl issue. It's happening on [Alpine Linux](https://gitlab.alpinelinux.org/alpine/aports/issues/10451) and [Gentoo Musl](https://github.com/gentoo/musl/issues/44#issuecomment-377793438) too.

I am unable to duplicate this issue on arm64 or amd64 musl gentoo. Are you sure your using the upstream patches in void for musl support in mesa?

**Comment by PureTryOut** [comment] 2020-01-12 18:30
@anarchpenguin well, I'm not using Void, but Alpine Linux which uses Musl too. Like I said, it's happening on more distros, including Gentoo Musl. However, for some reason it can't be reproduced by everyone, which makes the whole thing way more annoying to debug.

**Comment by svenper** [comment] 2020-01-25 21:05
72.0.2_1 still crashes on local directories, but password fields work now!

**Comment by zeliklil** [comment] 2020-04-12 20:10
I am using Alpine, but uninstalling `dconf` fixed it for me.

Also, I think the password related crash is related to [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1616780).

**Comment by svenper** [comment] 2020-04-13 07:42
Uninstalling `dconf` worked for me as well! I haven't had the password crash for a while though

**Comment by jnbr** [comment] 2020-04-21 20:36
Nice that you found a solution. I'm closing this, feel free to reopen or open a new issue if the problems appear again.

**Closed by jnbr** 2020-04-21 20:36 UTC
Labels: bug

**Comment by svenper** [comment] 2020-04-21 20:56
It's nice but more of a hack than a solution. Lots of other stuff unfortunately require dconf...

**Comment by PureTryOut** [comment] 2020-04-22 07:17
For me it was fixed since version 72.0, and that is with `dconf` installed. This is on Alpine Linux. Are you guys absolutely sure dconf was causing the problem? It seems unlikely to me.

**Comment by svenper** [comment] 2020-04-22 08:58
@PureTryOut Are you talking about password fields, or local directories, or both? E.g. for me `file:///tmp/index.html` works but `file:///tmp/` crashes. https://github.com/void-linux/void-packages/issues/12885#issuecomment-578443007 :wink:

**Comment by PureTryOut** [comment] 2020-04-22 09:56
Just password fields. Local directories indeed still crashes, but luckily I don't need that feature anyway.

**Comment by svenper** [comment] 2020-04-22 10:49
Perhaps better to split that off into a separate issue now that it's clear they are caused by different things?
