### ISSUE TITLE
libgl: Shader Cache triggers segfault on musl

### ISSUE THREAD

**Issue by Vlad-Romanov** [void-linux/void-packages#921] opened 2018-07-15 17:16 UTC
### System
Void-Linux MUSL-LIBC
* xuname:  
  Void 4.17.6_1 x86_64-musl GenuineIntel uptodate rrnDDF

* package:  
  *affected package(s) including the version*
Falkon 3.0.1_3 & 3.0.0
MGBA-qt 0.6.3_3 & 0.7( 0.7 from master.zip source-code) & medusa-emu (source-code, prototype for mgba DS emulator)

Possible something with a QT5 package dependency? 

### Expected behavior
expect to open

### Actual behavior
segmentation fault

### Steps to reproduce the behavior
update system & try to open falkon & mgba-qt in terminal

https://forum.voidlinux.eu/t/falkon-web-browser-crash/6200
https://forum.voidlinux.eu/t/mgba-not-working-after-update/6202

**Comment by Gottox** [comment] 2018-07-16 12:34
`MESA_GLSL_CACHE_DISABLE=1` works around the issue.

**Comment by Vlad-Romanov** [comment] 2018-07-16 15:42
Oh, thank you Gottox. How do I apply this, where does this go?

**Comment by Gottox** [comment] 2018-07-16 16:15
I don't think that's the right way to do it.

Just run `MESA_GLSL_CACHE_DISABLE=1 retroarch` or `MESA_GLSL_CACHE_DISABLE=1 falkon` on the terminal.

**Comment by Vlad-Romanov** [comment] 2018-07-16 16:19
Still falkon crashes when I do as you are saying.

**Comment by Gottox** [comment] 2018-07-16 19:43
The files are truncated and don't contain the actual segfault.

**Comment by Vlad-Romanov** [comment] 2018-07-16 19:56
??? But you ask me to use this gist.github.com ? I do not understand... pastebin instead?

**Comment by Vlad-Romanov** [comment] 2018-07-16 20:00
agh, pastebin will not work for this size, I have just create a github repo with .log files, hope it work.
https://github.com/Vlad-Romanov/logs

**Comment by Gottox** [comment] 2018-07-17 07:14
For now I mark this as a duplicate of #933.

**Comment by Gottox** [comment] 2018-07-17 10:32
Handling the issue in #933 from now on

**Closed** 2018-07-17 10:32 UTC
Labels: duplicate
