### ISSUE TITLE
zopfli-1.0.3_1 doesn't include shared libraries

### ISSUE THREAD

**Issue by mrnoname1000** [void-linux/void-packages#23986] opened 2020-08-01 12:53 UTC
Zopfli builds shared and static libraries, but the build script doesn't install them. FYI, Zopfli's included makefile doesn't link the binaries with the shared libraries, but its cmake script does (if building the libraries, with -DZOPFLI_BUILD_SHARED=ON).
The below build script builds and installs everything, but I wasn't able to figure out the best way to package the necessary files separately in a -devel package.
```bash
# Template file for 'zopfli'
pkgname=zopfli
version=1.0.3
revision=2
wrksrc="${pkgname}-${pkgname}-${version}"
build_style=cmake
configure_args=-DZOPFLI_BUILD_SHARED=ON
short_desc="Very good, but slow, deflate or zlib compression"
maintainer="Leah Neukirchen <leah@vuxu.org>"
license="Apache-2.0"
homepage="https://github.com/google/zopfli"
distfiles="https://github.com/google/${pkgname}/archive/${pkgname}-${version}.tar.gz"
checksum=e955a7739f71af37ef3349c4fa141c648e8775bceb2195be07e86f8e638814bd

post_install() {
	vlicense COPYING LICENSE
}
```

**Comment by ericonr** [comment] 2020-08-02 04:23
@leahneukirchen is it fine to switch to cmake?

**Comment by ericonr** [comment] 2020-08-02 04:56
A package with a good example of a devel split is `libopenal`, if you'd like to try:

```
libopenal-devel_package() {
	depends="${sourcepkg}>=${version}_${revision}"
	short_desc+=" - development files"
	pkg_install() {
		vmove usr/include
		vmove usr/lib/pkgconfig
		vmove "usr/lib/*.so"
		vmove usr/lib/cmake
	}
}
```

**Comment by mrnoname1000** [comment] 2020-08-02 08:26
Thanks for pointing me in the right direction. Now I have a working template using cmake. Shall I put it in a PR and close this issue?

**Comment by ericonr** [comment] 2020-08-02 08:44
You can open a PR and add "Fixes #23986" to it, then when it's merged the issue is closed automatically.

Did you add a `vmove "usr/lib/*.a"` line to the devel package? The static lib should go in the devel package.

**Comment by mrnoname1000** [comment] 2020-08-02 09:00
Nice catch, I nearly forgot about the static libs.
Zopfli's cmake script doesn't install them anywhere, so does a `vcopy "${cmake_builddir}/*.a" usr/lib` in the devel package sound right?

**Comment by ericonr** [comment] 2020-08-02 09:15
> Edit: I guess cmake_builddir isn't set, is using a bare build fine here?

Should be.

> Zopfli's cmake script doesn't install them anywhere, so does a vcopy "${cmake_builddir}/*.a" usr/lib in the devel package sound right?

In that case, it's possible the static library is only for its own usage and shouldn't be used by other projects. I wouldn't do anything with it.

**Comment by mrnoname1000** [comment] 2020-08-02 09:26
I figured it out, -DZOPFLI_BUILD_SHARED is a toggle between building static and shared libs. That seems weird and would require two passes with cmake to get both static and shared libs. Should I not bother?

**Comment by ericonr** [comment] 2020-08-02 09:35
Not at all. Shipping only the dynamic libraries works well enough.

**Closed** 2021-01-21 17:52 UTC
