### ISSUE TITLE
Package Request: ttf-mscorefonts

### ISSUE THREAD

**Issue by apirusKde** [void-linux/void-packages#32937] opened 2021-09-11 22:08 UTC
You should include the package for cross compatibility in the office suites with the Windows folks. Put it in the nonfree repo, and you can include the whole font pack, but only Arial and Times New Roman font families are generaly needed i think

**Comment by paper42** [comment] 2021-09-11 22:55
duplicate of #9925, already packaged

**Closed by paper42** 2021-09-11 22:55 UTC
