### ISSUE TITLE
rakudo cannot find built-in NativeCall module

### ISSUE THREAD

**Issue by rypervenche** [void-linux/void-packages#19151] opened 2020-02-14 18:13 UTC
When trying to install zef (module manager) for rakudo, I found that NativeCall cannot be found in the default paths.

### System

* xuname:  
Void 5.3.9_1 x86_64 GenuineIntel/KVM notuptodate rFF

* package:  
rakudo-2020.01_1
nqp-2020.01_1
MoarVM-2020.01.1_1

### Expected behavior
raku -e 'use NativeCall'
(no output, returns prompt)

### Actual behavior
raku -e 'use NativeCall'
===SORRY!=== Error while compiling -e
Could not find NativeCall in:
    inst#/home/rypervenche/.raku
    inst#/usr/share/perl6/site
    inst#/usr/share/perl6/vendor
    inst#/usr/share/perl6/core
    ap#
    nqp#
    perl5#
at -e:1

### Steps to reproduce the behavior
raku -e 'use NativeCall'

**Comment by ericonr** [comment] 2021-02-18 05:08
I was unable to reproduce this error, can you confirm if it's still an issue for you?

**Comment by lpvm** [comment] 2021-02-18 10:21
I'm not using Raku anymore.
Thank you for your interest.

**Comment by ericonr** [comment] 2021-02-18 12:36
Ok, I will be closing the issue then. Thanks!

**Closed by ericonr** 2021-02-18 12:36 UTC
Labels: bug
