### ISSUE TITLE
failed to read path from javaldx

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#13365] opened 2019-07-27 12:47 UTC
Hi. i want to only install libreoffice-writer.(Because i don't need some other components). But it gives me errors, when i install the package: `libreoffice-writer`.
### System

* xuname:  
`  Void 4.19.57_1 x86_64 GenuineIntel notuptodate rFFFFFFF`
* package:  
  *affected package(s) including the version*

### Expected behavior
Run libreoffice-writer properly without any error.

### Actual behavior
Can't run libreoffice-writer.

### Steps to reproduce the behavior
Install  **libreoffice-writer** package only and then run it from terminal:
```
╰ libreoffice 
javaldx: Could not find a Java Runtime Environment!
Warning: failed to read path from javaldx
```

**Comment by Anachron** [comment] 2019-07-27 15:00
Did you install any Java Runtime Environment like the error suggested?

**Comment by LinArcX** [comment] 2019-07-27 15:09
@Anachron No. I don't know which package should i install?

**Comment by Anachron** [comment] 2019-07-27 16:48
You probably want to tell us which error you are getting if you want us to help you.

**Comment by LinArcX** [comment] 2019-07-27 17:48
No error. It close immediately.

**Comment by Anachron** [comment] 2019-07-27 18:16
Start it from the terminal? You‘re killing me.

**Comment by LinArcX** [comment] 2019-07-27 18:30
Yes.

**Comment by obunden** [comment] 2019-10-13 04:14
This is still a problem. We should install openjdk by default because libreoffice-writer won't start without it, and as I understand it libreoffice relies on java for many other functions as well. I manually installed openjdk and used 'xbps-alternatives -g java -s openjdk' and that seems to fix the issue. But then there is a new error "The application cannot be started. The user interface language cannot be determined".

**Comment by sarether** [comment] 2020-06-18 16:02
> "The application cannot be started. The user interface language cannot be determined".

`# xbps-install -S libreoffice-i18n-YOUR_LOCALE`

**Comment by LinArcX** [comment] 2020-09-20 07:29
It doesn't work anymore with openjdk-8.

**Comment by pullmoll** [comment] 2021-01-06 16:20
Cannot reproduce. I removed all of libreoffice and installed just libreoffice-writer.
Java (openjd8 and openjdk11) were both installed as dependencies of other packages.

Then tried a fresh VM with XFCE4 installed from Live ISO, installed just libreoffice-writer and no JVM.
lowriter starts and works. Installed openjdk (which is openjdk8) and lowriter still starts.

I'd like to close this because the issue, if it was there, for me is not reproducible.

**Closed** 2021-01-06 16:27 UTC
