### ISSUE TITLE
Package request: joplin (a markdown notes manager)

### ISSUE THREAD

**Issue by superiums** [void-linux/void-packages#39932] opened 2022-10-13 12:38 UTC
### Package name

joplin

### Package homepage

https://github.com/laurent22/joplin/

### Description

Joplin is a free, open source note taking and to-do application, which can handle a large number of notes organised into notebooks. The notes are searchable, can be copied, tagged and modified either from the applications directly or from your own text editor. The notes are in [Markdown format](https://github.com/laurent22/joplin/#markdown).

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by paper42** [comment] 2022-10-13 12:41
duplicate of #19585

**Closed by paper42** 2022-10-13 12:41 UTC
Labels: request, electron 🤮
