### ISSUE TITLE
open shot fails to run

### ISSUE THREAD

**Issue by chriscamacho** [void-linux/void-packages#11258] opened 2019-04-22 17:51 UTC
### System

* xuname:  
  Void 4.19.36_1 x86_64 GenuineIntel uptodate rrrmFFFFFFF
* package:  
  openshot installed today

### Expected behavior
it would run

### Actual behavior
AttributeError: module 'zmq.backend.cython' has no attribute 'curve_public'

### Steps to reproduce the behavior
install openshot and run it from the command prompt

**Comment by jnbr** [comment] 2019-04-25 09:36
Do you refer to `openshot-qt`? It is working here. Please provide a full log.

**Comment by chriscamacho** [comment] 2019-04-25 10:30
[chris@xps-void ~]$ openshot-qt 
Loaded modules from installed directory: /usr/lib/python3.6/site-packages/openshot_qt
Traceback (most recent call last):
  File "/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.4.4', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/openshot_qt/launch.py", line 55, in <module>
    from classes.app import OpenShotApp
  File "/usr/lib/python3.6/site-packages/openshot_qt/classes/app.py", line 41, in <module>
    from classes import info, settings, project_data, updates, language, ui_util, logger_libopenshot
  File "/usr/lib/python3.6/site-packages/openshot_qt/classes/logger_libopenshot.py", line 33, in <module>
    import zmq
  File "/usr/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/usr/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/usr/lib/python3.6/site-packages/zmq/backend/select.py", line 38, in select_backend
    ns[key] = getattr(mod, key)
AttributeError: module 'zmq.backend.cython' has no attribute 'curve_public'

**Comment by jnbr** [comment] 2019-04-25 10:53
please try if you get the same output:

```
$ python3
Python 3.6.8 (default, Feb  1 2019, 07:25:12)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zmq
>>> from zmq import backend
>>> backend.select_backend('zmq.backend.cython')['curve_public']
<cyfunction curve_public at 0x7f169e2f0830>
```

**Comment by chriscamacho** [comment] 2019-04-25 10:55
[chris@xps-void cLogicFun]$ python3
Python 3.6.8 (default, Feb  1 2019, 07:25:12) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zmq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/usr/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/usr/lib/python3.6/site-packages/zmq/backend/select.py", line 38, in select_backend
    ns[key] = getattr(mod, key)
AttributeError: module 'zmq.backend.cython' has no attribute 'curve_public'

**Comment by jnbr** [comment] 2019-04-25 11:02
Please put pastes into code blocks, makes it more readable (I edited your posts).

On topic: something is wrong with your `python3-pyzmq`. Try `xbps-pkgdb python3-pyzmq` and if errors are reported, reinstall with `xbps-install -f python3-pyzmq`

**Comment by chriscamacho** [comment] 2019-04-25 11:06
no errors reported, did force reinstall anyhow, without effect

**Comment by jnbr** [comment] 2019-04-25 11:08
please post output of `xbps-query python3-pyzmq`

**Comment by chriscamacho** [comment] 2019-04-25 11:10
`[chris@xps-void ~]$ xbps-query python3-pyzmq
architecture: x86_64
automatic-install: yes
build-date: 2019-03-24 18:27 UTC
filename-sha256: cc20ddb089840e5c3946763aff469f899de31637852dbe1fdc30dda4debb2d34
filename-size: 264KB
homepage: https://pyzmq.readthedocs.io/
install-date: 2019-04-25 12:05 BST
install-script: 842B
installed_size: 1265KB
license: LGPL-3.0-or-later, BSD-3-Clause
maintainer: Alessio Sergi <al3hex@gmail.com>
metafile-sha256: 8a5edad5dc5b3bc22dd15d14d17a514a80854e235ddc2ef0fb3f1e91ee98f8e4
pkgver: python3-pyzmq-17.1.3_1
remove-script: 840B
repository: https://alpha.de.repo.voidlinux.org/current
shlib-requires:
	libpython3.6m.so.1.0
	libpthread.so.0
	libc.so.6
	libzmq.so.5
short_desc: Python3 bindings for the ZeroMQ messaging library
source-revisions: python-pyzmq:5d9f031596
state: installed
`

**Comment by jnbr** [comment] 2019-04-25 11:20
This looks fine. Maybe repeat steps for `zeromq` package. Otherwise, I'm out of ideas for now.

**Comment by chriscamacho** [comment] 2019-04-25 11:27
xbps-pkgdb reports nothing for zeromq

**Comment by jnbr** [comment] 2019-04-25 11:42
Do you have an additional zmq installation in e.g. /usr/local ?
Maybe check with: `echo "import zmq" > test.py; strace -e openat python3 test.py 2>&1|grep libzmq`

**Comment by chriscamacho** [comment] 2019-04-25 11:46
```echo "import zmq" > test.py; strace -e openat python3 test.py 2>&1|grep libzmq
openat(AT_FDCWD, "/usr/lib/python3.6/site-packages/zmq/backend/cython/../../.libs/tls/haswell/x86_64/libzmq-0576c57a.so.5.0.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python3.6/site-packages/zmq/backend/cython/../../.libs/tls/haswell/libzmq-0576c57a.so.5.0.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python3.6/site-packages/zmq/backend/cython/../../.libs/tls/x86_64/libzmq-0576c57a.so.5.0.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python3.6/site-packages/zmq/backend/cython/../../.libs/tls/libzmq-0576c57a.so.5.0.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python3.6/site-packages/zmq/backend/cython/../../.libs/haswell/x86_64/libzmq-0576c57a.so.5.0.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python3.6/site-packages/zmq/backend/cython/../../.libs/haswell/libzmq-0576c57a.so.5.0.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python3.6/site-packages/zmq/backend/cython/../../.libs/x86_64/libzmq-0576c57a.so.5.0.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python3.6/site-packages/zmq/backend/cython/../../.libs/libzmq-0576c57a.so.5.0.2", O_RDONLY|O_CLOEXEC) = 3
```

**Comment by chriscamacho** [comment] 2019-04-25 11:48
...well... thanks for your good suggestions, but I'm more confused now than at the start, do we have something different with cython ?

**Comment by jnbr** [comment] 2019-04-25 11:49
This looks strange: `... /../../.libs ...`

for me it is:
```
% echo "import zmq" > test.py; strace -e openat python3 test.py 2>&1|grep libzmq
openat(AT_FDCWD, "/usr/lib/tls/x86_64/x86_64/libzmq.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/tls/x86_64/libzmq.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/tls/x86_64/libzmq.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/tls/libzmq.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64/x86_64/libzmq.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64/libzmq.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64/libzmq.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libzmq.so.5", O_RDONLY|O_CLOEXEC) = 3
```

**Comment by chriscamacho** [comment] 2019-04-25 11:53
how does your output differ ?
```
xbps-query -o '*libzmq*'
python3-pyzmq-17.1.3_1: /usr/lib/python3.6/site-packages/zmq/backend/cython/libzmq.pxd (regular file)
zeromq-4.3.1_1: /usr/lib/libzmq.so.5.2.1 (regular file)
zeromq-4.3.1_1: /usr/lib/libzmq.so.5 -> /usr/lib/libzmq.so.5.2.1 (link)
```

**Comment by jnbr** [comment] 2019-04-25 11:54
I don't have `/usr/lib/python3.6/site-packages/zmq/.libs` and it shouldn't exist on your box either.
If you installed all software you use via xbps, it is safe to remove it, otherwise you should remove it as well and make sure other package managers like pip install to /usr/local.

**Comment by chriscamacho** [comment] 2019-04-25 11:56
could be something installed with pip, when I was doing some AI stuff, let me investigate pip, your xbps-query output would be useful

**Comment by jnbr** [comment] 2019-04-25 12:02
You need to be more specific than "xbpq-query output".
Easiest way to fix would be to remove /usr/lib/python3.6/site-packages/zmq/.libs and reinstall python3-pyzmq.

**Comment by chriscamacho** [comment] 2019-04-25 12:06
please see above
> xbps-query -o '*libzmq*'

**Comment by jnbr** [comment] 2019-04-25 12:09
```
% xbps-query -o '*libzmq*'
python3-pyzmq-17.1.3_1: /usr/lib/python3.6/site-packages/zmq/backend/cython/libzmq.pxd (regular file)
zeromq-4.3.1_1: /usr/lib/libzmq.so.5.2.1 (regular file)
zeromq-4.3.1_1: /usr/lib/libzmq.so.5 -> /usr/lib/libzmq.so.5.2.1 (link)
```

Again: the problem is that you have file in `/usr/lib` that aren't managed by xbps i.e. `/usr/lib/python3.6/site-packages/zmq/.libs`

**Comment by chriscamacho** [comment] 2019-04-25 12:15
yes i get that but I'm trying not to hose something else by blindly deleting /usr/lib/python3.6/site-packages/zmq/.libs, its been installed by pip by the looks but pip is refusing to uninstall it claiming its a "distutils installed project" please bare with me

**Comment by chriscamacho** [comment] 2019-04-25 12:31
okay I think I've got passed that problem, but caused another in the process
```
[chris@xps-void ~]$ openshot-qt 
Loaded modules from installed directory: /usr/lib/python3.6/site-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.4)
      launch:INFO ------------------------------------------------
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-chris'
         app:INFO openshot-qt version: 2.4.4
         app:INFO libopenshot version: 0.2.3
         app:INFO platform: Linux-4.19.36_1-x86_64-with-glibc2.3.4
         app:INFO processor: 
         app:INFO machine: x86_64
         app:INFO python version: 3.6.8
         app:INFO qt5 version: 5.11.3
         app:INFO pyqt5 version: 5.11.3
    language:INFO Qt Detected Languages: ['en-GB']
    language:INFO LANG Environment Variable: en_GB.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to /usr/lib/python3.6/site-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted
[chris@xps-void ~]$ file /usr/lib/libgcc_s.so.1
/usr/lib/libgcc_s.so.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=9244bf7cf3dea93fa08b3f6d18f7ce81e075ef02, stripped
[chris@xps-void ~]$ xbps-query libgcc
architecture: x86_64
automatic-install: yes
build-date: 2019-03-02 00:19 UTC
build-options: ada ~gnatboot 
filename-sha256: a0e7bf8666885e47f7978871034dcf266479fdb90fb737814a6964fd9c37b558
filename-size: 40KB
homepage: http://gcc.gnu.org
install-date: 2019-04-25 13:28 BST
installed_size: 102KB
license: GFDL-1.2-or-later, GPL-3.0-or-later, LGPL-2.1-or-later
maintainer: Juan RP <xtraeme@voidlinux.org>
metafile-sha256: 1dac294901dc59abadf4b5b7861dd073e06905bfe97edab069e76c37df7d04c3
pkgver: libgcc-8.3.0_1
replaces:
	libgcj<7.2.0
	libcilkrts<8.2.0
repository: https://alpha.de.repo.voidlinux.org/current
shlib-provides:
	libgcc_s.so.1
short_desc: GNU Compiler Collection - GCC library
source-revisions: gcc:0ae8e5bcd3
state: installed

```

I don't think this is a issue with this package however so feel free to close this issue...

**Comment by chriscamacho** [comment] 2019-04-25 12:42
interesting any ideas ?
```
[chris@xps-void ~]$ LD_PRELOAD=/usr/lib/libgcc_s.so openshot-qt 
ERROR: ld.so: object '/usr/lib/libgcc_s.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
Loaded modules from installed directory: /usr/lib/python3.6/site-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.4)
      launch:INFO ------------------------------------------------
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-chris'
         app:INFO openshot-qt version: 2.4.4
         app:INFO libopenshot version: 0.2.3
ERROR: ld.so: object '/usr/lib/libgcc_s.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
         app:INFO platform: Linux-4.19.36_1-x86_64-with-glibc2.3.4
         app:INFO processor: 
         app:INFO machine: x86_64
         app:INFO python version: 3.6.8
         app:INFO qt5 version: 5.11.3
         app:INFO pyqt5 version: 5.11.3
    language:INFO Qt Detected Languages: ['en-GB']
    language:INFO LANG Environment Variable: en_GB.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to /usr/lib/python3.6/site-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted
```

**Comment by jnbr** [comment] 2019-04-25 12:53
> interesting any ideas ?

You could use strace to figure out why it doesn't find libgcc_s.so.1. Something in your system is very wrong.
I'm closing this issue because it is not a problem with voidlinux but with installing stuff manually into /usr.

**Closed by jnbr** 2019-04-25 12:53 UTC
Labels: bug
