### ISSUE TITLE
FTBFS: mdocml

### ISSUE THREAD

**Issue by bobertlo** [void-linux/void-packages#20321] opened 2020-03-23 16:36 UTC
I was trying to build a base set of packages from bootstrap when I found this. It also happens building from the official repos.

```
=> mdocml-1.14.5_4: running do_configure ...
file config.log: writing...
make: echo: No such file or directory
make: *** [/tmp/GmK3pNhX:2: all] Error 127
=> ERROR: mdocml-1.14.5_4: do_configure: '${configure_script} ${configure_args}' exited with 2
=> ERROR:   in do_configure() at common/build-style/configure.sh:8
```

Also:
https://travis-ci.org/github/bobertlo/void-packages/jobs/665947505#L4146

**Comment by leahneukirchen** [comment] 2020-03-23 17:05
duplicate of #18816

**Closed by leahneukirchen** 2020-03-23 17:05 UTC
