### ISSUE TITLE
elogind: keyboard not released under certain conditions

### ISSUE THREAD

**Issue by st3r4g** [void-linux/void-packages#27132] opened 2020-12-14 00:04 UTC
### System

* xuname: Void 5.9.13_1 x86_64 AuthenticAMD notuptodate rFFF
* package: sway-1.5.1_1

### Expected behavior
keyboard grab released, linux console receives keypresses

### Actual behavior
keyboard still grabbed, can only shutdown via power key

### Steps to reproduce the behavior
* use `elogind` as `libseat` backend
* have `exec sway` in `.bash_profile`
* exit sway via `$mod+Shift+e` (`swaymsg exit`)

This started happening after the transition to `libseat` I believe. Would be interesting to know if this happens with other `wlroots` compositor as well.

**Comment by ericonr** [comment] 2020-12-14 00:11
You can probably reacquire the keyboard with sysrq magic, `alt+sysrq+r`.

**Comment by st3r4g** [comment] 2020-12-14 00:24
Yeah it worked... didn't know that, thanks!

**Comment by st3r4g** [comment] 2020-12-14 09:47
Additional info:
* no bug if `wlroots` compiled with `libelogind` session backend
* no bug if I logout via `loginctl terminate-session $XDG_SESSION_ID`

I am not sure who is to blame here. `sway` doesn't appear to do anything session-related on exit, so `elogind` should handle everything. But that doesn't explain the different behavior between the two session backends.

**Comment by kennylevinsen** [comment] 2020-12-14 10:35
If you drop back to the kernel console but do not have working keyboard input, then it would seem that elogind is not resetting the kernel keyboard mode (with KDSKBMODE) back to K_UNICODE. It is supposed to do this when the session control is either explicitly or implicitly dropped.

What version of elogind was tested against? You could use `busctl monitor` to get a dbus trace and compare with libseat to bare wlroots logind backend.

**Comment by kennylevinsen** [comment] 2020-12-14 10:55
The issue is not reproducible under systemd-logind 245 on a Fedora install I had lying around.

**Comment by st3r4g** [comment] 2020-12-14 11:21
From the dbus trace, the difference seems to be that the `logind` backend calls `ReleaseControl` while the `libseat` backend does not.

**Comment by kennylevinsen** [comment] 2020-12-14 11:37
> From the dbus trace, the difference seems to be that the logind backend calls ReleaseControl while the libseat backend does not.

ReleaseControl is indeed not called on libseat shutdown, because disconnecting from the bus is supposed to have the same effect. In elogind, this is set up here: https://github.com/elogind/elogind/blob/80c3df891cbe3bcdd27ada05ee7ca938a2c051ca/src/login/logind-session.c#L1521, with on_bus_track closing the session.

While we could just add the ReleaseControl call to libseat, not having working disconnect cleanup in elogind will lead to other problems, with e.g. a compositor crash still leaving you with a broken console.

> How are you starting sway? It happens when starting with exec sway in .bash_profile, but now manually in the shell.

Ran `LIBSEAT_BACKEND=logind sway -c sway_config -d 2>swaylog` from an empty TTY. The config is a mostly empty debug config, the env var is to force the logind backend instead of seatd.

It is very peculiar if it doesn't happen when you run it manually. I have not tried to mess around with my shell init scripts.

**Comment by kennylevinsen** [comment] 2020-12-14 11:55
I tried putting the following in my .bash_profile, changing my shell to bash and then logging in on tty4:

```
if [[ "$(tty)" == "/dev/tty4" ]]
then
        LIBSEAT_BACKEND=logind exec sway -c ~/sway_config -d 2>~/sway_debug.log
fi
```

This did not reproduce the issue. Afer issuing `swaymsg exit`, I was dropped back to a working TTY login.

**Comment by st3r4g** [comment] 2020-12-14 12:03
I can also reproduce with manually running `exec sway`

**Comment by kennylevinsen** [comment] 2020-12-14 12:10
Still no reproduction on "plain" logind. When you use the exec approach, the following will happen in parallel:
1. The parent `login` process will shut down the PAM session, having pam_elogind.so/pam_systemd.so notify (e)logind.
2. The bus is going to detach, notifying (e)logind.

It may very well be that elogind (and possibly logind if it's just a race) ends up messing things up when these happen simultaneously, as they both trigger various state changes.

Newer versions would be good to test. I don't have an elogind system near me right now, otherwise I'd have tried to see if I could reproduce there.

**Comment by kennylevinsen** [comment] 2020-12-14 22:22
You can probably reproduce using libseat's [simpletest](https://git.sr.ht/~kennylevinsen/seatd/tree/master/examples/simpletest/main.c), by running it as `simpletest /dev/dri/card0` (first argument is the device to try to open).

I haven't had time to test elogind, but I had a look at the code, and the session handling is considerably different than logind's own due to not being able to rely on systemd scopes. That's *probably* where it drops the ball.

**Comment by st3r4g** [comment] 2020-12-14 23:34
> You can probably reproduce using libseat's [simpletest](https://git.sr.ht/~kennylevinsen/seatd/tree/master/examples/simpletest/main.c) instead of running sway, by running it as `simpletest /dev/dri/card0` (first argument is the device to try to open).

You mean `exec simpletest /dev/dri/card0`? I don't reproduce it with that (can type in tty normally). Here's the output:
```
00:00:00.000 [INFO] [libseat/libseat.c:70] libseat_open_seat: Backend 'seatd' failed to open seat, skipping
00:00:00.002 [ERROR] [libseat/backend/logind.c:605] set_type: Could not set session type: Rejected send message, 2 matched rules; type="method_call", sender=":1.32" (uid=1000 pid=1936 comm="/tmp/simpletest /dev/dri/card0 ") interface="org.freedesktop.login1.Session" member="SetType" error name="(unset)" requested_reply="0" destination="org.freedesktop.login1" (uid=0 pid=1209 comm="elogind-daemon ")
00:00:00.002 [INFO] [libseat/libseat.c:67] libseat_open_seat: Seat opened with backend 'logind'
libseat_open_seat(listener: 0x7ffe83dbbf30, userdata: 0x7ffe83dbbf14) = 0x55886d2282a0
waiting for activation...
active!
libseat_open_device(backend: 0x55886d2282a0, path: /dev/dri/card0, fd: 0x7ffe83dbbf18) = 5
00:00:00.003 [ERROR] [libseat/backend/logind.c:132] close_device: Could not stat fd 5
```
the first error is due to `elogind` being outdated (doesn't have SetType), but what is the second error?
> @st3r4g Can you try the `release_control` branch of seatd? It includes the ReleaseControl call, which should do the trick for clean shutdowns at least.

Yeah that works. But still, it's an elogind bug... I should try master and report to them if it still happens.

**Comment by kennylevinsen** [comment] 2020-12-15 13:31
> the first error is due to elogind being outdated (doesn't have SetType), but what is the second error?

A minor bug in simpletests (closing the device fd too early, which trips up the logind backend). It's fixed on the `release_control` branch, but the bug should be inconsequential for reproduction.

**Comment by st3r4g** [comment] 2020-12-16 10:40
I am running `elogind` commit `80c3df891cbe3bcdd27ada05ee7ca938a2c051ca` (current master, from systemd 246) and I'm not seeing the issue anymore. So I think it was a logind bug that got fixed. This issue can be closed when elogind releases `v246` and we update to that.

**Comment by ericonr** [comment] 2021-02-05 02:10
Closed in https://github.com/void-linux/void-packages/commit/ae06ba604c515dabf49ddc901ea668f3571969c0

**Closed by ericonr** 2021-02-05 02:10 UTC
