### ISSUE TITLE
hfsprogs-540.1.linux3_6: bash: /bin/fsck.hfs: No such file or directory

### ISSUE THREAD

**Issue by amak79** [void-linux/void-packages#26125] opened 2020-11-04 10:06 UTC
### System

* xuname:  
Void 5.8.18_1 x86_64 GenuineIntel uptodate rF
* package:  
hfsprogs-540.1.linux3_6

### Expected behavior
`fsck.hfs` and `mkfs.hfsplus` should run without error.
### Actual behavior
```
# fsck.hfs
bash: /bin/fsck.hfs: No such file or directory
# mkfs.hfsplus
bash: /bin/mkfs.hfsplus: No such file or directory
```
This occurs with and without parameters being passed.
### Steps to reproduce the behavior
```
# xbps-install hfsprogs
# fsck.hfs
# mkfs.hfsplus
```
I tried rebuilding the package with `xbps-src` but I get the same result. Interestingly the package passes checks (`xbps-src check hfsprogs`), and I'm able to run the binaries from the build and install phases, but not after it's been packaged.

**Comment by sgn** [comment] 2020-11-04 11:12
On 2020-11-04 02:06:44-0800, amak79 <notifications@github.com> wrote:
> 
> ### System
> 
> * xuname:  
> Void 5.8.18_1 x86_64 GenuineIntel uptodate rF
> * package:  
> hfsprogs-540.1.linux3_6
> 
> ### Expected behavior
> `fsck.hfs` and `mkfs.hfsplus` should run without error.
> ### Actual behavior
> ```
> # fsck.hfs
> bash: /bin/fsck.hfs: No such file or directory
> # mkfs.hfsplus
> bash: /bin/mkfs.hfsplus: No such file or directory
> ```
> This occurs with and without parameters being passed.
> ### Steps to reproduce the behavior
> ```
> # xbps-install hfsprogs
> # fsck.hfs
> # mkfs.hfsplus
> ```
> I tried rebuilding the package with `xbps-src` but I get the same result. Interestingly the package passes checks (`xbps-src check hfsprogs`), and I'm able to run the binaries from the build and install phases, but not after it's been packaged.

Do you have your "/bin" linked to "/usr/bin"?

Please try "ls -al /bin".

In my machine, "fsck.hfs" is installed under "/usr/bin" and "/bin"
should link to "usr/bin"

-- 
Danh

**Comment by amak79** [comment] 2020-11-04 11:24
`/bin` is linked to `usr/bin`:
```
# ls -al /bin
lrwxrwxrwx 1 root root 7 Aug 21 21:26 /bin -> usr/bin
```

**Comment by sgn** [comment] 2020-11-04 15:05
Could you please check:
```sh
ls -al /usr/bin/fsck.hfs
file /usr/bin/fsck.hfs
strace fsck.hfs
```

**Comment by amak79** [comment] 2020-11-04 15:16
```
# ls -al /usr/bin/fsck.hfs
-rwxr-xr-x 1 root root 372472 Jul  4 09:08 /usr/bin/fsck.hfs

# file /usr/bin/fsck.hfs
/usr/bin/fsck.hfs: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=edebdfb10391134366021c20a944522a461a959f, for GNU/Linux 3.2.0, stripped

# strace fsck.hfs
execve("/bin/fsck.hfs", ["fsck.hfs"], 0x7ffd11977140 /* 44 vars */) = -1 ENOENT (No such file or directory)
strace: exec: No such file or directory
+++ exited with 1 +++
```

**Comment by ericonr** [comment] 2020-11-04 15:27
Have you tried running `xbps-pkgdb hfsprogs` ? I couldn't reproduce this here :/

**Comment by amak79** [comment] 2020-11-04 15:33
Just ran `xbps-pkgdb hfsprogs` but it didn't help.

**Comment by amak79** [comment] 2020-11-04 15:38
Installed `hfsprogs` on an RPi 3B+ arvm7l and it works. For some reason it won't work on my x86_64 install.

**Comment by Duncaen** [comment] 2020-11-04 17:13
It works fine, check `xbps-pkgdb -a`.

**Comment by Chocimier** [comment] 2020-11-04 17:23
What's output of following commands?
```
df -hT
echo $PATH
PATH=/usr/bin fsck.hfs
```

**Comment by amak79** [comment] 2020-11-04 23:54
@Duncaen 
```
# xbps-pkgdb -a
ERROR: base-files: broken symlink /lib32 (target: /usr/lib32)
ERROR: base-files: broken symlink /lib64 (target: /usr/lib)
ERROR: base-files: broken symlink /usr/lib64 (target: /usr/lib)
```
That dosn't look good. This is a new install (20201103) using the chroot method from the docs, and a x86_64 rootfs I created with mkrootfs. I examined the tarball I used and it doesn't have the `/lib32`, `/lib64` and `/usr/lib64` symlinks. It only has `/lib -> use/lib`. After  creating the `/lib64` synlink, both `fsck.hfs` and `mkfs.hfsplus` work.

@Chocimier 
```
# df -hT
Filesystem              Type      Size  Used Avail Use% Mounted on
devtmpfs                devtmpfs  3.9G     0  3.9G   0% /dev
tmpfs                   tmpfs     3.9G     0  3.9G   0% /dev/shm
tmpfs                   tmpfs     3.9G  888K  3.9G   1% /run
/dev/sda5               ext4       52G  2.4G   49G   5% /
cgroup                  tmpfs     3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs                   tmpfs     3.9G   12K  3.9G   1% /tmp
tmpfs                   tmpfs     787M  4.0K  787M   1% /run/user/1000

# echo $PATH
/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin

# PATH=/usr/bin fsck.hfs
bash: /usr/bin/fsck.hfs: No such file or directory
```

**Comment by ahesford** [comment] 2020-11-05 14:13
You should probably make sure all of those links exist and that `xbps-pkgdb -a` doesn't complain about the `base-files` package.

Closing because this issue appears to be resolved.

**Closed by ahesford** 2020-11-05 14:13 UTC

**Comment by amak79** [comment] 2020-11-05 14:46
Yes it's solved, bit is it normal for a rootfs tarball created by `mkrootfs` to be missing those symlinks? I've never had to create those links manually before.

**Comment by ericonr** [comment] 2020-11-05 14:51
> Yes it's solved, but is it normal for a rootfs tarball created by mkrootfs to be missing those symlinks? I've never had to create those links manually before.

Shouldn't be, I have two ROOTFS installations... Do you still have the tarball? Are the links indeed missing from it? (you can check with `tar tf <file>`.

**Comment by amak79** [comment] 2020-11-05 14:59
I still have the tarball. The `/lib32`, `/lib64` and `/usr/lib64` symlinks are definitely missing.

**Comment by ericonr** [comment] 2020-11-05 15:04
Well, if you can reproduce it is definitely worth reporting in void-mklive.

**Comment by amak79** [comment] 2020-11-05 15:07
Alright will do. Thanks to everyone who helped with this issue.

**Comment by Duncaen** [comment] 2020-11-05 15:09
https://github.com/void-linux/void-mklive/blob/2c7d8c02447a7ef0d81a9c292ee04c82c139679e/mkrootfs.sh.in#L184-L188 this was probably there from before those links were part of the base-files packages and were created with the base-files INSTALL script.
