### ISSUE TITLE
wine-devel doesn't install

### ISSUE THREAD

**Issue by Francesco149** [void-linux/void-packages#11729] opened 2019-05-14 15:53 UTC
for some reason wine-devel-32bit appears to depend on the non-existing non-32bit counterpart? not too familiar with how xbps handles -32bit but it's just impossible to install wine-devel-32bit

### System

* xuname:  Void 5.1.0_1 x86_64 GenuineIntel notuptodate hold rrrrmmnFFFFFFFFFFFFFF
* package:  wine-devel-32bit-4.8_1

### Expected behavior
installs correctly

### Actual behavior
```
$ sudo xbps-install wine-devel-32bit
MISSING: wine-devel-4.8_1
Transaction aborted due to unresolved dependencies.
```

### Steps to reproduce the behavior
```
sudo xbps-install wine-devel-32bit
```

**Comment by xtraeme** [comment] 2019-05-14 15:58
This is because the `wine-devel` subpkg does not set `lib32mode=full`.

**Comment by xtraeme** [comment] 2019-05-14 16:04
Hmm I was wrong, this is not the issue.

The issue is that it should set `lib32depends`.

**Comment by Hoshpak** [comment] 2019-05-15 07:13
duplicate of https://github.com/void-linux/void-packages/issues/8234

**Closed by Hoshpak** 2019-05-15 07:13 UTC
