### ISSUE TITLE
webkit2gtk: no target when introspection enabled

### ISSUE THREAD

**Issue by RossComputerGuy** [void-linux/void-packages#26287] opened 2020-11-11 05:24 UTC
### System

* xuname: `Void 5.8.17_1 x86_64 AuthenticAMD uptodate rrrrmmnFFFFF`
* package: `webkit2gtk-2.30.2_1`

### Expected behavior
WebKit2GTK with introspection support should compile

### Actual behavior
```
[ 98%] Building CXX object Source/WebKit/CMakeFiles/WebKit.dir/__/__/DerivedSources/WebKit/unified-sources/UnifiedSource-54928a2b-35.cpp.o
[ 98%] Linking CXX shared library ../../lib/libwebkit2gtk-4.0.so
[ 98%] Built target WebKit
Scanning dependencies of target WebKit2WebExtension-4-gir
make[2]: *** No rule to make target 'JavaScriptCore-4.0.gir', needed by 'WebKit2-4.0.gir'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1712: Source/WebKit/CMakeFiles/WebKit2WebExtension-4-gir.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
=> ERROR: webkit2gtk-2.30.2_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
=> ERROR:   in do_build() at common/build-style/cmake.sh:88
```

### Steps to reproduce the behavior
`./xbps-src pkg webkit2gtk`

**Comment by RossComputerGuy** [comment] 2020-11-11 08:24
Tried on upstream and not my fork, both are affected. This is not an isolated case to ExpidusOS.

**Comment by sgn** [comment] 2020-11-11 14:30
How did you compile `webkit2gtk`? Our packages are built with `gir` on.

**Comment by ericonr** [comment] 2020-11-11 15:11
> ./xbps-src pkg webkit2gtk

this is known to work, we literally have packages built with it.

**Comment by RossComputerGuy** [comment] 2020-11-11 16:14
I've done nothing to webkit2gtk besides removing qt5-tools. Also, `etc/conf` is default.

**Comment by sgn** [comment] 2020-11-11 17:10
It looks like we really have problems with `webkit2gtk`, I failed to compile it, too. I don't have time to look further, though.

**Comment by ericonr** [comment] 2020-11-11 18:27
```
=> Registering new packages to /host/binpkgs
index: added `webkit2gtk-2.30.2_1' (x86_64-musl).
index: added `webkit2gtk-devel-2.30.2_1' (x86_64-musl).
```

**Comment by RossComputerGuy** [comment] 2020-11-11 18:40
@ericonr Try the glibc target

**Comment by ericonr** [comment] 2020-11-11 19:28
```
=> Registering new packages to /host/binpkgs
index: added `webkit2gtk-2.30.2_1' (x86_64).
index: added `webkit2gtk-devel-2.30.2_1' (x86_64).
```

**Comment by sgn** [comment] 2020-11-11 23:12
On 2020-11-11 10:27:58-0800, Érico Nogueira Rolim <notifications@github.com> wrote:
> ```
> => Registering new packages to /host/binpkgs
> index: added `webkit2gtk-2.30.2_1' (x86_64-musl).
> index: added `webkit2gtk-devel-2.30.2_1' (x86_64-musl).
> ```

I guess my machine was OOM then, time to go shopping.

**Comment by ericonr** [comment] 2020-11-11 23:15
@RossComputerGuy can you reproduce this? Have you checked `dmesg` for OOM kills?

Both pullmoll and the-maldridge have built the package successfully (one of them at `-j120`), so I'm not sure it's an actual bug; if it is, it is very rare.

**Comment by RossComputerGuy** [comment] 2020-11-11 23:26
I'm using the standard `-j` value, 4, and my CPU is a Ryzen 5 3600 @ 4.50GHz. Also, I grepped for `OOM` (with `-i`) and `kill` (with `-i`) from `dmesg` and got no results.

**Comment by pullmoll** [comment] 2020-11-11 23:29
Your kernel is 5.8.17, mine is 5.8.18... Who knows?
Some people claim they have seen horses barfing in front of the pharmacy ;-P

**Comment by RossComputerGuy** [comment] 2020-11-11 23:30
Yeah but I don't have any kernel updates

**Comment by pullmoll** [comment] 2020-11-11 23:36
Huh? 5.8.18 has been there for 10 days. https://github.com/void-linux/void-packages/commit/5511289b42705fc5d6989be733cffb011ba5e0d3
What do you use to update? `xtools` or `xbps-install`? Don't forget the `-S` in the latter case.

**Comment by RossComputerGuy** [comment] 2020-11-11 23:38
```
~ > sudo xbps-install -Su                                                                                                                                                                                                                                                  ~
Password:
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/nonfree/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/nonfree/x86_64-repodata' ...
~ >
```

**Comment by sgn** [comment] 2020-11-11 23:40
On 2020-11-11 15:36:57-0800, Jürgen Buchmüller <notifications@github.com> wrote:
> Huh? 5.8.18 has been there for 10 days. https://github.com/void-linux/void-packages/commit/5511289b42705fc5d6989be733cffb011ba5e0d3
> What do you use to update? `xtools` or `xbps-install`? Don't forget the `-S` in the latter case.

He builds his own ;)

**Comment by pullmoll** [comment] 2020-11-11 23:41
Uh, ok, I missed that point :)

**Comment by sgn** [comment] 2020-11-11 23:42
On 2020-11-11 15:38:46-0800, Tristan Ross <notifications@github.com> wrote:
> ```
> ~ > sudo xbps-install -Su                                                                                                                                                                                                                                                  ~
> Password:
> [*] Updating repository `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
> [*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/nonfree/x86_64-repodata' ...
> [*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/x86_64-repodata' ...
> [*] Updating repository `https://alpha.de.repo.voidlinux.org/current/nonfree/x86_64-repodata' ...
> ~ >
> ```

Don't prepend your local repository to xbps.conf
Otherwise, it'll stop at it if it founds a package.

**Comment by RossComputerGuy** [comment] 2020-11-11 23:48
I haven't, my XBPS config on my dev machine is stock.

**Comment by gspe** [comment] 2021-01-06 09:38
I have a ryzen 7 3700x and I had the same exactly error but after add `XBPS_MAKEJOBS=16` to `etc/conf` it compile just fine.
So maybe the error happens just because it take very very long to compile with one core.
I think we can close this error.

**Comment by sgn** [comment] 2021-01-06 11:52
I think there's some race in cmake(1)

**Comment by RossComputerGuy** [comment] 2021-01-06 22:13
Doesn't `XBPS_MAKEJOBS` do the same as `-j`?

**Comment by Johnnynator** [comment] 2021-01-06 22:27
`-j` takes precedence over `XBPS_MAKEJOBS` but yeah otherwise it does the same.

**Comment by RossComputerGuy** [comment] 2021-01-06 22:28
Strange how I've tried it with and without that option and yet I get the same result

**Comment by ericonr** [comment] 2021-01-20 20:56
Reproducing is complicated, so closing for now. For the most part, can be solved by restarting the build.

**Closed by ericonr** 2021-01-20 20:56 UTC

**Comment by RossComputerGuy** [comment] 2021-02-03 18:17
I tried to build again but I'm still having the issue. If I set the makejobs, my mobo can't supply enough power to my CPU and it'll cause the entire system to shutdown.

**Comment by ericonr** [comment] 2021-02-03 18:32
@RossComputerGuy please check out #28304 then, it might be better.
