### ISSUE TITLE
Nvidia340 fails to compile on a new 5.7.9 lts kernel

### ISSUE THREAD

**Issue by AngryPhantom** [void-linux/void-packages#23602] opened 2020-07-16 18:17 UTC
### System

* xuname:  
Void 5.4.51_1 x86_64 AuthenticAMD uptodate rrFFFFF

* package:  
nvidia340-340.108_3

### Actual behavior
Just ran 'xbps-install -Su' today and it pulled the new 5.7.9 kernel. Is it LTS already?
Anyway, nvidia340 module fails to compile. Here is the [make.log](https://pastebin.com/raw/i5sck6fK).

(there are other modules like 8188eu wifi that also failed to compile, but that's another story and should be fixed by their authors I guess)

### Steps to reproduce the behavior
Update the system -> get the new 5.7.9 kernel
DKMS will fail for the nvidia340 driver.

**Comment by ericonr** [comment] 2020-07-16 18:30
https://aur.archlinux.org/packages/nvidia-340xx-dkms/

**Comment by ericonr** [comment] 2020-07-16 18:31
I guess we need to add some patches from https://forums.developer.nvidia.com/t/patches-for-340-108-and-5-6-rc-need-help-with-driver-init/111760/12

**Comment by AngryPhantom** [comment] 2020-07-16 19:08
> https://aur.archlinux.org/packages/nvidia-340xx-dkms/

Sorry what should I do with this? I'm a bit new to the Void world.

Probably I'd just better stay with the 5.4 kernel for some time (well, until all the dust settles down).

**Comment by ericonr** [comment] 2020-07-16 19:18
Sorry, that was the wrong link. The important part are those patches.

**Comment by AngryPhantom** [comment] 2020-07-16 19:22
@ericonr Ok, will wait for the fixes to come into the repo then :)

**Comment by AngryPhantom** [comment] 2020-07-16 19:28
@ericonr Sorry, a little offtopic: I decided to put linux and linux-headers via ignorepkg in /etc/xbps.d/ and if I do:

`sudo xbps-remove -Oo`

I get this:

`dracut                remove    050_2`
`kpartx                remove    0.8.4_1`
`linux-firmware-intel  remove    20200519_1`
`linux-firmware-nvidia remove    20200519_1`
`cpio                  remove    2.13_1`

I know that it's natural and logical because of new dependencies. Should I just not use this command in the nearest future? What is the best way to clean the cache and avoid this?

**Comment by q66** [comment] 2020-07-16 19:29
we should just drop this series, it was deprecated by nvidia last year, it won't be getting any more updates, it also doesn't support glvnd which is a can of worms of its own

additionally, *every* card supported by this driver and not supported by a newer series is fully supported by nouveau

**Comment by ericonr** [comment] 2020-07-16 19:41
@AngryPhantom 

> Sorry, a little offtopic: I decided to put linux and linux-headers via ignorepkg in /etc/xbps.d/ and if I do:

You probably want to `xdowngrade` to the previous `linux` and `linux-headers` metapackages, and then `xbps-pkgdb -m hold` them, if you don't want the update.

**Comment by AngryPhantom** [comment] 2020-07-16 19:51
@ericonr Oh, thanks!

**Comment by AngryPhantom** [comment] 2020-07-16 19:52
@q66

`nouveau`

Yeah, but there will be no OpenGL gaming and 3D :( Or it would be just awful.

**Comment by q66** [comment] 2020-07-16 19:55
? opengl is fully supported by nouveau for all cards up to 700 series

**Comment by AngryPhantom** [comment] 2020-07-16 19:57
@q66 Is the performance OK? Have you tried playing something? Just asking because I've never tested nouveau.

**Comment by q66** [comment] 2020-07-16 20:00
should be fine all the way up to kepler (i know cards like GTX 680 perform at least up to 80% of what they do on proprietary drivers, and that was a few years ago), fermi and kepler don't have automatic reclocking (400-700 series) so you have to reclock manually, but 400 series and newer is supported by `nvidia390` anyway

**Comment by AngryPhantom** [comment] 2020-07-16 20:06
@q66 Great news then. Thanks! Will try nouveau.

**Comment by q66** [comment] 2020-07-16 20:08
what card is this anyway?

**Comment by AngryPhantom** [comment] 2020-07-16 20:13
@q66 GeForce 9500 GT

**Comment by AngryPhantom** [comment] 2020-07-16 20:14
I also have GeForce 7600 GT :)

**Comment by AngryPhantom** [comment] 2020-07-16 20:28
@q66 Well, tried to uninstall all proprietary drivers. This is what I get:

```
sudo xbps-remove nvidia340 nvidia340-dkms nvidia340-libs 
nvidia340-libs-340.108_3 in transaction breaks installed pkg `SDL-1.2.15_12'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `SDL2-2.0.12_1'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `cairo-1.16.0_2'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `fltk-1.3.5_2'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `glxinfo-8.4.0_1'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `gst-plugins-base1-1.16.2_1'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `libglapi-20.1.2_1'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `libglvnd-devel-1.3.1_1'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `libvlc-3.0.11_3'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `mesa-20.1.2_1'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `qt5-declarative-5.15.0_2'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `qt5-gui-5.15.0_2'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `qt5-multimedia-5.15.0_2'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `qt5-wayland-5.15.0_2'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `qtav-1.12.0_3'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `virtualbox-ose-6.1.10_2'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `webkit2gtk-2.28.2_2'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `xfce4-screensaver-0.1.10_1'
nvidia340-libs-340.108_3 in transaction breaks installed pkg `xorg-server-1.20.8_4'
Transaction aborted due to unresolved dependencies.
```

**Comment by AngryPhantom** [comment] 2020-07-16 20:31
Sorry, deleted a comment. I've successfully uninstalled nvidia340. Gonna install kernel 5.7 and reboot...

**Comment by AngryPhantom** [comment] 2020-07-17 20:13
@q66 Well, it works to some extent, even played some games. The only thing I get artifacts in windows in XFCE sometimes, the title bars are garbled or with glitches. I don't know if there any configs/settings for nouveau.

**Comment by q66** [comment] 2020-07-18 00:33
I suggest you disable xfce's builtin compositor and use something like picom

**Comment by AngryPhantom** [comment] 2020-07-18 02:07
I never use compositing. It's the first thing I disable after installing
any distro.

**Comment by fosslinux** [comment] 2020-07-22 06:15
I have a laptop with a very old NVIDIA card. The artifacts in windows seem to be common, and I am not sure exactly why.

**Comment by AngryPhantom** [comment] 2020-07-23 20:19
@fosslinux Are you using nouveau or a proprietary driver?

**Comment by q66** [comment] 2020-07-23 20:36
i have a powermac g5 with geforce 6600 in it and that has no desktop artifacts (though in games it's quite broken, but i suspect that's specific to big endian architecture and it's probably fine on x86), though geforce 9000 series is a few years newer

**Comment by fosslinux** [comment] 2020-07-24 04:13
Nouveau

**Comment by fosslinux** [comment] 2020-11-02 03:35
Good news for this driver, majaro is actively developing patches for 5.7+, I'll PR them shortly, confirmed they work with my GTS 250 It is very much on its last legs though, this is probably it's last burst of life.

**Comment by seannaswell** [comment] 2020-11-02 18:44
> Good news for this driver, majaro is actively developing patches for 5.7+, I'll PR them shortly, confirmed they work with my GTS 250 It is very much on its last legs though, this is probably it's last burst of life.

Would be tremendously helpful, have an old MacBook that only works with nvidia340, not nouveau. At this point the FreeBSD Nvidia driver still works, but would be a great Void test machine...

**Comment by AngryPhantom** [comment] 2020-11-03 07:56
@seannaswell Could you please share how do you install the FreeBSD driver?

**Comment by fosslinux** [comment] 2020-11-03 10:22
Please test :))

**Comment by AngryPhantom** [comment] 2020-11-07 16:29
@fosslinux Sorry, what should I test? Is it in the repos?

**Comment by fosslinux** [comment] 2020-11-07 23:39
No, it isn't, but if you are able to, clone the void-packages repository on my branch, `./xbps-src binary-bootstrap && ./xbps-src pkg nvidia340` and then `xbps-install -R hostdir/binpkgs nvidia340 -u` to update. You ahve to build it yourself until it is merged and more testers would be appreciated

**Comment by AngryPhantom** [comment] 2020-11-10 12:20
That's nice that it can be still supported. Actually I switched to a more stable 5.4.x kernel branch. I've also found out that **Debian** still supports **nvidia340** driver and will support it in the future releases with **5.8.x**, **5.9.x** and higher kernels. Probably you can take the patches from them? Here is the [driver](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=nvidia-legacy-340xx-kernel-source) (you need to unpack it and take the _nvidia-legacy-340xx-kernel.tar.xz_ archive, there will be a '**patches**' directory inside). I think you should take the latest version (for Debian Sid).
I guess I'm not the one with old hardware here, so it would be really nice if you continue supporting legacy drivers.
Well, if it's not a problem for you, of course...

Thank you!

**Comment by fosslinux** [comment] 2020-11-10 22:09
It has been merged into master, try an update, 5.{7,8,9}.x should work now

**Comment by AngryPhantom** [comment] 2020-11-11 08:49
@fosslinux Thank you very much! I really appreciate your efforts. Keep up the good work!

**Comment by Chocimier** [comment] 2021-01-04 22:52
Is it fixed?

**Closed by Chocimier** 2021-01-04 22:52 UTC

**Comment by fosslinux** [comment] 2021-01-05 00:43
Yes

**Comment by Yay-mod** [comment] 2021-01-17 17:16
i didn,t find that package (nvidia340) in the repo

where to download it ?

**Comment by fosslinux** [comment] 2021-01-17 21:21
`nvidia340` has now been dropeed from the repos.

**Comment by Yay-mod** [comment] 2021-01-18 01:00
this is the repo your taking about (if i,m not wrong)
https://github.com/void-linux/void-packages

and so you tell me that there,s in the srcpkgs folder a package called nvidia340
i downloaded all of this and didn,t find anything
runned the command above and got this

[alakondray@alakondray-s-laptop]$ cd void-packages
[alakondray@alakondray-s-laptop void-packages]$ ./xbps-src binary-bootstrap && xbps-src pkg nvidia340
fatal: cannot change to '/home/alakondray/void-packages/srcpkgs/nvidia340': No such file or directory
stat: cannot statx '/home/alakondray/void-packages/srcpkgs/nvidia340/template No such file or directory
ERROR: xbps-src: unexistent file: /home/alakondray/void-packages/srcpkgs/ nvidia340/template
[akakondray@alakondray-s-laptop void-packages]$

and i know that means there,s no nvidia340 package
i saw that there,s nvidia and nvidia390 and same version of DKMS but no nvidia340
(i,m not a basher i like linux and i,m stuck with this problem)(plz help)

**Comment by Yay-mod** [comment] 2021-01-18 01:03
i now realised that you said (Droped)

do you have a copy so i can put it in my copy of the repo

**Comment by Yay-mod** [comment] 2021-01-18 01:09
pls don,t tell me i,m too late

**Comment by ericonr** [comment] 2021-01-18 02:19
@Yay-mod just revert the commit where it was removed: `git revert 9c820a9e247bfafaac9e1221eb8e7974250bb331`.

But be warned that we no longer guarantee that everything will work correctly with the driver.

**Comment by AngryPhantom** [comment] 2021-01-18 08:14
@Yay-mod 
What are you [talking about](http://0x0.st/-iTN.png)? Just enable non-free repo. And yes, as @ericonr has already said, this will make your system unsupported. Switch to nouveau.

**Comment by fosslinux** [comment] 2021-01-18 10:59
@AngryPhantom nvidia340 had been dropped from the repo... there is no `nvidia340` package any longer.

**Comment by AngryPhantom** [comment] 2021-01-18 11:45
@fosslinux I saw a post on Void Linux subreddit where **aedinius** said that it _would be dropped soon_. I'm aware of the issue. Anyway, you saw my screenshot, the package is there at the moment. Also [here](https://voidlinux.org/packages/).

**Comment by Yay-mod** [comment] 2021-01-18 18:30
1) what  is the non-free repo (it is just like the repo forks or what / how to install it
2)the packages is also removed frome the binary 
https://github.com/void-linux/void-packages/tree/master/srcpkgs/nvidia340
https://github.com/void-linux/void-packages/tree/master/srcpkgs/nvidia340-dkms
3) i found on aur a version of it with updating / bleeeding edge patches (i was a arch user before until they couldn,t help me at this)
https://aur.archlinux.org/pkgbase/nvidia-340xx/
4) nouveau driver is giving me performance and compibiltiy issues it is hard to paly games and upscalling windows always slows (i want the driver to revive this laptop and can,t change gpu. other than this i,ll haveto move back to windows which is so bloated and so heavy on the laptop) + crashes. so i have 0 choice

**Comment by Yay-mod** [comment] 2021-01-18 18:33
about 2
can,t the repo use the patches and readd the driver ?
just like you did with the debian driver
for some reason it didn,t want to install on arch (or at least endeavour what i was using)
but you can take the patches and hopefully i,ll work?

**Comment by Yay-mod** [comment] 2021-01-18 19:28
and about the nvidia340 repo
it will be supported untill what

wait have the repo already readded it ?

**Comment by AngryPhantom** [comment] 2021-01-18 22:11
Install the void-repo-nonfree package. And start reading the manuals:
https://docs.voidlinux.org/xbps/repositories/index.html

**Comment by fosslinux** [comment] 2021-01-19 00:01
It has been dropped from the source packages tree:

https://github.com/void-linux/void-packages/tree/master/srcpkgs/nvidia340 <-- not found

It is now a **no-op** package, see https://github.com/void-linux/void-packages/blob/master/srcpkgs/removed-packages/template#L87, installing it will not do anything.

**Comment by Yay-mod** [comment] 2021-01-19 03:17
well i installed it and it no longer works
xorg didn,t start/work
i had to uninstall it
but there,s something happened while installing
the terminal (cli) told me it couldn,t install the nvidia340-dkms module
it told me to do to /etc/x11/xorg to see the errorlog
i didn,t find anything other than the build/source of nvidia340
i,m not sure but i think it have to do with it

**Comment by fosslinux** [comment] 2021-01-19 04:38
@Yay-mod `nvidia340` is no longer supported/packaged by Void. Either find some other way of installing it or just use nouveau. We won't be providing help here.

**Comment by Chocimier** [comment] 2021-01-19 18:43
It's not that package is no-op. If one grabs it and forcefully install, it will have all what it had. But it will be then removed on (some of) next system update.

**Comment by Yay-mod** [comment] 2021-01-20 02:45
then where can i find help
the nouveau driver isn,t that good compared to the nvidia one (as i said above) i understand why (and tbh they,re making a good job from scratch) but that isn,t fair.
i don,t want to go back to windows it,s bad in every way and i can,t unless that modified version of it fixes the download link (https://nexusliteos.blogspot.com/2020/11/xtreme-liteos-10-v3-ltsb-1607-build-x64.html)
i just wanted to make this laptop usable and playable as it is one of linux uses and advantages
+ i want to use linux and learning in progress it (because it is so customizable and good for tinkering) as my spare computer that i can do whatever i want on (i wouldn,t be a good idea to install it on a pc full of work and files for a beginner).
there have to be a solution (right ?) i don,t want to give up on that laptop yet

**Comment by Yay-mod** [comment] 2021-01-20 02:52
and if it no longer supported on void should i install debian and install the driver or install arch and hope for the best (i choosed void because it,s so minimal)

or just get the package with patches from anywhere and build it and also hope for the best

**Comment by fosslinux** [comment] 2021-01-20 06:31
If you have a very compelling need for nvidia340, you have two options:

- manually build and install nvidia340 on every kernel update (I would suggest using LTS versions to avoid jumping major versions too often) using patches from other places, using other distros still supporting nvidia340 (probably not for too much longer)
- use another distro supporting nvidia340

FWIW, my experience with nvidia340 was less than stellar.

**Comment by AngryPhantom** [comment] 2021-01-20 11:00
@Yay-mod 
>should i install debian

Debian still supports nvidia340 and will support it in the next release. And even after the next one, as you can see [here](https://packages.debian.org/ru/buster/nvidia-legacy-340xx-driver). So, yes, if you really need nvidia driver you can switch to it. I'm running Debian on my other machines and servers, it's awesome.

>i choosed void because it,s so minimal

Just install Debian from the netinst.iso and use `--no-install-recommends` in the APT's settings. It will be as minimal as you want it to.

**Comment by Yay-mod** [comment] 2021-01-22 02:45
(sorry for replying late i was kinda busy)(this comment is long and might be unnecessary at all !)
well i appreciate all the help i,m getting from this github issue and the patience from the helpers including the maintainers of the void source repo (fosslinux , Angeryphantom and ericonr).
i fear that the main problem (with me) is that i,m not able to install that driver correctly due to the problem of me being a linux beginner , so i always miss a important part of the installation becaues there wasn,t a guide video to follow. i later while i was researching i found out that i have to configure #nvidia-xconfig in order to make that working (as for no reason the nvidia driver dosen,t use the xorg config file).
while installing other nvidia supported distro is still a good idea but if i don,t know what i,m doing i,ll ending up nowhere otherwise in any distro (or in a timehole like this).
 i,m not bashing about linux i understand how unsupportive nvidia is to the linux community and how harsh it is to (completely) setup that proprietary driver and dealing with it specially in that case where nvidia no longer want linux user to use it anymore (i mean literally resupporting that driver) and that,s why it,s rare to find a guide fr someting so harsh like this .

**Comment by Yay-mod** [comment] 2021-01-22 02:46
i just want to know how to setup that driver and dealing with the #nvidia-config and if there,s something else have to be done.
i know i have pulled this problem this far with you but i don,t want to end up in another timehole and that,s will solve some problems with me experiencing linux.
