### ISSUE TITLE
fuse-exfat-1.3.0_1 won't mount drives with udevil

### ISSUE THREAD

**Issue by Gigahawk** [void-linux/void-packages#2928] opened 2018-09-20 07:29 UTC
### System

* xuname:  
  Void 4.18.7_2 GenuineIntel notuptodate rrrmFFFFFF
* package:  
  fuse-exfat

### Expected behavior
udevil will mount an exfat drive in /media/<label>, creating that folder if it is not already there.

### Actual behavior
If the folder doesn't exist, fuse-exfat will error out with
```
FUSE exfat 1.3.0
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
```

### Steps to reproduce the behavior
```
udevil mount /dev/<drive>
```

I'm guessing there's some issue with the way the new version of fuse-exfat handles (or doesn't handle) `nonempty`, since that option is set by default with udevil. Passing it in manually doesn't seem to do anything either.

Regular mounting by creating a folder and using `sudo mount` still works fine, and provided the folder you create remains, udevil will also work, but it won't delete the folder after you unmount.

**Comment by biopsin** [comment] 2018-09-28 12:29
Related to [issue #81](https://github.com/IgnorantGuru/udevil/issues/81#issue-350013548)

**Comment by Gigahawk** [comment] 2018-11-17 11:04
Tried this, I can't seem to get it to build on install or using `dkms autoinstall`.

**Comment by Johnnynator** [comment] 2018-11-17 11:15
@Gigahawk Is your system up to date? The compile time error of exfat-dkms with linux4.18 should be fixed in the current exfat-dkms package. Maybe you also have to clean the build dir manually.

**Comment by Johnnynator** [comment] 2018-11-17 12:35
Mh... I don't have a Clue what could cause `unable to initialize decompress status for section .debug_info`. I also can't reproduce it locally..

**Comment by pullmoll** [comment] 2018-11-17 20:05
I see this error after updating a laptop. It now fails to build e.g. dkms module rtl8012au-4.3.14 giving me exactly this error. I booted into 4.18.18 to have the previously built module for WIFI.

xuname: *Void 4.18.18_1 x86_64 AuthenticAMD uptodate F*

Which dependency of the dkms build process did recently change?

**Comment by pullmoll** [comment] 2018-11-17 20:34
This seems to be the bug in binutils-2.29.1:
https://lists.gnu.org/archive/html/bug-binutils/2015-07/msg00038.html

**Comment by pullmoll** [comment] 2018-11-17 21:23
Uh, so it was elfutils-0.175 ...

**Comment by Gigahawk** [comment] 2018-11-19 08:17
@biopsin seems to install correctly now (at least on the kernel I'm running) but the same error still persists.

I'm not entirely sure that the kernel module is being loaded properly though, `lsmod | grep exfat` shows nothing and manually with `modprobe exfat` doesn't fix the problem either.

**Comment by biopsin** [comment] 2018-11-19 22:12
Think you should head over to https://github.com/dorimanx/exfat-nofuse , I see folks are having issues with newer kernels, as I'm still on 4.9

Also see pull request https://github.com/dorimanx/exfat-nofuse/pull/137

**Closed** 2018-12-27 09:32 UTC
