### ISSUE TITLE
Package request:  mysql-workbench

### ISSUE THREAD

**Issue by machadofguilherme** [void-linux/void-packages#40714] opened 2022-11-24 01:37 UTC
### Package name

mysql-workbench

### Package homepage

https://www.mysql.com/products/workbench/

### Description

Unified visual tool for database architects

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by paper42** [comment] 2022-11-24 10:10
Duplicate of https://github.com/void-linux/void-packages/issues/24488

**Closed by paper42** 2022-11-24 10:10 UTC
Labels: request
