### ISSUE TITLE
wl-clipboard 2.2.0: wl_display_dispatch: Protocol error

### ISSUE THREAD

**Issue by K14D** [void-linux/void-packages#45604] opened 2023-08-14 13:22 UTC
### Is this a new report?

Yes

### System Info

Void 6.3.13_1 x86_64 GenuineIntel uptodate hold rDF

### Package(s) Affected

wl-clipboard-2.2.0_1

### Expected behaviour

"wl-copy Hello" shoud copy the word "Hello" to the clipboard.

### Actual behaviour

"wl-copy Hello" crashes with:

> wl_registry@2: error 0: invalid version for global gtk_shell1 (39): have 3, wanted 4
> wl_display_dispatch: Protocol error

Only version 2.2.0 is affected. The previous version 2.1.0 works perfectly fine.

I'm running wayfire as wm. Maybe there is a dependency conflict?

### Steps to reproduce

see above

**Comment by Bnyro** [comment] 2023-08-14 15:59
Hmm, everything works fine for me on River. I'll try to get Wayfire running and see whether I can reproduce the issue.

**Comment by mhmdanas** [comment] 2023-08-14 16:04
Cannot reproduce on Sway too.

**Comment by Bnyro** [comment] 2023-08-14 16:55
Can't get wayfire running unfortunately, but seems like a wayfire issue so far.

**Comment by Bnyro** [comment] 2023-08-14 17:41
If you find the wayfire commit that fixed it, we could patch wayfire.

**Comment by mhmdanas** [comment] 2023-08-15 16:26
It seems like this will be fixed from the wl-clipboard side: https://github.com/bugaevc/wl-clipboard/issues/194

**Comment by Bnyro** [comment] 2023-08-21 08:19
I added the upstream patches in #45699, but they also seem to be willing to create a new bugfix release soon.

**Closed** 2023-09-05 19:43 UTC
Labels: bug, needs-testing
