### ISSUE TITLE
Package Update: Crystal Programming Language 0.25.1

### ISSUE THREAD

**Issue by The-BigDaddy** [void-linux/void-packages#1196] opened 2018-07-25 22:10 UTC
**xuname:** Void 4.17.9_1 x86_64 GenuineIntel uptodate rrrmF
 
**Package:** crystal, current version 0.24.1, most recent stable version 0.25.1

Not a huge deal. From just opening **Issues** I can see there's quite a few other more important packages to fix and/or update. However there have been some decent [changes](https://github.com/crystal-lang/crystal/blob/master/CHANGELOG.md#0251-2018-06-27) to the Crystal programming langauge since the Void packages [current version](https://github.com/crystal-lang/crystal/blob/master/CHANGELOG.md#0241-2017-12-23). 

Again, no rush. :)

**Comment by TeddyDD** [comment] 2018-07-27 11:41
I update package basically for myself, not sure if it is correct. I can't make Travis to build it, so I doubt it will be merged.

Works for me on x86_64 glibc box, so If you need new Crystal you can build it from mine PR.

Btw: duplicate of #306

**Comment by pullmoll** [comment] 2018-08-03 09:31
https://github.com/void-linux/void-packages/commit/f31a1e19527ae493a4dca8660a1cff572a25ef01

**Closed by pullmoll** 2018-08-03 09:31 UTC
