### ISSUE TITLE
Package request: AppImage Launcher

### ISSUE THREAD

**Issue by magnusshtebner** [void-linux/void-packages#38497] opened 2022-08-06 05:27 UTC
### Package name

AppImageLauncher

### Package homepage

https://github.com/TheAssassin/AppImageLauncher

### Description

This program allows you to integrate appimage packages into your system. For example, such applications as librewolf, etcher, rpcs3 and others.

### Does the requested package meet the quality requirements?

System

### Is the requested package released?

Yes

**Comment by paper42** [comment] 2022-08-06 08:12
duplicate of #26702

**Closed** 2022-08-06 08:12 UTC
Labels: request
