### ISSUE TITLE
FTBFS: stack

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#22368] opened 2020-05-27 20:23 UTC
As every now and then, if not most of the time, `stack` fails to build from source again.

I tried updating to `2.3.1` and also to update `_stackage="lts-15.5"` yet the error when trying to compile Stack.Types.Resolver persists:

```
[ 29 of 109] Compiling Stack.Types.Resolver ( src/Stack/Types/Resolver.hs, /builddir/stack-2.3.1/dist-newstyle/build/x86_64-linux/ghc-8.8.3/stack-2.3.1/build/Stack/Types/Resolver.o )

src/Stack/Types/Resolver.hs:71:17: error:
    Ambiguous occurrence ‘SnapName’
    It could refer to
       either ‘Stack.Prelude.SnapName’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.SnapName’,
              defined at src/Stack/Types/Resolver.hs:67:1
   |
71 | instance NFData SnapName
   |                 ^^^^^^^^

src/Stack/Types/Resolver.hs:72:18: error:
    Ambiguous occurrence ‘SnapName’
    It could refer to
       either ‘Stack.Prelude.SnapName’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.SnapName’,
              defined at src/Stack/Types/Resolver.hs:67:1
   |
72 | instance Display SnapName where
   |                  ^^^^^^^^

src/Stack/Types/Resolver.hs:82:11: error:
    Ambiguous occurrence ‘ParseSnapNameException’
    It could refer to
       either ‘Stack.Prelude.ParseSnapNameException’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.ParseSnapNameException’,
              defined at src/Stack/Types/Resolver.hs:76:7
   |
82 |     show (ParseSnapNameException t) = "Invalid snapshot name: " ++ T.unpack t
   |           ^^^^^^^^^^^^^^^^^^^^^^

src/Stack/Types/Resolver.hs:97:19: error:
    Ambiguous occurrence ‘SnapName’
    It could refer to
       either ‘Stack.Prelude.SnapName’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.SnapName’,
              defined at src/Stack/Types/Resolver.hs:67:1
   |
97 | renderSnapName :: SnapName -> Text
   |                   ^^^^^^^^

src/Stack/Types/Resolver.hs:98:17: error:
    Ambiguous occurrence ‘LTS’
    It could refer to
       either ‘Stack.Prelude.LTS’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.LTS’,
              defined at src/Stack/Types/Resolver.hs:68:7
   |
98 | renderSnapName (LTS x y) = T.pack $ concat ["lts-", show x, ".", show y]
   |                 ^^^

src/Stack/Types/Resolver.hs:99:17: error:
    Ambiguous occurrence ‘Nightly’
    It could refer to
       either ‘Stack.Prelude.Nightly’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.Nightly’,
              defined at src/Stack/Types/Resolver.hs:69:7
   |
99 | renderSnapName (Nightly d) = T.pack $ "nightly-" ++ show d
   |                 ^^^^^^^

src/Stack/Types/Resolver.hs:102:44: error:
    Ambiguous occurrence ‘SnapName’
    It could refer to
       either ‘Stack.Prelude.SnapName’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.SnapName’,
              defined at src/Stack/Types/Resolver.hs:67:1
    |
102 | parseSnapName :: MonadThrow m => Text -> m SnapName
    |                                            ^^^^^^^^

src/Stack/Types/Resolver.hs:105:29: error:
    Ambiguous occurrence ‘ParseSnapNameException’
    It could refer to
       either ‘Stack.Prelude.ParseSnapNameException’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.ParseSnapNameException’,
              defined at src/Stack/Types/Resolver.hs:76:7
    |
105 |         Nothing -> throwM $ ParseSnapNameException t0
    |                             ^^^^^^^^^^^^^^^^^^^^^^

src/Stack/Types/Resolver.hs:113:18: error:
    Ambiguous occurrence ‘LTS’
    It could refer to
       either ‘Stack.Prelude.LTS’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.LTS’,
              defined at src/Stack/Types/Resolver.hs:68:7
    |
113 |         return $ LTS x y
    |                  ^^^

src/Stack/Types/Resolver.hs:116:9: error:
    Ambiguous occurrence ‘Nightly’
    It could refer to
       either ‘Stack.Prelude.Nightly’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.Nightly’,
              defined at src/Stack/Types/Resolver.hs:69:7
    |
116 |         Nightly <$> readMaybe (T.unpack t1)
    |         ^^^^^^^

src/Stack/Types/Resolver.hs:132:18: error:
    Ambiguous occurrence ‘parseSnapName’
    It could refer to
       either ‘Stack.Prelude.parseSnapName’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.parseSnapName’,
              defined at src/Stack/Types/Resolver.hs:103:1
    |
132 |             case parseSnapName t of
    |                  ^^^^^^^^^^^^^

src/Stack/Types/Resolver.hs:134:24: error:
    Ambiguous occurrence ‘LTS’
    It could refer to
       either ‘Stack.Prelude.LTS’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.LTS’,
              defined at src/Stack/Types/Resolver.hs:68:7
    |
134 |                 Right (LTS _ _) -> fail "Unexpected LTS value"
    |                        ^^^

src/Stack/Types/Resolver.hs:135:24: error:
    Ambiguous occurrence ‘Nightly’
    It could refer to
       either ‘Stack.Prelude.Nightly’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.Nightly’,
              defined at src/Stack/Types/Resolver.hs:69:7
    |
135 |                 Right (Nightly d) -> return d
    |                        ^^^^^^^

src/Stack/Types/Resolver.hs:140:18: error:
    Ambiguous occurrence ‘parseSnapName’
    It could refer to
       either ‘Stack.Prelude.parseSnapName’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.parseSnapName’,
              defined at src/Stack/Types/Resolver.hs:103:1
    |
140 |             case parseSnapName t of
    |                  ^^^^^^^^^^^^^

src/Stack/Types/Resolver.hs:142:24: error:
    Ambiguous occurrence ‘LTS’
    It could refer to
       either ‘Stack.Prelude.LTS’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.LTS’,
              defined at src/Stack/Types/Resolver.hs:68:7
    |
142 |                 Right (LTS x y) -> return $ IntMap.singleton x y
    |                        ^^^

src/Stack/Types/Resolver.hs:143:24: error:
    Ambiguous occurrence ‘Nightly’
    It could refer to
       either ‘Stack.Prelude.Nightly’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.Nightly’,
              defined at src/Stack/Types/Resolver.hs:69:7
    |
143 |                 Right (Nightly _) -> fail "Unexpected nightly value"
    |                        ^^^^^^^
=> ERROR: stack-2.3.1_1: do_build: 'HOME=$PWD cabal new-build ${makejobs} --flag disable-git-info' exited with 1
=> ERROR:   in do_build() at srcpkgs/stack/template:24
```

I think @leahneukirchen needs to take a look at this.

**Comment by st3r4g** [comment] 2020-05-27 21:02
Duplicate of #22027

**Closed** 2020-05-28 00:01 UTC
