### ISSUE TITLE
zathura-pdf-mupdf: undefined symbol: opj_setup_decoder

### ISSUE THREAD

**Issue by sug0** [void-linux/void-packages#35634] opened 2022-02-15 13:11 UTC
### System

* xuname:  
  * Void 5.15.22_1 x86_64 AuthenticAMD uptodate hold rrrmFFFFFFFFF
* package:  
  * zathura-0.4.9_1
  * zathura-pdf-mupdf-0.3.8_1

### Expected behavior

Read a PDF file.

### Actual behavior

```
error: Could not load plugin '/usr/lib64/zathura/libpdf-mupdf.so' (/usr/lib64/zathura/libpdf-mupdf.so: undefined symbol: opj_setup_decoder).
error: Could not determine file type.
```

### Steps to reproduce the behavior

Open any PDF file with zathura and the mupdf plugin.

**Comment by sug0** [comment] 2022-02-15 13:11
cc @lemmi

**Comment by dkwo** [comment] 2022-02-15 13:39
Similar error on `Void 5.16.7_1 x86_64-musl GenuineIntel uptodate rrnFFFFFFFF`
```
error: Could not load plugin '/usr/lib64/zathura/libpdf-mupdf.so' (Error relocating /usr/lib64/zathura/libpdf-mupdf.so: jbig2_page_out: symbol not found).
error: Could not determine file type.
```

**Comment by lemmi** [comment] 2022-02-15 14:02
Had to revert to the previous version. The only changes in `0.3.8` were to dependencies and both patches caused problems.

**Comment by dexgs** [comment] 2022-09-08 02:13
I think this might be the offending change: https://git.pwmt.org/pwmt/zathura-pdf-mupdf/-/blob/0.3.8/meson.build#L32-36

If you modify the ``meson.build`` such that the ``else`` block always executes, I think you might be able to get it to build.

**Comment by lemmi** [comment] 2022-09-08 10:47
> I think this might be the offending change: https://git.pwmt.org/pwmt/zathura-pdf-mupdf/-/blob/0.3.8/meson.build#L32-36
> 
> If you modify the `meson.build` such that the `else` block always executes, I think you might be able to get it to build.

Yeah, this is basically what we achieved by not updating to `0.3.8`. That obviously won't work forever.

So, [comments for 49a85ef](https://git.pwmt.org/pwmt/zathura-pdf-mupdf/-/commit/49a85efb915bfed933d251f6074b807d0e1ef385#note_1588) sound like this won't be fixed by upstream at this point, but they are open to contributions. Additionally they suggested 
1. to rework the detection, such that they can still run their tests against `mupdf` built from source
2. ship a `pkgconfig` file with `mupdf-devel`
   Maybe @Gottox can judge whether this is possible or desired

I don't know how to do either of those, but I think we can just revert [49a85ef](https://git.pwmt.org/pwmt/zathura-pdf-mupdf/-/commit/49a85efb915bfed933d251f6074b807d0e1ef385) for the time being and keep the thing on life support this way for a little longer.

**Comment by dkwo** [comment] 2023-11-02 15:41
is this now fixed? cannot reproduce

**Closed** 2023-11-02 19:44 UTC
Labels: bug
