### ISSUE TITLE
Package request: Citra

### ISSUE THREAD

**Issue by Nathan-MV** [void-linux/void-packages#38301] opened 2022-07-27 05:32 UTC
### Package name

citra-canary

### Package homepage

https://github.com/citra-emu/citra-canary

### Description

Nintendo 3DS emulator

### Does the requested package meet the quality requirements?

Compiled

### Is the requested package released?

Yes

**Comment by paper42** [comment] 2022-07-27 07:56
duplicate of #12690

**Closed by paper42** 2022-07-27 07:56 UTC
Labels: request
