### ISSUE TITLE
[Package Request] Zrythm

### ISSUE THREAD

**Issue by rempas** [void-linux/void-packages#26221] opened 2020-11-08 13:06 UTC
Zrythm is a highly automated and intuitive digital audio workstation

[site](https://www.zrythm.org/en/index.html)

[git](https://git.zrythm.org/cgit/zrythm)
[github](https://github.com/zrythm/zrythm)

[Licence](https://www.gnu.org/licenses/agpl-3.0.en.html): AGPL  v3

**Comment by biopsin** [comment] 2020-11-08 14:29
duplicate of https://github.com/void-linux/void-packages/issues/21236

**Comment by Godnyx** [comment] 2020-11-09 14:26
> duplicate of #21236

In this case should I close the issue?

**Comment by classabbyamp** [comment] 2022-06-25 07:08
dup of #21236

**Closed** 2022-06-25 07:08 UTC
Labels: request
