### ISSUE TITLE
`xreader` cross-build seems to hang on `armv7l-musl` and `armv6l-musl`

### ISSUE THREAD

**Issue by mhmdanas** [void-linux/void-packages#47790] opened 2023-12-16 16:36 UTC
### Is this a new report?

Yes

### System Info

Void 6.5.13_1 x86_64 GenuineIntel uptodate rFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

### Package(s) Affected

`xreader-3.8.2_1`

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

None I could find.

### Expected behaviour

The package builds successfully.

### Actual behaviour

The build gets stuck:

<details>
<summary>Build log</summary>

```
=> xbps-src: updating repositories for host (x86_64-musl)...
[*] Updating repository `https://repo-default.voidlinux.org/current/musl/bootstrap/x86_64-musl-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/musl/x86_64-musl-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/musl/nonfree/x86_64-musl-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/musl/debug/x86_64-musl-repodata' ...
=> xbps-src: updating repositories for target (armv6l-musl)...
[*] Updating repository `https://repo-default.voidlinux.org/current/musl/bootstrap/armv6l-musl-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/musl/armv6l-musl-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/musl/nonfree/armv6l-musl-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/musl/debug/armv6l-musl-repodata' ...
=> xbps-src: updating software in / masterdir...
=> xbps-src: cleaning up / masterdir...
=> xreader-3.8.2_1: removing autodeps, please wait...
=> xreader-3.8.2_1: removing autocrossdeps, please wait...
=> xreader-3.8.2_1: the following build options are set:
   gir: Enable support for gobject introspection data (ON)
=> xreader-3.8.2_1: building with [meson] [gir] [meson] for armv6l-musl...
   [host] mate-common-1.26.0_1: found (https://repo-default.voidlinux.org/current/musl)
   [host] mathjax2-2.7.9_1: found (https://repo-default.voidlinux.org/current/musl)
   [host] meson-1.3.0_1: found (https://repo-default.voidlinux.org/current/musl)
   [host] gobject-introspection-1.76.1_3: found (https://repo-default.voidlinux.org/current/musl)
   [host] qemu-user-static-8.1.3_1: found (https://repo-default.voidlinux.org/current/musl)
   [host] prelink-cross-20180128_2: found (https://repo-default.voidlinux.org/current/musl)
   [target] djvulibre-devel-3.5.28_2: found (https://repo-default.voidlinux.org/current/musl)
   [target] libSM-devel-1.2.4_1: found (https://repo-default.voidlinux.org/current/musl)
   [target] libgnomekbd-devel-3.28.1_1: found (https://repo-default.voidlinux.org/current/musl)
   [target] libgxps-devel-0.3.2_2: found (https://repo-default.voidlinux.org/current/musl)
   [target] libsecret-devel-0.21.1_1: found (https://repo-default.voidlinux.org/current/musl)
   [target] libspectre-devel-0.2.12_1: found (https://repo-default.voidlinux.org/current/musl)
   [target] libxkbfile-devel-1.1.2_1: found (https://repo-default.voidlinux.org/current/musl)
   [target] poppler-glib-devel-23.12.0_1: found (/host/binpkgs)
   [target] libwebkit2gtk41-devel-2.40.0_4: found (https://repo-default.voidlinux.org/current/musl)
   [target] xapps-devel-2.6.1_2: found (https://repo-default.voidlinux.org/current/musl)
   [target] gdk-pixbuf-devel-2.42.10_2: found (https://repo-default.voidlinux.org/current/musl)
   [target] gobject-introspection-1.76.1_3: found (https://repo-default.voidlinux.org/current/musl)
   [runtime] desktop-file-utils-0.26_1: found (https://repo-default.voidlinux.org/current/musl)
   [runtime] hicolor-icon-theme-0.17_3: found (https://repo-default.voidlinux.org/current/musl)
   [runtime] mathjax2-2.7.9_1: found (https://repo-default.voidlinux.org/current/musl)
   [runtime] libxreader-3.8.2_1: found (https://repo-default.voidlinux.org/current/musl)
   [runtime] libxreader-3.8.2_1: found (https://repo-default.voidlinux.org/current/musl)
=> xreader-3.8.2_1: installing host dependencies: mate-common-1.26.0_1 mathjax2-2.7.9_1 meson-1.3.0_1 gobject-introspection-1.76.1_3 qemu-user-static-8.1.3_1 prelink-cross-20180128_2 ...
=> xreader-3.8.2_1: installing target dependencies: djvulibre-devel-3.5.28_2 libSM-devel-1.2.4_1 libgnomekbd-devel-3.28.1_1 libgxps-devel-0.3.2_2 libsecret-devel-0.21.1_1 libspectre-devel-0.2.12_1 libxkbfile-devel-1.1.2_1 poppler-glib-devel-23.12.0_1 libwebkit2gtk41-devel-2.40.0_4 xapps-devel-2.6.1_2 gdk-pixbuf-devel-2.42.10_2 gobject-introspection-1.76.1_3 ...
=> xreader-3.8.2_1: running do-fetch hook: 00-distfiles ...
=> xreader-3.8.2_1: running do-extract hook: 00-distfiles ...
=> xreader-3.8.2_1: extracting distfile(s), please wait...
=> xreader-3.8.2_1: running do-patch hook: 00-patches ...
=> xreader-3.8.2_1: patching: 06b18a884c8cf3257ea1f053a82784da078999ed.patch.
=> xreader-3.8.2_1: running pre-configure hook: 00-gnu-configure-asneeded ...
=> xreader-3.8.2_1: running pre-configure hook: 01-override-config ...
=> xreader-3.8.2_1: running pre-configure hook: 02-script-wrapper ...
=> xreader-3.8.2_1: running do_configure ...
DEPRECATION: "pkgconfig" entry is deprecated and should be replaced by "pkg-config"
The Meson build system
Version: 1.3.0
Source dir: /builddir/xreader-3.8.2
Build dir: /builddir/xreader-3.8.2/build
Build type: cross build
Project name: xreader
Project version: 3.8.2
C compiler for the host machine: arm-linux-musleabihf-gcc (gcc 12.2.0 "arm-linux-musleabihf-gcc (GCC) 12.2.0")
C linker for the host machine: arm-linux-musleabihf-gcc ld.bfd 2.39
C++ compiler for the host machine: arm-linux-musleabihf-c++ (gcc 12.2.0 "arm-linux-musleabihf-g++ (GCC) 12.2.0")
C++ linker for the host machine: arm-linux-musleabihf-c++ ld.bfd 2.39
C compiler for the build machine: cc (gcc 12.2.0 "cc (GCC) 12.2.0")
C linker for the build machine: cc ld.bfd 2.39
C++ compiler for the build machine: g++ (gcc 12.2.0 "g++ (GCC) 12.2.0")
C++ linker for the build machine: g++ ld.bfd 2.39
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: arm
Host machine cpu: armv6l
Target machine cpu family: arm
Target machine cpu: armv6l
Found pkg-config: YES (/builddir/.xbps-xreader/wrappers/arm-linux-musleabihf-pkg-config) 0.29.2
Run-time dependency cairo found: YES 1.18.0
Run-time dependency gail-3.0 found: YES 3.24.38
Run-time dependency gio-2.0 found: YES 2.78.0
Run-time dependency glib-2.0 found: YES 2.78.0
Run-time dependency gmodule-2.0 found: YES 2.78.0
Run-time dependency gtk+-3.0 found: YES 3.24.38
Run-time dependency ice found: YES 1.1.1
Run-time dependency sm found: YES 1.2.4
Run-time dependency x11 found: YES 1.8.7
Run-time dependency xapp found: YES 2.6.1
Run-time dependency libxml-2.0 found: YES 2.11.4
Run-time dependency zlib found: YES 1.3
Run-time dependency libsecret-1 found: YES 0.21.1
Run-time dependency gtk+-unix-print-3.0 found: YES 3.24.38
Run-time dependency poppler-glib found: YES 23.12.0
Run-time dependency libspectre found: YES 0.2.12
Run-time dependency libtiff-4 found: YES 4.5.1
Run-time dependency libgxps found: YES 0.3.2
Run-time dependency webkit2gtk-4.1 found: YES 2.40.0
Library m found: YES
Program intltool-merge found: YES (/usr/bin/intltool-merge)
WARNING: You should add the boolean check kwarg to the run_command call.
         It currently defaults to false,
         but it will default to true in future releases of meson.
         See also: https://github.com/mesonbuild/meson/issues/9300
Configuring config.h using configuration
Found pkg-config: YES (/usr/bin/pkg-config) 0.29.2
Build-time dependency glib-2.0 found: YES 2.78.0
Program /usr/bin/glib-mkenums found: YES (/usr/bin/glib-mkenums)
Dependency glib-2.0 found: YES 2.78.0 (cached)
Program /usr/bin/glib-mkenums found: YES (/usr/bin/glib-mkenums)
Configuring ev-version.h using configuration
Run-time dependency gobject-introspection-1.0 found: YES 1.76.1
Dependency glib-2.0 found: YES 2.78.0 (cached)
Program /usr/bin/glib-mkenums found: YES (/usr/bin/glib-mkenums)
Dependency glib-2.0 found: YES 2.78.0 (cached)
Program /usr/bin/glib-mkenums found: YES (/usr/bin/glib-mkenums)
Dependency glib-2.0 found: YES 2.78.0 (cached)
Program /usr/bin/glib-genmarshal found: YES (/usr/bin/glib-genmarshal)
Configuring org.x.reader.Daemon.service using configuration
Configuring xreader.desktop.in using configuration
Build-time dependency gio-2.0 found: YES 2.78.0
Program /usr/bin/glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Dependency glib-2.0 found: YES 2.78.0 (cached)
Program /usr/bin/glib-genmarshal found: YES (/usr/bin/glib-genmarshal)
Dependency gio-2.0 found: YES 2.78.0 (cached)
Program /usr/bin/glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Dependency gio-2.0 found: YES 2.78.0 (cached)
Program /usr/bin/gdbus-codegen found: YES (/usr/bin/gdbus-codegen)
Dependency gio-2.0 found: YES 2.78.0 (cached)
Program /usr/bin/gdbus-codegen found: YES (/usr/bin/gdbus-codegen)
Program msgfmt found: YES (/usr/bin/msgfmt)
Program msginit found: YES (/usr/bin/msginit)
Program msgmerge found: YES (/usr/bin/msgmerge)
Program xgettext found: YES (/usr/bin/xgettext)
Program testFileMenu.py found: YES (/builddir/xreader-3.8.2/test/testFileMenu.py)
Program testEditMenu.py found: YES (/builddir/xreader-3.8.2/test/testEditMenu.py)
Program testHelpMenu.py found: YES (/builddir/xreader-3.8.2/test/testHelpMenu.py)
Program testZoom.py found: YES (/builddir/xreader-3.8.2/test/testZoom.py)
Program testGoMenu.py found: YES (/builddir/xreader-3.8.2/test/testGoMenu.py)
Program testBookmarksMenu.py found: YES (/builddir/xreader-3.8.2/test/testBookmarksMenu.py)
Program testEncryptedFile.py found: YES (/builddir/xreader-3.8.2/test/testEncryptedFile.py)
Program testFileReloading.py found: YES (/builddir/xreader-3.8.2/test/testFileReloading.py)
Program testWrongFileExtension.py found: YES (/builddir/xreader-3.8.2/test/testWrongFileExtension.py)
Configuring xreader-document-1.5.pc using configuration
Configuring xreader-view-1.5.pc using configuration
Message: prefix = /usr
Message: bindir = bin
Message: datadir = share
Message: libdir = lib32
Message: includedir = include
Message: libexecdir = libexec
Message: desktopdir = share/applications
Message: schema_dir = share/glib-2.0/schemas
Message: ENABLE_DBUS = true
Message: MathJax directory = /usr/share/mathjax
Message: Backends enabled:
Message:     pdf
Message:     ps
Message:     tiff
Message:     xps
Message:     epub
Build targets in project: 152

xreader 3.8.2

  User defined options
    Cross files   : /builddir/.xbps-xreader/wrappers/meson/xbps_meson.cross
    auto_features : auto
    bindir        : /usr/bin
    buildtype     : plain
    datadir       : /usr/share
    includedir    : /usr/include
    infodir       : /usr/share/info
    libdir        : /usr/lib32
    libexecdir    : /usr/libexec
    localedir     : /usr/share/locale
    localstatedir : /var
    mandir        : /usr/share/man
    prefix        : /usr
    sbindir       : /usr/bin
    sharedstatedir: /var/lib
    sysconfdir    : /etc
    wrap_mode     : nodownload
    b_lto         : true
    b_ndebug      : true
    b_staticpic   : true
    introspection : true
    thumbnailer   : false

Found ninja-1.11.1 at /usr/bin/ninja
=> xreader-3.8.2_1: running pre-build hook: 02-script-wrapper ...
=> xreader-3.8.2_1: running do_build ...
ninja: Entering directory `build'
[1/274] Compiling C object cut-n-paste/zoom-control/liblibephyzoom.a.p/ephy-zoom-action.c.o
[2/274] Compiling C object cut-n-paste/zoom-control/liblibephyzoom.a.p/ephy-zoom-control.c.o
[3/274] Compiling C object cut-n-paste/zoom-control/liblibephyzoom.a.p/ephy-zoom.c.o
[4/274] Linking static target cut-n-paste/zoom-control/liblibephyzoom.a
[5/274] Compiling C object cut-n-paste/totem-screensaver/libtotemscrsaver.a.p/totem-scrsaver.c.o
[6/274] Linking static target cut-n-paste/totem-screensaver/libtotemscrsaver.a
[7/274] Compiling C object cut-n-paste/smclient/libsmclient.a.p/eggsmclient.c.o
[8/274] Compiling C object cut-n-paste/smclient/libsmclient.a.p/eggdesktopfile.c.o
[9/274] Compiling C object cut-n-paste/smclient/libsmclient.a.p/eggsmclient-xsmp.c.o
[10/274] Linking static target cut-n-paste/smclient/libsmclient.a
[11/274] Compiling C object cut-n-paste/synctex/libsynctex.a.p/synctex_parser.c.o
[12/274] Compiling C object cut-n-paste/synctex/libsynctex.a.p/synctex_parser_utils.c.o
[13/274] Linking static target cut-n-paste/synctex/libsynctex.a
[14/274] Generating GObject enum file libdocument/ev-document-type-builtins.h (wrapped by meson to capture output)
[15/274] Generating GObject enum file libdocument/ev-document-type-builtins.c (wrapped by meson to capture output)
[16/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/meson-generated_.._ev-document-type-builtins.c.o
[17/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-annotation.c.o
[18/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-async-renderer.c.o
[19/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-attachment.c.o
[20/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-backends-manager.c.o
[21/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-layer.c.o
[22/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-link.c.o
[23/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-link-action.c.o
[24/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-link-dest.c.o
[25/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-image.c.o
[26/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-init.c.o
[27/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document.c.o
[28/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document-annotations.c.o
[29/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document-attachments.c.o
[30/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document-factory.c.o
[31/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document-thumbnails.c.o
[32/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document-fonts.c.o
[33/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document-layers.c.o
[34/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document-links.c.o
[35/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document-images.c.o
[36/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document-print.c.o
[37/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document-security.c.o
[38/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document-find.c.o
[39/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document-transition.c.o
[40/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document-forms.c.o
[41/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document-text.c.o
[42/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-form-field.c.o
[43/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-debug.c.o
[44/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-file-exporter.c.o
[45/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-file-helpers.c.o
[46/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-mapping-list.c.o
[47/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-module.c.o
[48/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-page.c.o
[49/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-render-context.c.o
[50/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-selection.c.o
[51/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-transition-effect.c.o
[52/274] Compiling C object libdocument/libxreaderdocument.so.3.0.0.p/ev-document-misc.c.o
[53/274] Linking target libdocument/libxreaderdocument.so.3.0.0
[54/274] Generating symbol file libdocument/libxreaderdocument.so.3.0.0.p/libxreaderdocument.so.3.0.0.symbols
[55/274] Generating libdocument/XreaderDocument-1.5.gir with a custom command (wrapped by meson to set env)
../libdocument/ev-annotation.c:706: Warning: XreaderDocument: multiple comment blocks documenting 'ev_annotation_set_area:' identifier (already seen at ev-annotation.c:687).
../libdocument/ev-file-helpers.c:200: Error: XreaderDocument: identifier not found on the first line:
 * This function is copied from
   ^
../libdocument/ev-document-misc.c:31: Error: XreaderDocument: identifier not found on the first line:
 * Returns a new GdkPixbuf that is suitable for placing in the thumbnail view.
   ^
../libdocument/ev-document-info.h:70: Warning: XreaderDocument: symbol='PERMISSIONS_FULL': Unknown namespace for symbol 'PERMISSIONS_FULL'
../libdocument/ev-document-misc.h:37: Warning: XreaderDocument: symbol='DEFAULT_DPI': Unknown namespace for symbol 'DEFAULT_DPI'
../libdocument/ev-document.c:423: Warning: XreaderDocument: ev_document_synctex_backward_search: unknown parameter 'page' in documentation comment, should be 'page_index'
../libdocument/ev-backends-manager.h:42: Warning: XreaderDocument: ev_backends_manager_get_document: return value: Missing (transfer) annotation
../libdocument/ev-backends-manager.h:48: Warning: XreaderDocument: ev_backends_manager_get_document_type_info: return value: Invalid non-constant return of bare structure or union; register as boxed type or (skip)
../libdocument/ev-backends-manager.h:50: Warning: XreaderDocument: ev_backends_manager_get_all_types_info: return value: Missing (element-type) annotation
../libdocument/ev-mapping-list.h:37: Warning: XreaderDocument: ev_mapping_list_ref: return value: Invalid non-constant return of bare structure or union; register as boxed type or (skip)
../libdocument/ev-mapping-list.h:41: Warning: XreaderDocument: ev_mapping_list_get_list: return value: Missing (element-type) annotation
../libdocument/ev-mapping-list.h:42: Warning: XreaderDocument: ev_mapping_list_find: return value: Invalid non-constant return of bare structure or union; register as boxed type or (skip)
../libdocument/ev-mapping-list.h:44: Warning: XreaderDocument: ev_mapping_list_find_custom: argument func: Missing (scope) annotation for callback without GDestroyNotify (valid: call, async, forever)
../libdocument/ev-mapping-list.h:44: Warning: XreaderDocument: ev_mapping_list_find_custom: return value: Invalid non-constant return of bare structure or union; register as boxed type or (skip)
../libdocument/ev-mapping-list.h:52: Warning: XreaderDocument: ev_mapping_list_nth: return value: Invalid non-constant return of bare structure or union; register as boxed type or (skip)
../libdocument/ev-mapping-list.h:34: Warning: XreaderDocument: ev_mapping_list_new: argument list: Missing (element-type) annotation
../libdocument/ev-mapping-list.h:34: Warning: XreaderDocument: ev_mapping_list_new: return value: Invalid non-constant return of bare structure or union; register as boxed type or (skip)
../libdocument/ev-mapping-list.h:34: Warning: XreaderDocument: ev_mapping_list_new: argument list: Missing (element-type) annotation
../libdocument/ev-mapping-list.h:34: Warning: XreaderDocument: ev_mapping_list_new: return value: Invalid non-constant return of bare structure or union; register as boxed type or (skip)
../libdocument/ev-file-helpers.c:175: Warning: XreaderDocument: ev_mkstemp_file: return value: Missing (transfer) annotation
../libdocument/ev-document.h:149: Warning: XreaderDocument: ev_document_get_page: return value: Missing (transfer) annotation
../libdocument/ev-document.c:479: Warning: XreaderDocument: ev_document_synctex_forward_search: return value: Invalid non-constant return of bare structure or union; register as boxed type or (skip)
../libdocument/ev-document.h:125: Warning: XreaderDocument: ev_document_get_doc_mutex: return value: Invalid non-constant return of bare structure or union; register as boxed type or (skip)
../libdocument/ev-document.h:131: Warning: XreaderDocument: ev_document_get_fc_mutex: return value: Invalid non-constant return of bare structure or union; register as boxed type or (skip)
../libdocument/ev-document-misc.h:42: Warning: XreaderDocument: ev_document_misc_get_thumbnail_frame: return value: Missing (transfer) annotation
../libdocument/ev-document-misc.h:46: Warning: XreaderDocument: ev_document_misc_get_loading_thumbnail: return value: Missing (transfer) annotation
../libdocument/ev-document-misc.h:50: Warning: XreaderDocument: ev_document_misc_render_loading_thumbnail: return value: Missing (transfer) annotation
../libdocument/ev-document-misc.h:54: Warning: XreaderDocument: ev_document_misc_render_thumbnail_with_frame: return value: Missing (transfer) annotation
../libdocument/ev-document-misc.h:69: Warning: XreaderDocument: ev_document_misc_pixbuf_from_surface: return value: Missing (transfer) annotation
../libdocument/ev-document-annotations.h:91: Warning: XreaderDocument: ev_document_annotations_get_annotations: return value: Invalid non-constant return of bare structure or union; register as boxed type or (skip)
../libdocument/ev-document-attachments.h:55: Warning: XreaderDocument: ev_document_attachments_get_attachments: return value: Missing (element-type) annotation
../libdocument/ev-document-find.h:63: Warning: XreaderDocument: ev_document_find_find_text: return value: Missing (element-type) annotation
../libdocument/ev-link-action.h:58: Warning: XreaderDocument: ev_link_action_get_dest: return value: Missing (transfer) annotation
../libdocument/ev-link-action.h:63: Warning: XreaderDocument: ev_link_action_get_show_list: return value: Missing (element-type) annotation
../libdocument/ev-link-action.h:64: Warning: XreaderDocument: ev_link_action_get_hide_list: return value: Missing (element-type) annotation
../libdocument/ev-link-action.h:65: Warning: XreaderDocument: ev_link_action_get_toggle_list: return value: Missing (element-type) annotation
../libdocument/ev-link-action.h:74: Warning: XreaderDocument: ev_link_action_new_layers_state: argument show_list: Missing (element-type) annotation
../libdocument/ev-link-action.h:74: Warning: XreaderDocument: ev_link_action_new_layers_state: argument hide_list: Missing (element-type) annotation
../libdocument/ev-link-action.h:74: Warning: XreaderDocument: ev_link_action_new_layers_state: argument toggle_list: Missing (element-type) annotation
../libdocument/ev-link.h:50: Warning: XreaderDocument: ev_link_get_action: return value: Missing (transfer) annotation
../libdocument/ev-document-forms.h:88: Warning: XreaderDocument: ev_document_forms_get_form_fields: return value: Invalid non-constant return of bare structure or union; register as boxed type or (skip)
../libdocument/ev-image.h:60: Warning: XreaderDocument: ev_image_get_pixbuf: return value: Missing (transfer) annotation
../libdocument/ev-document-images.h:58: Warning: XreaderDocument: ev_document_images_get_image_mapping: return value: Invalid non-constant return of bare structure or union; register as boxed type or (skip)
../libdocument/ev-document-images.h:60: Warning: XreaderDocument: ev_document_images_get_image: return value: Missing (transfer) annotation
../libdocument/ev-document-layers.h:75: Warning: XreaderDocument: ev_document_layers_get_layers: return value: Missing (transfer) annotation
../libdocument/ev-document-links.h:76: Warning: XreaderDocument: ev_document_links_get_links_model: return value: Missing (transfer) annotation
../libdocument/ev-document-links.h:78: Warning: XreaderDocument: ev_document_links_get_links: return value: Invalid non-constant return of bare structure or union; register as boxed type or (skip)
../libdocument/ev-document-links.h:80: Warning: XreaderDocument: ev_document_links_find_link_dest: return value: Missing (transfer) annotation
../libdocument/ev-document-thumbnails.h:59: Warning: XreaderDocument: ev_document_thumbnails_get_thumbnail: return value: Missing (transfer) annotation
../libdocument/ev-document-transition.h:59: Warning: XreaderDocument: ev_document_transition_get_effect: return value: Missing (transfer) annotation
[56/274] Generating libdocument/XreaderDocument-1.5.typelib with a custom command
[57/274] Generating GObject enum file libview/ev-view-type-builtins.h (wrapped by meson to capture output)
[58/274] Generating GObject enum file libview/ev-view-type-builtins.c (wrapped by meson to capture output)
[59/274] Generating glib marshaller header libview/ev-view-marshal_h
INFO: Reading ../libview/ev-view-marshal.list...
[60/274] Generating glib marshaller source libview/ev-view-marshal_c
INFO: Reading ../libview/ev-view-marshal.list...
[61/274] Compiling C object libview/libxreaderview.so.3.0.0.p/meson-generated_.._ev-view-type-builtins.c.o
[62/274] Compiling C object libview/libxreaderview.so.3.0.0.p/meson-generated_.._.._libdocument_ev-document-type-builtins.c.o
[63/274] Compiling C object libview/libxreaderview.so.3.0.0.p/meson-generated_.._ev-view-marshal.c.o
[64/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-annotation-window.c.o
[65/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-document-model.c.o
[66/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-loading-window.c.o
[67/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-jobs.c.o
[68/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-job-scheduler.c.o
[69/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-link-accessible.c.o
[70/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-page-cache.c.o
[71/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-pixbuf-cache.c.o
[72/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-print-operation.c.o
[73/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-stock-icons.c.o
[74/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-timeline.c.o
[75/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-transition-animation.c.o
[76/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-view.c.o
[77/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-web-view.c.o
[78/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-view-accessible.c.o
[79/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-view-cursor.c.o
[80/274] Compiling C object libview/libxreaderview.so.3.0.0.p/ev-view-presentation.c.o
[81/274] Linking target libview/libxreaderview.so.3.0.0
[82/274] Generating symbol file libview/libxreaderview.so.3.0.0.p/libxreaderview.so.3.0.0.symbols
```

</details>

A similar hang seems to happen in xreader 3.8.4 in my bumped PR, but near the end of the build.

### Steps to reproduce

1. Do `xbps-src` cross-build of `xreader` for `armv6l-musl` or `armv7l-musl`

**Comment by chrysos349** [comment] 2024-02-19 06:21
The issue is fixed now. This was due to the same qemu error I had here - #48747, and here - https://github.com/void-linux/void-packages/pull/48768#issuecomment-1950991944

You can close the issue.

**Closed** 2024-02-19 11:42 UTC
Labels: bug, needs-testing
