### ISSUE TITLE
Package request: Common Desktop Environment (CDE)

### ISSUE THREAD

**Issue by G00d-Syst3m** [void-linux/void-packages#53724] opened 2024-12-27 18:33 UTC
### Package name

cde-desktop (or cdesktopenv)

### Package homepage

https://cdesktopenv.sourceforge.io/

### Description

Common Desktop Environment (CDE) is a desktop environment, based on the Motif widget toolkit.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment] 2024-12-27 19:28
duplicate of #25839

**Closed by classabbyamp** 2024-12-27 19:28 UTC
Labels: request
