### ISSUE TITLE
gnuplot doesn't use alpha for lines

### ISSUE THREAD

**Issue by TOertel** [void-linux/void-packages#12035] opened 2019-05-30 14:13 UTC
### System

* xuname:  
Void 4.19.36_1 x86_64 AuthenticAMD notuptodate rrFFFF
(Everything is up to date except the kernel)

* package:  
gnuplot-5.2.6_1 (at least)

### Expected behavior
Drawing lines with alpha color should show as translucent.

### Actual behavior
Drawing lines are always 100% opaque.

### Steps to reproduce the behavior
````
gnuplot

  plot x lw 10, -x lw 10 lc rgb "#77000000"
  plot x lw 10, -x lw 10 lc rgb "#FF000000"  
  plot x lw 10, -x lw 10 lc rgb "#00000000" 
````

These should all display differently, but display the same.  Doing `set term png; set output "test.png"` and re-running the above generate the same incorrect result.

Alpha channel for lines was added in 5.2, I haven't found any other examples of alpha not working on the internet, so it seems like it's just void (or perhaps just me).

gnuplot-wx and gnuplot-qt both correctly display the alpha when drawing to X.  All commands fail when terminal is png or jpeg.

**Comment by jnbr** [comment] 2019-05-30 15:11
It works (at least this [example](http://gnuplot.sourceforge.net/demo/rgba_lines.html))with `gnuplot-wx` and `gnuplot-qt` with terminal type respectively `wx` or `qt` and also with terminal type `pngcairo`.
I don't know why `pngcairo` is missing in `gnuplot`.

**Comment by TOertel** [comment] 2019-05-30 20:06
Confirmed.  gnuplot-wx & gnuplot-qt both work when displaying to X.

However, they all fail when drawing to png (and jpg).

**Comment by jnbr** [comment] 2019-05-30 20:48
png works for me with `set terminal pngcairo`

**Comment by TOertel** [comment] 2019-05-30 21:03
Confirmed.  `set terminal pngcairo` also works correctly for me.

Can you confirm that the cases I've outlined *don't* work for you as well?

**Comment by jnbr** [comment] 2019-05-30 21:19
Yes, it does not work with x11 or png terminal.

**Comment by jnbr** [comment] 2019-05-31 11:15
Anything left to do here or can this be closed?

**Comment by TOertel** [comment] 2019-05-31 11:32
Do we have any evidence this is actually an upstream bug vs something in the build?

( I guess I don't know how these sorts of things are handled, in general. )

**Comment by jnbr** [comment] 2019-06-02 19:47
Not sure what exactly you are referring to as a potential bug.
In case you are referring to alpha not working in png and x11, I think this is the intended behavior by upstream. You can discuss this with upstream.
In case you are referring to the `gnuplot` package not having `pngcairo`, this might be a packaging bug, but I don't see it as a real problem because we have `gnuplot-qt` and `gnuplot-wx`.

I'm closing this. Feel free to reopen if you think different about it.

**Closed by jnbr** 2019-06-02 19:47 UTC

**Comment by TOertel** [comment] 2019-06-03 12:47
I was referring to the different behaviors, alpha not working in png, jpeg and x11.  I have no evidence that this is "intended behavior".

So, for now, I've opened an upstream bug: https://sourceforge.net/p/gnuplot/bugs/2177
