### ISSUE TITLE
last utility is broken by /dev/null/wtmp usage in Musl (locs-musl setting)

### ISSUE THREAD

**Issue by Kerrnel** [void-linux/void-packages#39048] opened 2022-09-02 04:29 UTC
### Is this a new report?

No - Issue #35158 from Jan '22 gone stale

### System Info

Void 5.18.19_1 x86_64-musl GenuineIntel uptodate rFFFFF

### Package(s) Affected

util-linux-2.38.1_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://gitlab.alpinelinux.org/alpine/aports/-/issues/3282

(Erroneously closed; and referred to months later)

### Expected behaviour

On non-Musl Void

 $ last -n 20
(akua@fish) Password: 
akua     ssh          10.6.6.17        Fri Sep  2 00:24   still logged in
akua     ssh          10.6.6.17        Fri Sep  2 00:24 - 00:24  (00:00)
akua     ssh          10.6.6.17        Fri Sep  2 00:24 - 00:24  (00:00)
akua     ssh          10.6.6.17        Fri Sep  2 00:24 - 00:24  (00:00)
akua     ssh          10.6.6.17        Fri Sep  2 00:24 - 00:24  (00:00)
akua     pts/3        10.6.6.15        Fri Sep  2 00:06 - 00:06  (00:00)
akua     ssh          10.6.6.15        Fri Sep  2 00:06 - 00:06  (00:00)
akua     pts/2        10.6.6.7         Wed Aug 31 04:03   still logged in
akua     ssh          10.6.6.7         Wed Aug 31 04:03 - 00:06 (1+20:03)
akua     pts/0        10.6.6.8         Wed Aug 31 03:59   still logged in
akua     ssh          10.6.6.8         Wed Aug 31 03:59 - 04:03  (00:03)
reboot   system boot  5.15.50_1        Wed Aug 31 02:07   still running
reboot   system boot  5.15.50_1        Wed Aug 31 02:05   still running
akua     pts/1        10.6.6.8         Sat Aug 27 16:29 - crash (3+09:36)
akua     ssh          10.6.6.8         Sat Aug 27 16:29 - crash (3+09:36)
akua     pts/0        10.6.6.7         Sat Aug 27 16:29 - crash (3+09:36)
akua     ssh          10.6.6.7         Sat Aug 27 16:29 - 16:29  (00:00)
reboot   system boot  5.15.50_1        Sat Aug 27 14:32   still running
root     ssh          10.6.6.15        Thu Aug 25 00:08 - 00:12  (00:04)
root     ssh          10.6.6.15        Wed Aug 24 23:59 - 00:03  (00:03)

wtmp begins Thu Mar  8 08:00:19 2018

or specifying the wtmp location

 $ last -f /var/log/wtmp -n 20
reboot   system boot  5.18.19_1        Thu Sep  1 16:14   still running
reboot   system boot  5.18.19_1        Thu Sep  1 15:26 - 16:12  (00:45)
reboot   system boot  5.18.19_1        Thu Sep  1 15:08 - 15:26  (00:18)
reboot   system boot  5.18.19_1        Thu Sep  1 13:40 - 15:07  (01:27)
reboot   system boot  5.18.19_1        Thu Sep  1 12:26 - 13:40  (01:13)
reboot   system boot  5.18.14_1        Sat Aug 27 18:36 - 12:26 (4+17:50)
reboot   system boot  5.18.14_1        Sat Aug 27 11:31 - 18:35  (07:04)
reboot   system boot  5.18.14_1        Sat Aug 27 11:24 - 18:35  (07:10)
reboot   system boot  5.18.14_1        Sat Aug 27 09:53 - 11:24  (01:30)
reboot   system boot  5.18.14_1        Sat Aug 27 07:03 - 09:53  (02:49)
reboot   system boot  5.9.16_1         Sat Jan 16 12:41 - 12:54  (00:13)
reboot   system boot  5.9.16_1         Sat Jan 16 16:53 - 16:55  (00:02)
reboot   system boot  4.15.8_1         Sat Jan 16 16:02 - 16:50  (00:48)

### Actual behaviour

Without specifying on Musl

 $ last -n 20
last: cannot open /dev/null/wtmp: Not a directory

### Steps to reproduce

From cli: last

It seems the location is set to /dev/null/wtmp for some reason in a musl specific WTMP_FILE_LOC define; this was collateral damage.

[srcpkgs/acct/files/locs-musl](https://github.com/void-linux/void-packages/blob/a279abf769ef7cab6ebb49d8c99bf774a2ff97b8/srcpkgs/acct/files/locs-musl)

**Comment by sgn** [comment] 2022-09-02 06:14
musl doesn't support utmp and wtmp

**Comment by sgn** [comment] 2022-09-02 06:15
You may want to package https://skarnet.org/software/utmps/ for musl to support utmp and wtmp, I don't know if it works.

**Comment by ahesford** [comment] 2022-09-11 12:09
Closing because this is expected behavior for a tool that attempts to read login databases that musl expressly declines to write.

**Closed by ahesford** 2022-09-11 12:09 UTC
Labels: bug, needs-testing
