### ISSUE TITLE
KDE Wayland Broken on Latest Nvidia Driver

### ISSUE THREAD

**Issue by TrueTechie** [void-linux/void-packages#40235] opened 2022-10-30 18:35 UTC
### Is this a new report?

Yes

### System Info

Void 5.19.16_1 x86_64 GenuineIntel uptodate FFFFF

### Package(s) Affected

nvidia-515.65.01_2, plasma-wayland-protocols-1.9.0_1

### Expected behaviour

The Plasma Wayland session works with `nvidia-drm` enabled just as other window managers such as Wayfire do.

### Actual behaviour

The desktop launches though it is incredibly slow and laggy, making it unusable. According to [this comment](https://www.reddit.com/r/voidlinux/comments/y86m7f/comment/iu5bkt7/?context=3) on Reddit, this does not happen with the 470 series of Nvidia drivers. I think this might be an EGL/GBM issue.

If there is a way to solve this issue without modifying the package, such as an environment variable, I haven't found it and it should be put somewhere in the docs.

### Steps to reproduce

1. Install Nvidia drivers 
2. Enable kernel modesetting (`nvidia-drm`) on boot
3. Install `kde5` and the various packages required to run a Wayland session in Plasma
4. Launch the Wayland session from SDDM

**Comment by furryfixer** [comment] 2022-10-30 23:38
The reddit comment referred to above was mine. I have since installed Void Plasma Wayland with nvidia for myself to investigate (GeForce GTX 1660 Ti), and can confirm this issue with nvidia515.65.01 and kernel 5.19.16_1. If it helps, this is what I have found so far:
- Does not occur on Plasma X11
- Occurs with startx as well as SDDM login
- Downgrading to nvidia470 xbps packages fixes it
- kwin_wayland takes nearly 100% cpu during this
- Occurs with more than one theme and icon set
- A key pressed within both Konsole (wayland) and lxterminal (Xwayland) is sometimes echoed repeatedly to the terminal window.
- Briefly corrects and lowers CPU usage after showing **irq-130nvidia** interrupt in top?   

Despite very slow startup, the latest version of kwin_wayland initially allows normal mouse cursor movement, but as soon as a cursor mouse-over on a desktop icon occurs, the issue arises.  Weirdly, when mousing over certain Panel icons, the problem goes away after the popup notification disappears.  Sometimes the popup seems to shift slightly just before disappearing, and then kwin CPU usage drops to normal, until trying to do almost anything but moving the mouse in an empty area of the desktop makes it recur.

**Comment by EwolBash** [comment] 2022-10-31 17:31
I'm also having this same issue. I did test Gnome-Wayland out of curiosity and the problem doesn't exist there.
If there is any information I can provide to help get this fixed let me know and I'll gladly provide it.

**Comment by furryfixer** [comment] 2022-11-01 10:27
There is a workaround for now. Either of two environment variable settings may fix it:   

**__GL_MaxFramesAllowed=1**   
or   
**__GL_YIELD=USLEEP**   

This would initially suggest a regression in nvidia drivers or kwin (upstream). However, the issue does not occur in Gnome Wayland on Void with the same packages (nvidia), and does not seem to occur in Plasma Wayland on non-Void distros with same or similar packages (wayland/kwin/plasma/qt). 

I am uncertain of any negative consequences to using the above workaround.

**Comment by furryfixer** [comment] 2022-11-23 16:17
After updates to qt5,nvidia,linux kernel,kwin, etc. failed to resolve this bug, I finally bypassed xbps, and manually downloaded and installed the nvidia 515.86.01 driver directly from nvidia.  Plasma/Wayland now works perfectly for both kernels linux-lts (5.10) and linux 6.0.9_1.  I would hope 1-2 others will confirm this.

I cannot find any reason why the Void build template creates this problem, but I can think of no other explanation.  I suggest focusing on how the Void build/install process differs from nvidia's.  It is exasperating that the bug only shows up in Plasma/Wayland, but not Gnome/Wayland.

**Comment by furryfixer** [comment] 2022-11-26 02:19
I have hopefully identified the problem.  Others please confirm, and if so, create a PR to fix this if you like, since I will be unable for the next several days at least. 

The file "**15_nvidia_gbm.json**" is misplaced.  Void's template installs it in the "**/usr/share/glvnd/egl_vendor.d/**" directory.  It should apparently be installed to the "**/usr/share/egl/egl_external_platform.d/**" directory.  Plasma/Wayland becomes fully functional by doing:

`sudo mv /usr/share/glvnd/egl_vendor.d/15_nvidia_gbm.json /usr/share/egl/egl_external_platform.d/15_nvidia_gbm.json`

A simple change to the vmove target for that file in the template should do it. I remain curious as to why Gnome was not obviously affected, since I thought I was forcing GBM through environment variables, but perhaps it was still using EGL streams on nvidia.

**Comment by cmhainesii** [comment] 2022-11-26 14:07
Nice! I tested this fix and it worked for me. I created a pr.

**Comment by kruceter** [comment] 2022-11-26 18:12
furryfixer's suggestion was merged in 4d9de55a669ae42a1612dfd2d363756ddfa4531d.

**Closed** 2022-11-26 18:21 UTC
Labels: bug
