### ISSUE TITLE
X11 GNOME shell crashes when dragging windows in activities overview

### ISSUE THREAD

**Issue by JamiKettunen** [void-linux/void-packages#50126] opened 2024-04-30 07:51 UTC
### Is this a new report?

Yes

### System Info

Void 6.6.29_1 x86_64-musl AuthenticAMD/VM uptodate F

### Package(s) Affected

gnome-shell-45.5_2

### Expected behaviour

Windows in the activities overview can be dragged around to other workspaces without issue.

### Actual behaviour

Attempting to move windows around in the activities overview by holding left click and dragging them towards another workspace simply crashes the GNOME shell with an `Oh no! Something has gone wrong.` screen with a `Log Out` button.

I cannot reproduce this under the Wayland session so it seems specific to the X11 session.

### Steps to reproduce

1. Select `GNOME on Xorg` in GDM
2. After logging in start any app (e.g. `nautilus`)
3. Open activities overview and try moving any open window to another workspace

**Comment by okawo80085** [comment] 2024-04-30 07:55
Same this happens on Void 6.6.29_1 x86_64 AuthenticAMD uptodate rrrrmmnFFFFFFF with Nvidia drivers

**Comment by oreo639** [comment] 2024-04-30 11:25
This is caused by https://github.com/void-linux/void-packages/commit/baeee86d11a7c6c941a0312700d35b8aed183851 as GNOME changed the cursor names between GNOME 45 and GNOME 46.

**Comment by yyny** [comment] 2024-05-02 18:40
Can confirm too, it is ultimately a problem in `mutter` which [seems to already be fixed](https://gitlab.gnome.org/GNOME/mutter/-/commit/9f89421ef5abfe5143a777aa33eee308e81a7055).

This script should temporarily fix the crash:

```sh
CURSOR_THEME="$(gsettings get org.gnome.desktop.interface cursor-theme)"
sudo ln -s "/usr/share/icons/$CURSOR_THEME/cursors/default" "/usr/share/icons/$CURSOR_THEME/cursors/dnd-none"
sudo ln -s "/usr/share/icons/$CURSOR_THEME/cursors/default" "/usr/share/icons/$CURSOR_THEME/cursors/dnd-move"
```

**Comment by okawo80085** [comment] 2024-05-02 19:26
Had to add `CURSOR_THEME=$(echo "$CURSOR_THEME" | tr -d "'")` before calling the `ln` commands, but yea that fixed it

**Comment by oreo639** [comment] 2024-06-26 07:09
It should be fixed once mutter 46 is done building: https://github.com/void-linux/void-packages/commit/c423aacda25c38393277909c5762731758cd2d8f

**Comment by oreo639** [comment] 2024-06-26 09:39
Should be available now, let me know if this issue persists.

**Closed by oreo639** 2024-06-26 09:39 UTC
Labels: bug, needs-testing
