### ISSUE TITLE
Update to Python 3.9 appears to break multiple python packages in a Docker Container

### ISSUE THREAD

**Issue by Frick-David** [void-linux/void-packages#25606] opened 2020-10-14 18:41 UTC
-- Docker Container
-- Python 3.9 no longer byte compiles C-linked Python libraries such as `numpy` or `pandas` successfully.
-- I am hoping that a hold on Python in the container will work until 3.9 works again

I would say this almost might break regular void installs.
To attempt a reproduce. Install python3.9 and then install say `Flask-SQLAlchemy` and it will try and byte compile that which would probably throw the error.

**Comment by ahesford** [comment] 2020-10-14 19:26
I already have numpy and pandas installed, but reconfiguring shows successful byte compilation:
```
# xbps-reconfigure -f python3-numpy
python3-numpy: configuring ...
Byte-compiling python3.9 code for module numpy...
Updating ldconfig(8) cache...
python3-numpy: configured successfully.

# xbps-reconfigure -f python3-pandas
python3-pandas: configuring ...
Byte-compiling python3.9 code for module pandas...
Updating ldconfig(8) cache...
python3-pandas: configured successfully.
```

Similarly, I can install `python3-Flask-SQLAlchemy` and see no errors about byte-compiling that package or any of its dependencies. Did you upgrade all of the `python3-*` packages alongside `python3`?

**Comment by ahesford** [comment] 2020-10-14 19:51
FYI, [this Dockerfile](https://github.com/void-linux/void-packages/files/5380526/Dockerfile.txt) builds an image with byte-compiled Python packages. Do you have some cached layer that is causing problems? Try building your image with `--no-cache`.

**Comment by ahesford** [comment] 2020-11-05 14:15
Ping; have you uncovered any more about your issue?

**Comment by esauvisky** [comment] 2020-11-29 02:55
I'm unaware of what this project is about, but given the behavior and errors were very similar, here's some information I gathered:

All my images that were using:
    
    FROM python:3-slim

And required byte-compiling libs, would no longer build properly.  After some testing, I managed to find a fix, by installing `build-essentials` via apt before installing libs via pip. That made the build process take longer and the final image to be bigger, but not as big as if I were to use `FROM python:3`, so I kept that and just removed `build-essentials` after pip successfully installed the dependencies.

I'm still not sure why this behavior begun on python 3.9 though 🤷, but hope this helps people with the same issue.

**Comment by ahesford** [comment] 2020-11-29 03:05
The `python:3-slim` and `python:3` images are published by the Python project and are not built on Void Linux. Any issues there are unrelated to Void's move to Python 3.9.

Closing this issue because I am unable to reproduce, the original reporter has been unresponsive and the latest comment from @esauvisky makes me wonder whether the original report was even about Void Linux containers.

**Closed by ahesford** 2020-11-29 03:05 UTC

**Comment by Frick-David** [comment] 2020-11-30 03:16
@ahesford what you wrote seemed to fix the error . I was not using the python containers as those are based on Debian, not void. I do believe it much have been something in Docker's caching. Thanks for pointing that out. You were correct to close the issue. Thanks!
