### ISSUE TITLE
alacritty, i965_dri segfault

### ISSUE THREAD

**Issue by svenper** [void-linux/void-packages#974] opened 2018-07-17 09:53 UTC
### System

* xuname:  
  `Void 4.17.6_1 x86_64-musl GenuineIntel notuptodate hold rrnFFFFFFFFFF`
  (LTS kernel and a mousepad driver on hold, otherwise current)
* package:  
  `alacritty-0.1.0.20180705_2`

### Expected behavior
  Program starts as normal.

### Actual behavior
  Program segfaults at start.

### Steps to reproduce the behavior
  Launch the program.

### `gdb` mishaps
  [`gdb` output](https://gist.githubusercontent.com/svenper/98a448cb99dcfe3f14ddb0359c58d65e/raw) (rust?)

**Comment by tawsi-melek** [comment] 2018-07-17 10:22
This is probably a duplicate of #921 & #933.

But in short, thanks to Gottox, you may try to run alacritty like this:
`MESA_GLSL_CACHE_DISABLE=1 alacritty`

Also, for me, deleting the ~/.cache/mesa_shader_cache folder solved the problem completely (it seems), but Gottox said that it kept segfaulting for him on the other hand.

**Comment by Gottox** [comment] 2018-07-17 10:32
duplicate of #933.

**Closed by Gottox** 2018-07-17 10:32 UTC
Labels: duplicate

**Comment by svenper** [comment] 2018-07-17 10:33
@tawsi-melek Thanks, the `MESA_GLSL_CACHE_DISABLE=1` line worked around the issue for me as well. Deleting the cache did not, however.
