### ISSUE TITLE
Kernel Panic after updating void linux

### ISSUE THREAD

**Issue by noloop** [void-linux/void-packages#11814] opened 2019-05-18 23:34 UTC
### System

* xuname:  
  Void 4.19.15_1 x86_64 GenuineIntel uptodate rFF
* package:
Linux 4.19.42_1

### Expected behavior
Do not receive a panic kernel at startup.

### Actual behavior
Receiving a panic kernel at startup.

### Steps to reproduce the behavior

`xbps install -Su`

Update Linux 4.19.15_1 -> 4.19.42_1

Img kernel panic screen:

![kernel panic screen](https://i.imgur.com/vzXAUnu.jpg)

I can still access the system normally under Linux 4.19.15_1

>UP:

I've updated void linux again, and now it has upgraded to linuz-4.19.44_1 and kernel panic still occurs.

.

**Comment by abenson** [comment] 2019-05-19 15:31
Is your `/boot` full? There may not have been enough space to generate the required `initramfs`.

**Comment by svenper** [comment] 2019-05-20 01:12
I also get panics on old LTS 4.14.120 and `/boot` has 125M free.

**Comment by Anachron** [comment] 2019-05-20 08:10
I have the same issue on my `RPI` (aarch64) but not ever boot causes a panic.

**Comment by noloop** [comment] 2019-05-20 10:27
Not full no, my `/boot` is 2GB, since I've had trouble with it full, and I did not want to have any more problems with it.

*sudo df -h:*

```
Sist. Arq.      Tam. Usado Disp. Uso% Montado em
/dev/sda1       2,0G  129M  1,8G   7% /boot
```

**Comment by Hoshpak** [comment] 2019-05-21 09:52
Could you post a screenshot of the error screen? Kernel Panics can occur for a large number of reasons and if no one else is able to reproduce it, it is unlikely to be fixed without further information.

**Comment by noloop** [comment] 2019-05-21 11:06
@Hoshpak I updated it up there with the screenshot.

**Comment by Hoshpak** [comment] 2019-05-24 06:55
Thanks, this looks pretty much like any generic "can't mount root file system" panic. Are you sure your initrd image is OK? It might be corrupted even if there's enough space available so regenerating it might be worth a try. You could also try again with 4.19.45. If you are using ext4, there's at least one kernel panic fixed in there.

**Comment by svenper** [comment] 2019-05-28 15:25
Update 4.14.120 → 4.14.122 solved the panic for me

**Comment by noloop** [comment] 2019-06-04 12:28
I am updating void linux again with another version of linux, and even then I get kernel panic, what should I reconfigure that might be wrong?

**Comment by pobetiger** [comment] 2019-06-07 02:34
@noloop, it looks like the kernel is not able to mount your root drive. If you can boot into the system, can you get the old kernel log and post that instead? If not, you might have to boot live cd and attempt to mount your root drive and see if there's anything wrong with it. Incidentally, what rootfs filesystem are you using? Maybe the drive is not properly loaded.

**Comment by xtraeme** [comment] 2020-02-25 09:05
stalled for a long while, reopen if you can reproduce it with recent kernels.

**Closed by xtraeme** 2020-02-25 09:05 UTC
Labels: bug
