### ISSUE TITLE
gdb libstdc++ frame gives warning: <line> <file>.h: No such file or directory

### ISSUE THREAD

**Issue by meator** [void-linux/void-packages#49207] opened 2024-03-09 20:32 UTC
### Is this a new report?

Yes

### System Info

Void 6.6.18_1 x86_64 GenuineIntel uptodate hold rrrdDFFFFFFFFFFFFFFFFFFFFFFFFFFFF

### Package(s) Affected

libstdc++-13.2.0_2 libstdc++-devel-13.2.0_2 libstdc++-dbg-13.2.0_2

### Expected behaviour

Everything being all right.

### Actual behaviour

I have the following program:

```c++
#include <string>

int main() {
    std::string{std::string{}};
}
```

When I compile it with

```
g++ -ggdb main.cpp
```

, debug it with `gdb` and try to step in the fourth line, I get
```
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=0x7fffffffe590)
    at ./build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.h:512
warning: 512	./build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.h: No such file or directory
```

`gdb` is trying to look into `./build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.h`, but it should be looking in `/usr/include/c++/13.2/bits/basic_string.h`.

This looks like `./build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.h` was the path in the build step of `libstdc++` (which is a subpackage of `gcc`) in the masterdir. This path doesn't match the path in a real installed system, which rightfully confuses gdb.

I have `libstdc++-13.2.0_2` `libstdc++-devel-13.2.0_2` and `libstdc++-dbg-13.2.0_2` installed, so I shouldn't be lacking debugging symbols.

### Steps to reproduce

I have first created this recording with slightly different code and it was intended for `#voidlinux`, but it is still relevant and useful: https://asciinema.org/a/646146

**Comment by meator** [comment] 2024-03-09 20:50
@classabbyamp suggested on `#voidlinux` that `gcc`'s template might have `-ffile-prefix-map` missing. This is likely the solution to this problem.

**Comment by oreo639** [comment] 2024-03-09 22:33
This issue is labeled as gdb not being able to step inside libstdc++ (which occurs per-instruction), but your issue appears to be that the file paths shown are the ones from build time? Am I misunderstanding?

Showing `/usr/include/c++/13.2/bits/basic_string.h` would not be correct in this instance since the debug symbols can also point to cpp files. The correct generalized path would be smth like `/usr/sources/libstdc++/...` which isn't supported by void since we don't have `-src` packages.

gdb supports a substitute path for this purpose:
https://sourceware.org/gdb/current/onlinedocs/gdb.html/Source-Path.html#set-substitute_002dpath

> suggested on `#voidlinux` that `gcc`'s template might have `-ffile-prefix-map` missing. This is likely the solution to this problem.

The opposite is the case, the `-ffile-prefix-map` is getting passed and is set up such that the wrksrc is replaced with `./`.
https://github.com/void-linux/void-packages/blob/7771ef865fa7b5312892b8c53dbfbc459cfdfd41/common/environment/configure/debug-debug-prefix-map.sh#L12-L13

**Comment by meator** [comment] 2024-03-10 06:49
So

```
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=0x7fffffffe590)
    at ./build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.h:512
warning: 512	./build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.h: No such file or directory
```

is the intended behavior?

**Comment by oreo639** [comment] 2024-03-10 07:17
> is the intended behavior?

I can't speak for what the other Void maintainers intend, but afaict it is working as it is written. In this case, you can use substitute-path to fix the locations for the includes.
For source files you can can download the un-patched sources from https://sources.voidlinux.org (this won't include patches and compile-time generated files though, so be aware of that. For example, the header in this instance is a compile-time generated file.)
Ofc you can also use `disas` to see the assembly.

**Comment by oreo639** [comment] 2024-03-10 07:34
I updated the title, let me know if it is incorrect.

**Comment by ahesford** [comment] 2024-03-14 11:48
This is definitely not a bug, but an expected consequence of our decision (implicit or otherwise) not to include source in debug packages.

I don't believe shipping source in debug packages is a good idea in general. There are a number of reasons why people might want debug symbols, but in many cases, also having the source sitting around may not be necessary or particularly useful. Having source available for this kinds of things should be an extra opt-in. We don't have a mechanism for that except shipping `-src` packages, which I'm sure nobody wants to do.

If you just need some context for debugging your own stuff, it's easy enough to `./xbps-src -I patch <pkg>` and look through the source. If you're actually trying to debug packaged software, this may be a bit more cumbersome, but there are probably better ways to debug and test packaged software than by trying to use only the packages.

Also note that the generated nature of the header in your example would pose substantial challenges to properly accumulating the source for distribution anyway.

I'm marking this WONTFIX; if any Void member wishes to reopen for more discussion, please do so.

**Closed by ahesford** 2024-03-14 11:48 UTC

**Comment by meator** [comment] 2024-03-14 17:40
Thanks for the explanation! I understand why was this issue closed.
