### ISSUE TITLE
[package request] tenacity | audio editor, fork of audacity

### ISSUE THREAD

**Issue by AspirusFromScratch** [void-linux/void-packages#32642] opened 2021-08-23 04:55 UTC
Source: https://github.com/tenacityteam/tenacity

Please add this fork of Audacity to the repo. It is a fork that deals with the new Audacity privacy policy and adds new features.

**Comment by paper42** [comment] 2021-08-23 05:04
duplicate of #32582

**Closed** 2021-08-23 05:04 UTC
