### ISSUE TITLE
Package request: wezterm

### ISSUE THREAD

**Issue by eoli3n** [void-linux/void-packages#39954] opened 2022-10-14 14:38 UTC
### Package name

wezterm

### Package homepage

https://github.com/wez/wezterm

### Description

A GPU-accelerated cross-platform terminal emulator and multiplexer written by @wez and implemented in Rust.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by paper42** [comment] 2022-10-14 14:49
duplicate of #35721

**Closed by paper42** 2022-10-14 14:49 UTC
Labels: request
