### ISSUE TITLE
Linux Kernal

### ISSUE THREAD

**Issue by ayoubkafi** [void-linux/void-packages#27423] opened 2020-12-25 14:34 UTC
### System

* xuname:  
  Void 5.9.16_1 x86_64 GenuineIntel uptodate rrFFF
* package:  
  linux-5.9_2

#### First
After booting Linux, this message appears
```
[    0.721523] DMAR: [Firmware Bug]: No firmware reserved region can cover this RMRR [0x00000000bdc00000-0x00000000bfffffff], contact BIOS vendor for fixes
```
and then the computer will continue

#### Second
Sometimes the system freezes for no reason. I can't move the mouse or switch between tty. The thing I can do is turn off the power from the computer
Once I checked out of the dwm window manager and was lucky enough to see this message before the system freezes
![error](https://user-images.githubusercontent.com/71545968/103137111-61033080-46c6-11eb-9bfa-5d2816882696.jpg)

**Comment by Mek101** [comment] 2020-12-29 10:01
What's your motherboard? Could it be damaged?

**Comment by leahneukirchen** [comment] 2020-12-30 18:27
Does kernel 5.4 work better?

May be related to https://bugzilla.kernel.org/show_bug.cgi?id=206313

Try disabling the IOMMU else (`intel_iommu=off`)

**Comment by Anachron** [comment] 2021-01-05 10:47
Also you might check if there is a firmware upgrade for your setup.

**Comment by ericonr** [comment] 2021-01-21 17:28
@ayoubkafi ping?

**Comment by ayoubkafi** [comment] 2021-01-22 09:03
> ?

What do you mean by ping

**Comment by Anachron** [comment] 2021-01-22 09:19
It means he asks you if you have any new progress here.

**Comment by ayoubkafi** [comment] 2021-01-28 17:48
> @ayoubkafi ping?

No progress I reinstalled for the millionth time
Things are fine for a few minutes, up to an hour, and then suddenly the system freezes, I can't move the mouse, and if the audio clip is working it keeps repeating itself over and over again.
Any way to debug ?

**Comment by ericonr** [comment] 2021-01-28 19:04
How much memory do you have? You could be running out of it and using a lot of swap. Do you have swap enabled?

Try pressing `sysrq+alt+f` when this happens, it will try to kill the application using the most memory.

**Comment by ayoubkafi** [comment] 2021-01-28 20:46
> How much memory do you have? You could be running out of it and using a lot of swap. Do you have swap enabled?
> 
> Try pressing `sysrq+alt+f` when this happens, it will try to kill the application using the most memory.

This is not related to memory
I have 4GB memory and 8GB swap, when I was using Void Linux it did not exceed 50%.
I have archlinux installed alongside voidlinux and i don't have any problem with archlinux

**Comment by ericonr** [comment] 2021-01-28 21:28
In that case I'd check what `htop` (or some similar program) shows about currently running processes... Does it lock up even if you don't launch a graphical session? You could try ssh'ing into it when it locks up and seeing if dmesg says anything.

Maybe some process is dying and not being properly reaped.

**Comment by mvf** [comment] 2021-01-29 14:35
Booting with `intel_iommu=off` like Leah suggested will fix this since it disables the panicking code path. See the [GRUB section of the docs](https://docs.voidlinux.org/config/kernel.html#grub) on how to do this. To test it first without changing your system, you can select the kernel in GRUB, press <kbd>E</kbd>, append `intel_iommu=off` to the command line and press <kbd>F10</kbd> to boot.

There's still a Void bug here. `CONFIG_INTEL_IOMMU_DEFAULT_ON=y` is not suitable for a distro kernel.

**Comment by ericonr** [comment] 2021-01-29 14:52
This was brought up in #21767, and in IRC determined to be WONTFIX. I don't remember the exact issue.

**Comment by ahesford** [comment] 2021-01-29 14:57
Try `intel_iommu=igfx_off` instead. https://www.kernel.org/doc/html/latest/x86/intel-iommu.html#graphics-problems

**Comment by ayoubkafi** [comment] 2021-01-29 17:30
I have installed intel-ucode, then I used the computer for a long time about 7 hours and the problem did not occur but I am not sure if it resolved or not

**Comment by Anachron** [comment] 2021-01-29 17:46
> Also you might check if there is a firmware upgrade for your setup.

Please revisit my suggestion from the 5th of January.

**Comment by ayoubkafi** [comment] 2021-01-29 17:58
> > Also you might check if there is a firmware upgrade for your setup.
> 
> Please revisit my suggestion from the 5th of January.
I have previously said that I installed VoidLinux alongside ArchLinux and I don't have any problems with ArchLinux

**Comment by ayoubkafi** [comment] 2021-02-04 12:48
The problem returned

**Comment by Anachron** [comment] 2021-02-04 13:07
You know it's not really helpful for anybody if you give us a short message that something still doesn't work. 
Tell us what you tried from the above suggestions and what changed. Also maybe post some kernel logs and alike.

**Comment by travankor** [comment] 2021-02-04 13:11
I agree there's nothing actionable here and you haven't done any of the recommended suggestions yet.

**Comment by Anachron** [comment] 2021-02-17 10:50
Should we close this?

**Comment by ahesford** [comment] 2021-02-17 15:35
@ayoubkafi If you can find a way to reliably recreate this issue, rule out the suggestions in here and have high confidence that the issue is caused by a Void configuration or packaging issue, please feel free to open a follow-up issu with more documentation.

**Closed by ahesford** 2021-02-17 15:35 UTC
Labels: question

**Comment by ayoubkafi** [comment] 2021-03-24 12:22
i have replaced the old kernel argument with `rw loglevel=3 intel_iommu=igfx_off` then  the problem solved
