### ISSUE TITLE
Graphical Corruption on Chromium Apps with Mesa 19.0.5

### ISSUE THREAD

**Issue by HadetTheUndying** [void-linux/void-packages#11907] opened 2019-05-23 20:16 UTC
### System

* xuname: Void 4.19.45_1 x86_64 AuthenticAMD uptodate rrrmFFFFFF

* package: 
[*] libGL-19.0.5_1          Graphics library similar to SGI's OpenGL
[*] libGL-32bit-19.0.5_1    Graphics library similar to SGI's OpenGL (32bit)
[*] libGLES-19.0.5_1        Free implementation of the OpenGL|ES 1.x and 2.x API
[*] libGLES-32bit-19.0.5_1  Free implementation of the OpenGL|ES 1.x and 2.x API (32bit)
[*] libglapi-19.0.5_1       Free implementation of the GL API - shared library
[*] libglapi-32bit-19.0.5_1 Free implementation of the GL API - shared library (32bit)
[*] libOSMesa-32bit-19.0.5_1    Mesa Off-Screen interface library (32bit)
[*] libgbm-19.0.5_1             Mesa Generic buffer management API - runtime
[*] libtxc_dxtn-32bit-1.0.1_2   S3 Texture Compression (S3TC) library for Mesa (32bit)
[*] libxatracker-19.0.5_1       Mesa XA tracker interface library
[*] mesa-ati-dri-19.0.5_1       Mesa DRI drivers for ATI GPUs
[*] mesa-ati-dri-32bit-19.0.5_1 Mesa DRI drivers for ATI GPUs (32bit)
[*] mesa-intel-dri-19.0.5_1     Mesa DRI drivers for Intel GPUs
[*] mesa-nouveau-dri-19.0.5_1   Mesa DRI drivers for NVIDIA GPUs (nouveau dri)
[*] mesa-opencl-19.0.5_1        Mesa implementation of OpenCL (r600+ only)
[*] mesa-vmwgfx-dri-19.0.5_1    Mesa DRI drivers for VMware
  *affected package(s) including the version*

### Expected behavior
Proper Rendering in videos and some web Content
### Actual behavior
Weird Graphical corruption with Certain content and Videos, maybe related to hardware acceleration.
https://i.imgur.com/ueM5iOY.png

### Steps to reproduce the behavior
Happens to me with the latest Mesa on most Chromium apps with an RX Vega 56

**Comment by MungFuSensei** [comment] 2019-05-23 20:36
Hmmm. That's interesting, since I've been using mesa-git through xbps-src, and I have very similar issues with qutebrowser (which I believe shares an engine with chromium?).

For me, if I start qutebrowser, it crashes my gpu entirely, then it comes back, and my entire screen is pixelated like that. In other browsers, gfys and other such video formats will appear pixelated like this, and crash the browser if I pause or close the video. It's ok for most YouTube videos, though. 

I just assumed it was on me for rolling the dice with mesa-git, but seeing as it's popping up in the stable version...

Oh, I'm also using a vega card as well, so there could be something there.

If anyone could point me towards what logs I should be digging up, I'd be grateful.

**Comment by HadetTheUndying** [comment] 2019-05-23 20:39
I'm not having the GPU Crash issue, and people on other Distros are reporting the issue with RX Vega cards as well with 19.0.5 so i don't think this is a void related issue after all.

You might wanna do some testing like run a long benchmark or something because that sounds like it might be a hardware fault. We might just need to wait for 19.0.6 and hope the issue gets fixed.

**Comment by MungFuSensei** [comment] 2019-05-23 20:42
It works perfectly fine with games, it's really just happening with chromium based browsers and some video formats. Didn't have any similar behavior before updating.

**Comment by HadetTheUndying** [comment] 2019-05-23 21:09
Can confirm that the issue is not present in Mesa/libGL 19.0.4, the bug was introduced in 19.0.5

**Comment by arifur** [comment] 2019-05-24 09:25
I am having the same issues.

**Comment by dennis1248** [comment] 2019-05-24 11:57
A temporary work around is to disable hardware acceleration in the browser settings. 

I am also affected by this issue since 19.0.5. I run a Vega 64.

**Comment by arifur** [comment] 2019-05-24 17:00
`--disable-gpu` tested on code-oss and it works but did not work on chromium for me

**Comment by HadetTheUndying** [comment] 2019-05-24 22:46
This is a Mesa issue not void issue, verrified on three different distros.

**Comment by paualberto** [comment] 2019-05-27 15:07
Had this issue, couldn't disable HW acceleration because I need it.
Had to downgrade mesa and GL libraries
```
xdowngrade libglapi-19.0.4_1.x86_64.xbps libEGL-19.0.4_1.x86_64.xbps libGL-19.0.4_1.x86_64.xbps libGLES-19.0.4_1.x86_64.xbps mesa-intel-dri-19.0.4_1.x86_64.xbps mesa-nouveau-dri-19.0.4_1.x86_64.xbps mesa-vmwgfx-dri-19.0.4_1.x86_64.xbpsps mesa-ati-dri-19.0.4_1.x86_64.xbps libgbm-19.0.4_1.x86_64.xbps
```

Now it doesn't occur, waiting for next update.

**Comment by silvernode** [comment] 2019-05-28 16:03
I can confirm this issue is present with the AMD RX 580.

**Comment by silvernode** [comment] 2019-05-30 15:30
Fixed in Fedora 30 as of the last couple of days. I tried to find the source and commits but can't seem to locate it. If anyone can find the recent changes that were made in revision 2 of these packages for Fedora, the solution should be there.

**Comment by makmm** [comment] 2019-05-30 22:15
Can confirm, it was unusable for me (everything was glitchy.) Had to use it anyway to test something xP

**Comment by simonvanderveldt** [comment] 2019-06-01 12:10
I'm seeing the same issue on gentoo, 19.0.4 works fine.
Seems like it's this bug https://bugs.freedesktop.org/show_bug.cgi?id=110721

**Comment by silvernode** [comment] 2019-06-01 18:56
So I guess we need a revision to Mesa in void that does a patch and removes
commit 811fa9a79cf as mentioned in the free desktop bug report.  (Or wait
for upstream). I suggest just downgrading until a solution comes from
upstream but here is what was said:

> There are 2 problematic commits, making the bisect a bit more complicated.


The first one has already been solved by d6053bf2a170.
The second one is 811fa9a79cf ("mesa: unreference current winsys
buffers when unbinding winsys buffers").

Using master + this commit reverted: no more corruption in chromium.

**Comment by HadetTheUndying** [comment] 2019-06-01 19:20
Honestly I would assume now that the issue has been corrected we'll see a patch in stable soon.

**Comment by silvernode** [comment] 2019-06-01 22:00
Yeah that's why suggest downgrading until further notice.

**Comment by Syndicate6690** [comment] 2019-06-02 00:23
I just installed Void Linux two hours ago, had this same exact issue on my machine. I'm using a AMD Polaris RX 470 graphics card. I slowly but surely narrowed my issue down to the mesa-ati-dri package.

Cannot downgrade due to not having the packages, what's the best fix here?

**Comment by MungFuSensei** [comment] 2019-06-02 00:26
@Syndicate6690 You can use xbps-src, and edit the template for mesa-ati-dri. Check the void wiki for details.

**Comment by Syndicate6690** [comment] 2019-06-02 00:29
I really think Void should roll this package back asap... Fedora has patched this already somehow, someone should make a pull request.

**Comment by HadetTheUndying** [comment] 2019-06-02 04:11
> I really think Void should roll this package back asap... Fedora has patched this already somehow, someone should make a pull request.

The problem is that no one is sure if after bisecting and removing these two commits if new bugs were introduced yet. You can manually rebuild 19.0.4 if you do not have it in your cache, which is my suggestion,.

**Comment by Syndicate6690** [comment] 2019-06-02 15:32
mesa-dri-drivers-19.0.5-2.fc30.i686.rpm | Mesa-based DRI drivers

All I'm saying is they somehow fixed the issue with a second revision to their package.

**Comment by HadetTheUndying** [comment] 2019-06-02 20:55
> mesa-dri-drivers-19.0.5-2.fc30.i686.rpm | Mesa-based DRI drivers
> 
> All I'm saying is they somehow fixed the issue with a second revision to their package.

I've been following the bugtrucker on freedesktop.org. They solved the issues by removing 2 commits from the upstream. However no one is aware if this introduced new bugs or not, and I currently have not tested it on Void

Here is the commit if someone would like to test it on Void:
https://src.fedoraproject.org/rpms/mesa/c/3ea3041de61441948dc170c2f9425293fb627c7a?branch=f30

My suggestion is to wait for an official patch in the upstream, or as I said before, build to downgrade 19.0.4, if you are unsure how to do this and have tried already I can personally archive the required packages for you but I will not distribute them here, and it would be a use at your own risk situation.

**Comment by HadetTheUndying** [comment] 2019-06-03 00:21
It Appears there is now a fix, not idea when it's coming in stable
https://bugs.freedesktop.org/show_bug.cgi?id=110721

**Comment by Syndicate6690** [comment] 2019-06-03 01:36
I know about the bug and the commits and stuff, but this should be pushed to stable asap. I've built it and tested it, it does work. This is the same patch the Fedora people are shipping.

**Comment by HadetTheUndying** [comment] 2019-06-03 01:42
> I know about the bug and the commits and stuff, but this should be pushed to stable asap. I've built it and tested it, it does work. This is the same patch the Fedora people are shipping.

You're misunderstanding the situation. Fedora is using their own patch of 19.0.5  the mesa project maintainers have made no such patches to 19.0.5, it is unclear whether Fedora's packages introduced new bugs which would remove us from the baseline support tree. It is better to wait for an official commit to the stable mesa branch.

**Comment by Syndicate6690** [comment] 2019-06-03 01:44
Ok well true, I see what you're saying about sticking to upstream code. What I don't understand is why Void is even shipping Mesa 19.0.5 in the first place if it has a known issue with AMD graphics & Chromium. I think it should be rolled back if it cannot be fixed in a way that makes sense.

**Comment by silvernode** [comment] 2019-06-04 09:05
> Ok well true, I see what you're saying about sticking to upstream code. What I don't understand is why Void is even shipping Mesa 19.0.5 in the first place if it has a known issue with AMD graphics & Chromium. I think it should be rolled back if it cannot be fixed in a way that makes sense.

I totally agree, who knows when upstream will commit the fix to stable and these graphical glitches render the system unusable for multiple users (myself included). I haven't used Void since the issue started happening and don't plan to until a solution is applied. In the meantime I am using Fedora which already has the fix. No visible bugs that I can see so far but that's beside the point. Packages have been rolled back in the past for lesser issues so I don't see why this hasn't happened yet for mesa. This bug really sucks!

**Comment by xtraeme** [comment] 2019-06-04 09:11
How hard is to revert the changes and build the packages locally? git and xbps-src are our friends.

Three simple commands and you can get back to 19.0.4 or revert the affected changes. Not sure why people complain about this.

If you really care that much then go to the mesa bugtracker and complain there.

**Comment by silvernode** [comment] 2019-06-04 11:30
Fair enough, hi Juan!

**Comment by Syndicate6690** [comment] 2019-06-04 22:10
I do kind of agree with the idea that if it's broken and you can fix it with xbps-src and git you should do that yourself. But, as a new user just switching to Void, this is a real turn-off. Most people who have this issue just blame the distribution and switch away. Not everyone has the time to narrow it down to mesa's ATI driver (radeonsi), find the package and go compile a old version. People use their systems in their daily lives, and yes you could argue that issues happen and if you care about stability maybe rolling distros aren't for you, but when there is an issue, why not roll it back for everyone and fix it?

**Comment by MungFuSensei** [comment] 2019-06-04 23:02
Has anyone tested 19.1 to see if the issue disappears? 19.1 release is next week, so it might not even be worth worrying about it.

**Closed** 2019-06-06 11:06 UTC
Labels: bug
