### ISSUE TITLE
Please update Qt version (to 5.11.1) as Plasma (latest - 5.13.4) looks weird without...

### ISSUE THREAD

**Issue by MirceaMx** [void-linux/void-packages#1660] opened 2018-08-11 13:02 UTC
### System
Void Linux - All intel (Gpu-Cpu) - KDE Plasma version 5.13.4

### Expected behavior
I expected KDE Plasma to look normal out of the box given that it's the latest version. However, given the rather old qt version (5.10.1) some **menu items look strange**. Also the text is, well light grey text on white background makes it **very difficult to read**. Also Mesa version seems out of date (using Intel GPU).

**Comment by Johnnynator** [comment] 2018-08-11 16:45
Can you provide some more information e.g. used theme and font since I tested it before it got merged and it did look normal on my machines (Intel iGPU glibc and musl).

**Comment by MirceaMx** [comment] 2018-08-11 18:45
Thanks for the response. Theme does not seem to matter, I tried different
themes, icon themes, even widget styles and all the same. Am using
breeze-dark now. All the menu with checkboxes have "problems" and should
not look like that. Also see what I marked in one of the screenshots. I
know how plasma should look btw.

[image: image.png]
[image: image.png]



[image: image.png]

**Comment by Johnnynator** [comment] 2018-08-11 18:54
> [image: image.png] [image: image.png] [image: image.png]
Does seem like sending images in a mail doesn't work for github. I can't see them.

**Comment by MirceaMx** [comment] 2018-08-11 19:00
Just a sec...will try something else...

On August 11, 2018 9:54:57 PM GMT+03:00, John Zimmermann <notifications@github.com> wrote:
>> [image: image.png] [image: image.png] [image: image.png]
>Does seem like sending images in a mail doesn't work for github. I
>can't see them.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/void-linux/void-packages/issues/1660#issuecomment-412294819

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MirceaMx** [comment] 2018-08-11 19:14
Uploaded here:
https://expirebox.com/download/72a452b5587cf85d044c2d047f12dc65.html

**Comment by Johnnynator** [comment] 2018-08-11 19:31
Ok. I agree that is totally not how it should look like.
Did you already use KDE before that update? That broken design looks similiar as qt5ct did break KDE on Gentoo for me once.
If this is a new install check you enviroment varaibles for some anomalies like a set `QT_QPA_PLATFORMTHEME`. Otherwise I will check tomottow if I can reproduce it on a minimal install on a differetn machine, but  I doubt it is related to our QT version.

**Comment by MirceaMx** [comment] 2018-08-11 19:40
Yes I used Kde with Arch (5.13, 5.13.1....5.13.4) then I switched to Void cause it seems a lot faster and more stable. Did a fresh install of Kde Plasma since I noticed it had 5.13.4 the latest. Will check.  Thank you. 

On August 11, 2018 10:31:03 PM GMT+03:00, John Zimmermann <notifications@github.com> wrote:
>Ok. I agree that is totally not how it should look like.
>Did you already use KDE before that update? That broken design looks
>similiar as qt5ct did break KDE on Gentoo for me once.
>If this is a new install check you enviroment varaibles for some
>anomalies like a set `QT_QPA_PLATFORMTHEME`. Otherwise I will check
>tomottow if I can reproduce it on a minimal install on a differetn
>machine, but  I doubt it is related to our QT version.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/void-linux/void-packages/issues/1660#issuecomment-412296815

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Johnnynator** [comment] 2018-08-11 19:54
I did meant wether you used KDE on void before to make sure if it is a regression or just some behaviour that was always there.

**Comment by MirceaMx** [comment] 2018-08-11 20:47
Yes, I did try KDE on Void when it was "just" version 5.12 and I had no
issues with it. I moved 'cause of the rather small number of available
packages. In the meantime Void seems to have matured (more) and has more
packages. It has issues, for example no calendar events plugin (using
alternative - Events Calendar from KDE Store and synchronizing with Google
for events) then I tried to install Opera browser either through XBPS
(package not available bla bla) or manually (missing dependency). Then
PPSSPP is available but there is also PPSSPP-Qt that is not available...

**Comment by MirceaMx** [comment] 2018-08-11 20:54
*All my environment variables:*

COLORFGBG=15;0
COLORTERM=truecolor
DESKTOP_SESSION=/usr/share/xsessions/plasma
DISPLAY=:0
GNOME_KEYRING_CONTROL=/home/mircea/.cache/keyring-8KFFNZ
GS_LIB=/home/mircea/.fonts
GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/mircea/.gtkrc-2.0:/home/mircea/.config/gtkrc-2.0
GTK_RC_FILES=/etc/gtk/gtkrc:/home/mircea/.gtkrc:/home/mircea/.config/gtkrc
HOME=/home/mircea
KDE_FULL_SESSION=true
KDE_SESSION_UID=1000
KDE_SESSION_VERSION=5
KONSOLE_DBUS_SERVICE=:1.33
KONSOLE_DBUS_SESSION=/Sessions/1
KONSOLE_DBUS_WINDOW=/Windows/1
KONSOLE_PROFILE_NAME=Profile 2
LANG=en_US.UTF-8
LANGUAGE=
LC_COLLATE=C
LOGNAME=mircea
LS_COLORS=
MAIL=/var/spool/mail/mircea
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
PAM_KWALLET5_LOGIN=/tmp/kwallet5_mircea.socket
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
PROFILEHOME=
PWD=/home/mircea
QT_AUTO_SCREEN_SCALE_FACTOR=0
SESSION_MANAGER=local/voidlinux:@
/tmp/.ICE-unix/1828,unix/voidlinux:/tmp/.ICE-unix/1828
SHELL=/usr/bin/fish
SHELL_SESSION_ID=fdb19419d8574380b476180d0b921b77
SHLVL=2
TERM=xterm-256color
USER=mircea
WINDOWID=73400326
XAUTHORITY=/tmp/xauth-1000-_0
XCURSOR_SIZE=0
XCURSOR_THEME=Breeze_Obsidian
XDG_CURRENT_DESKTOP=KDE
XDG_DATA_DIRS=/usr/share:/usr/share:/usr/local/share
XDG_SEAT=seat0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=KDE
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
XDG_SESSION_TYPE=x11
XDG_VTNR=7

**Comment by pullmoll** [comment] 2018-08-11 21:00
There were problems building qt5-5.11.1 with gcc-7.3.0, but I don't recall exactly which (was it about full C++14 support?), so we probably need to delay this until after gcc is updated to 8.2.0.

And saying that qt5-5.10.1 is rather old is not really true. OTOH let's hope 5.11.x does not have some changes which will cause trouble with other packages depending on qt5.

**Comment by MirceaMx** [comment] 2018-08-11 21:05
I hope so to but I don't think Qt 5.11.1 will break anything. I am not one
of those that thinks what is new is best...sometimes what is old(-er) works
best but in this case Qt 5.11.1 seems like a very good update and makes
everything faster, more stable and Plasma related, better looking.

**Comment by travankor** [comment] 2018-08-11 22:14
@pullmoll I think you said that qt 5.11.X is not compatible with the current libressl? AFAIK, I don't see patches around yet for libressl.

BTW gcc 7.3 already has full C++14 support (unless there is some regression).

**Comment by pullmoll** [comment] 2018-08-11 22:48
Ah, yes, that was the problem. Thanks @travankor I mixed this with may paid job experience that MSVC2015 is not sufficient to build Qt5-5.11.1 because its C++14 is support is not sufficient.

So unless someone is going to (re-)write SSL support for qt5-5.11.x we cannot upgrade.

**Comment by MirceaMx** [comment] 2018-08-12 01:35
Just (re)installed kde Plasma again, fresh, on a different partition. Looks the same...oh, well...

**Comment by pullmoll** [comment] 2018-08-12 12:58
Well, it looks as if we can't solve this problem in the near future. The only option would be to build qt5-5.11.1 with openssl, which we don't want to do because Void uses libressl.

**Closed** 2018-08-12 16:02 UTC
