### ISSUE TITLE
Snapper complains about locale and fails upon dbus fatal exception

### ISSUE THREAD

**Issue by Mek101** [void-linux/void-packages#27047] opened 2020-12-09 14:27 UTC
### System

* xuname:  
  `Void 5.9.13_1 x86_64-musl AuthenticAMD uptodate rFFFF`

* package:  
  `snapper-0.8.14_1`

### Expected behavior
After enabling and ensuring that `snapperd` is running, `snapper` should run without errors.

### Actual behavior
Snapper complains about the locale, an issue that has already been reported 2 years ago but ignored #5212.

But most importantly, attempting to run snapper results in a fatal exception, which makes the program unusable.

Running `snapper`:
```
[mek101@home-server ~]$ snapper -c public_storage create-config /mountpoints/public_storage/
Failed to set locale. Fix your system.
Failure (dbus fatal exception)
[mek101@home-server ~]$
```

Running `snapperd`:
```
[mek101@home-server ~]$ snapperd
terminate called after throwing an instance of 'DBus::FatalException'
  what():  dbus fatal exception
Aborted
[mek101@home-server ~]$ 
```

### Steps to reproduce the behavior
Install the `snapper` package and run any command

**Comment by ericonr** [comment] 2020-12-09 14:48
Do you have the `dbus` system service running?

**Comment by Mek101** [comment] 2020-12-09 14:51
I installed the `dbus` package and enabled the service. Now `snapper` appears to work.
Perhaps it shoulld be added in the dependencies of `snapper` (plus a post-installation message to remember to start `dbus`?)

**Comment by ericonr** [comment] 2020-12-09 14:59
Making `snapper` depend on `dbus` sounds reasonable to me. Could you open a PR for it?

Having documentation in the install message is a bit complicated, though. Few people read them, and accessing them isn't something most people remember how to do, so if they miss it during installation they are unlikely to ever read them.

Void doesn't have dbus enabled by default and leaves that as something the user can choose to enable or not. Therefore, it's expected that a fatal error about dbus would prompt the user to try and enable the service. Information about dbus is covered in https://docs.voidlinux.org/config/session-management.html

**Comment by Mek101** [comment] 2020-12-09 15:06
Correction: the command above (`snapper -c public_storage create-config /mountpoints/public_storage/`) still reports an error
```
[root@home-server mek101]# snapper -v -c public_storage create-config /mountpoints/public_storage/\@data/
Failed to set locale. Fix your system.
Failure (error.something).
[root@home-server mek101]#
```
Although the effects as listed on the [arch wiki](https://wiki.archlinux.org/index.php/Snapper#Create_a_new_configuration) seem to have worked fine.

**Comment by Mek101** [comment] 2020-12-09 15:08
> Making `snapper` depend on `dbus` sounds reasonable to me. Could you open a PR for it?

I need to check what to do first, but ok.

> Having documentation in the install message is a bit complicated, though. Few people read them, and accessing them isn't something most people remember how to do, so if they miss it during installation they are unlikely to ever read them.

I was more thinking on something simple like "Snapper requires a running dbus session to work!"

**Comment by ericonr** [comment] 2020-12-09 15:31
The issue is more that nearly no one reads post install messages :/

That said, I'm not super strongly opposed to adding the warning to the package. You'd have to add an `INSTALL.msg` file and put a message like "Snapper requires the dbus service to work."

**Comment by loreb** [comment] 2020-12-09 16:24
Isn't it just the service, snapperd, that requires dbus? The program, snapper, has a --no-dbus that iirc some distros used
to manage snapshots from cron.{hourly,daily,weekly,monthly}, so **IF** memory serves me /etc/sv/snapper/run should check that dbus is running.

**Comment by Mek101** [comment] 2020-12-09 16:48
There's no such check in the snapperd service
```
[root@home-server mek101]# cat /etc/sv/snapperd/run 
#!/bin/sh
exec snapperd
[root@home-server mek101]#
```

**Comment by loreb** [comment] 2020-12-09 16:54
LOL yeah, I meant like "if I remember correctly (about --no-dbus), the fix should go in /etc/sv/snapperd/run".
That being said, I checked the most likely candidate (artix) and it appears I misremembered:
they do run snapper from cron, but not without dbus.

**Comment by ericonr** [comment] 2020-12-09 17:36
```
[root@home-server mek101]# cat /etc/sv/snapperd/run 
#!/bin/sh
exec snapperd
```

Tbh, that check is necessary only if the program tries to launch its own dbus or something. If it fails at launch, that's all we really need.

**Comment by ericonr** [comment] 2020-12-10 13:36
I'm closing this issue for now.

If any of you come up with a better solution, please make a PR or open a new issue for discussion. We could also improve the void-docs page, though I'm not sure what that'd look like.

**Closed** 2020-12-10 13:36 UTC
