### ISSUE TITLE
users running unprivileged lxc container no worky no more.

### ISSUE THREAD

**Issue by egrain** [void-linux/void-packages#38682] opened 2022-08-15 09:06 UTC
### Is this a new report?

Yes

### System Info

5.18.17_1 #1 SMP PREEMPT_DYNAMIC Fri Aug 12 13:53:18 UTC 2022 x86_64 GNU/Linux musl.

### Package(s) Affected

lxc-5.0.1_1

### Expected behaviour

It working like it did before the update. All I did was XBoxPlayStation-install -Su and init 6. 

### Actual behaviour

lxc-start: alpina: ../src/lxc/network.c: lxc_create_network_unpriv_exec: 2990 lxc-user-nic failed to configure requested network: ../src/lxc/cmd/lxc_user_nic.c: 802: create_db_dir - Permission denied - Failed to create /run/lxc

../src/lxc/cmd/lxc_user_nic.c: 1125: main: Failed to create directory for db file
lxc-start: alpina: ../src/lxc/start.c: lxc_spawn: 1840 Failed to create the network
lxc-start: alpina: ../src/lxc/start.c: __lxc_start: 2107 Failed to spawn container "alpina"
lxc-start: alpina: ../src/lxc/tools/lxc_start.c: main: 306 The container failed to start
lxc-start: alpina: ../src/lxc/tools/lxc_start.c: main: 311 Additional information can be obtained by setting the --logfile and --logpriority options

and if i mkdir /run/lxc, chown lxcuser /run/lxc i get this:

lxc-start: alpina: ../src/lxc/network.c: lxc_create_network_unpriv_exec: 2990 lxc-user-nic failed to configure requested network: ../src/lxc/cmd/lxc_user_nic.c: 474: instantiate_veth - Operation not permitted - Failed to create veth1003_cv7j-veth1003_cv7jp

../src/lxc/cmd/lxc_user_nic.c: 529: create_nic: Error creating veth tunnel
../src/lxc/cmd/lxc_user_nic.c: 720: get_nic_if_avail: Failed to create new nic
../src/lxc/cmd/lxc_user_nic.c: 1206: main: Quota reached
lxc-start: alpina: ../src/lxc/start.c: lxc_spawn: 1840 Failed to create the network
lxc-start: alpina: ../src/lxc/start.c: __lxc_start: 2107 Failed to spawn container "alpina"
lxc-start: alpina: ../src/lxc/tools/lxc_start.c: main: 306 The container failed to start
lxc-start: alpina: ../src/lxc/tools/lxc_start.c: main: 311 Additional information can be obtained by setting the --logfile and --logpriority options

### Steps to reproduce

Have a working lxc user + container.
Update the system.
Reboot.
Try and start it with: lxc-start -n nameofyourcontainer -F

Thanks for reading.

**Comment by CameronNemo** [comment] 2022-08-16 19:25
> ../src/lxc/cmd/lxc_user_nic.c: 720: get_nic_if_avail: Failed to create new nic
> ../src/lxc/cmd/lxc_user_nic.c: 1206: main: Quota reached

From the [lxc-user-nic manpage](https://man.voidlinux.org/lxc-user-nic):

```
lxc-user-nic is a setuid-root program with which unprivileged users may
manage network interfaces for use by a lxc container.

It will consult the configuration file /etc/lxc/lxc-usernet to
determine the number of interfaces which the calling user is allowed to
create, and which bridge they may attach them to.
```

What is the contents of that file? See also [lxc-usernet(5)](https://man.voidlinux.org/lxc-usernet).

**Comment by egrain** [comment] 2022-08-16 19:35
As I said I haven't changed anything. The file is the same it was before the system upgrade:
lexie veth skib 1

Also I think that doesn't touch the first issue with the /run/lxc permissions. But of course I prefer to solve things my own self, so i turned it up to 11 (50 actually) before I asked in the void channel, but still no cigar.

Also since I'm guessing you'll ask for this next:
9: skib: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 56:d4:0f:45:0e:f1 brd ff:ff:ff:ff:ff:ff
    inet 10.0.3.1/30 scope global skib
       valid_lft forever preferred_lft forever
    inet6 fe80::54d4:fff:fe45:ef1/64 scope link 
       valid_lft forever preferred_lft forever

but i have a script for creating it and i didn't change that either. I upgraded and rebooted the box quite a few times and it always worked. I really don't think I did anything wrong, ... otherwise I wouldn't have reported it obviously.

**Comment by CameronNemo** [comment] 2022-08-16 20:15
Maybe this will fix it:

   chmod +s /usr/libexec/lxc/lxc-user-nic

**Comment by egrain** [comment] 2022-08-16 20:27
That works, but that can't be right. Root created the file so I would be running it as root. I don't think that's a good idea.

**Comment by CameronNemo** [comment] 2022-08-16 20:31
@egrain that is exactly how networking works for unprivileged LXC containers. Re-read my first comment / read the manpage.

**Comment by egrain** [comment] 2022-08-16 20:35
Why did it change the permission though? I for sure didn't.

**Comment by CameronNemo** [comment] 2022-08-16 20:38
Upstream migrated from autotools to meson. Autotools was setting the bit before, now meson does not set it as setuid so we have to set it manually. That is my best guess. Sorry I broke your use case, hopefully the fix gets merged soon.

**Comment by egrain** [comment] 2022-08-16 20:39
No need to apologize. Learned something in the process. All good. Keep up the good work and all that.

**Comment by eli-schwartz** [comment] 2022-08-17 00:44
> Upstream migrated from autotools to meson. Autotools was setting the bit before, now meson does not set it as setuid so we have to set it manually. That is my best guess.

That's interesting because it's actually set in Meson's permissions:
https://github.com/lxc/lxc/blob/1df8895204244384c468a809f2da5cae2bc44c57/src/lxc/cmd/meson.build#L99

**Comment by eli-schwartz** [comment] 2022-08-17 02:56
I discovered the issue, and it's a Meson bug.

**Comment by eli-schwartz** [comment] 2022-08-17 03:01
Note the issue is kind of fun, because Void installs stuff as non-root, but mapped to root via userns, so the kernel doesn't give out its "you are root, so you're exempt from setuid wiping" thing.

And Meson's own testsuite didn't catch that, because our test for the setuid functionality working, didn't include a binary with a build rpath to be deleted.

**Comment by egrain** [comment] 2022-08-17 08:29
Well if it's a fun issue who am I to complain?

**Closed as completed** 2022-08-17 14:31 UTC
Labels: bug, needs-testing
