### ISSUE TITLE
today's update breaks fonts in texlive

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#28051] opened 2021-01-20 09:02 UTC
```
$ xuname
Void 5.10.8_1 x86_64-musl GenuineIntel uptodate hold rrnDFFF
```
Since today's update, this fails for me
```
\documentclass{article}
\usepackage{amsmath,amssymb}

\begin{document}
$\mathfrak k$
\end{document}
```
with
```
$ pdflatex test
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/VoidLinux) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2020-10-01> patch level 2
L3 programming layer <2020-12-03> xparse <2020-03-03>
(/usr/share/texmf-dist/tex/latex/base/article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
(/usr/share/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/share/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/share/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/share/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/share/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/share/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/share/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/share/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def) (./test.aux)
(/usr/share/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/share/texmf-dist/tex/latex/amsfonts/umsb.fd)
(/usr/share/texmf-dist/tex/latex/amsfonts/ueuf.fd) [1

pdfTeX warning: pdflatex (file pdftex.map): cannot open font map file
] (./test.aux) ) </usr/share/texmf-dist/fonts/pk/ljfour/public/cm/dpi600/cmr10.
pk>
kpathsea: Running mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 eufm10
gsftopk: fatal: map file `psfonts.map' not found.
mktexpk: don't know how to create bitmap font for eufm10.
mktexpk: perhaps eufm10 is missing from the map file.
kpathsea: Appending font creation commands to missfont.log.

!pdfTeX error: pdflatex (file eufm10): Font eufm10 at 600 not found
 ==> Fatal error occurred, no output PDF file produced!
```

**Comment by ericonr** [comment] 2021-01-20 13:13
@fosslinux @Chocimier

**Comment by ifreund** [comment] 2021-01-20 18:00
I get the following trying to output beamer slides from pandoc after the update:
```
pandoc --from markdown+task_lists -t beamer \
        -V theme=metropolis \
        -o slides.pdf slides.md
Error producing PDF.
! pdfTeX error (font expansion): auto expansion is only possible with scalable 
fonts.
<argument> ...shipout:D \box_use:N \l_shipout_box 
                                                  
l.206 \end{frame}
```
This worked before the update with no changes.

**Comment by ahesford** [comment] 2021-01-20 18:01
I see the same issue as @dkwo when compiling well-formed LaTeX documents.

**Comment by ahesford** [comment] 2021-01-20 18:27
During the upgrade, the following error was printed for each `texlive-*` package that was configured:
```
fmtutil [ERROR]: running `aleph -ini   -jobname=lamed -progname=lamed *lambda.ini </dev/null' return status: 1
```
Downgrading `texlive-core` to `2020.55416_2` (and the `texlive-most` meta) instead prints
```
fmtutil [ERROR]: running `pdftex -ini   -jobname=pdflatex-dev -progname=pdflatex-dev -translate-file=cp227.tcx *pdflatex.ini </dev/null' return status: 1
fmtutil [ERROR]: returning error due to option --strict
fmtutil [ERROR]: running `xetex -ini   -jobname=xelatex-dev -progname=xelatex-dev -etex xelatex.ini </dev/null' return status: 1
fmtutil [ERROR]: returning error due to option --strict
fmtutil [ERROR]: running `luahbtex -ini   -jobname=lualatex-dev -progname=lualatex-dev lualatex.ini </dev/null' return status: 1
fmtutil [ERROR]: returning error due to option --strict
fmtutil [ERROR]: running `luatex -ini   -jobname=dvilualatex-dev -progname=dvilualatex-dev dvilualatex.ini </dev/null' return status: 1
fmtutil [ERROR]: returning error due to option --strict
fmtutil [ERROR]: running `pdftex -ini   -jobname=latex-dev -progname=latex-dev -translate-file=cp227.tcx *latex.ini </dev/null' return status: 1
fmtutil [ERROR]: returning error due to option --strict
```
but allows me to compile the aforementioned document again.

**Comment by fosslinux** [comment] 2021-01-20 22:53
Wuh woh... I'll look into it.

**Comment by fosslinux** [comment] 2021-01-20 23:25
This was an error with my testing setup that I overlooked. I will fix the error once gcc10 builds are over.

In the meantime, please run the following commands to fix it, fixed it for me in a clean Void install:

```
sed -i 's:`kpsewhich -var-value=TEXMFROOT`:"/usr/share/texmf-dist":' /usr/sbin/updmap
updmap-sys --syncwithtrees
updmap-sys
```

FWIW, the fix for this is to patch updmap in texlive and to add `updmap` to the trigger... (hooray, even longer times for the trigger :|).

Sorry about that!

**Comment by q66** [comment] 2021-01-21 00:28
confirming that fixes it

**Comment by ahesford** [comment] 2021-01-21 00:47
Seems to work for me as well, but does not eliminate the [fmtutil error that I noted earlier](https://github.com/void-linux/void-packages/issues/28051#issuecomment-763844526).

**Comment by fosslinux** [comment] 2021-01-21 00:49
I have been unable to reproduce that fmtutil error. Can you please provide a list of all installed `texlive-` packages and the output of `aleph -ini   -jobname=lamed -progname=lamed *lambda.ini </dev/null`.

**Comment by ahesford** [comment] 2021-01-21 03:10
I doubt the `aleph` error is related to this issue and I agree that it's harmless, but it is new with these texlive updates.

- Ouput from `fmtutil-sys` run as in the XBPS trigger, but without `--quiet`: [fmtutil-sys.log](https://github.com/void-linux/void-packages/files/5846587/fmtutil-sys.log)
- Output of the failed `aleph` run mentioend in `fmtutil-sys` output: [lamed.log](https://github.com/void-linux/void-packages/files/5846588/lamed.log)
- List of installed TeXLive packages: [tlpkgs.txt](https://github.com/void-linux/void-packages/files/5846589/tlpkgs.txt)

**Comment by ahesford** [comment] 2021-01-21 14:10
Closed in https://github.com/void-linux/void-packages/commit/af51134b0b3d965f0d2ec3fd5689e821212438db

**Closed by ahesford** 2021-01-21 14:10 UTC
Labels: bug

**Comment by Begasus** [comment] 2023-05-30 11:09
> In the meantime, please run the following commands to fix it, fixed it for me in a clean Void install:
> 
> ```
> updmap-sys --syncwithtrees
> updmap-sys
> ```

Thanks, this solved the problem also on Haiku for me 👍
