### ISSUE TITLE
Telegram-desktop broken / failing to start after recent qt6 6.7 update

### ISSUE THREAD

**Issue by gc-user** [void-linux/void-packages#50957] opened 2024-06-24 08:07 UTC
### Is this a new report?

Yes

### System Info

Void 6.6.35_1 x86_64 GenuineIntel uptodate hold rrmDDDDDDFFFFFFFF

### Package(s) Affected

telegram-desktop-5.1.7_1

### Expected behaviour

Telegram-desktop should start.

### Actual behaviour

Telegram-desktop does not start. When started from terminal it gives the following error:

telegram-desktop: symbol lookup error: telegram-desktop: undefined symbol: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate, version Qt_6_PRIVATE_API

### Steps to reproduce

1. Update system to current versions of qt6 (v6.7).
2. Try to start telegram-desktop.
3. Watch telegran-desktop fail to start.
4. Downgrade all those updated qt6 packages to v6.6 and watch telegram-desktop start as expected.

**Comment by DarkCat09** [comment] 2024-06-24 08:08
Duplicate of #50953

**Comment by gc-user** [comment] 2024-06-24 08:10
Ah, ok, I missed that because I was searching for telegram and that one didn't show up. Sorry about that.

**Closed** 2024-06-24 09:34 UTC
Labels: bug, needs-testing
