### ISSUE TITLE
Package request: kwave

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-packages#38027] opened 2022-07-12 16:20 UTC
### Package name

kwave

### Package homepage

https://apps.kde.org/kwave/

### Description

With Kwave you can record, play back, import and edit many sorts of audio files including multi channel files.
Kwave includes some plugins to transform audio files in several ways and presents a graphical view with a complete zoom- and scroll capability.

### Does the requested package meet the quality requirements?

System

### Is the requested package released?

Yes

**Comment by tranzystorek-io** [comment] 2022-07-12 21:16
Duplicate of #37680

**Closed** 2022-07-12 23:57 UTC
Labels: request
