### ISSUE TITLE
font-manager - Segmentation fault on starting up

### ISSUE THREAD

**Issue by nihilismus** [void-linux/void-packages#22923] opened 2020-06-15 15:36 UTC
### System

* xuname:  
  `Void 5.6.18_1 x86_64 GenuineIntel notuptodate rFFFFFF`
* package:  
  `fontmanager-0.7.7_1`

### Expected behavior

`/usr/bin/font-manager` should just work.

### Actual behavior

I'm getting this message in the command line:

```
$ /usr/bin/font-manager
Segmentation fault
```

This issue has already been reported upstream: https://github.com/FontManager/font-manager/issues/119

BTW, `/usr/bin/font-manager --list` executes without any issue.

### Steps to reproduce the behavior

Execute `/usr/bin/font-manager` from the command line.

**Comment by ericonr** [comment] 2020-06-15 15:40
Duplicate of #22699, I think. Thanks for the upstream report, though. Will be useful to track a fix.

**Comment by nihilismus** [comment] 2020-06-15 18:47
Oh, sorry, I didn't searched by an already opened issue.

**Comment by sgn** [comment] 2020-06-16 15:22
Duplicate of #22699

**Closed by sgn** 2020-06-16 15:22 UTC
