### ISSUE TITLE
"depmod: WARNING" after kmod update

### ISSUE THREAD

**Issue by Haagen-Dazs** [void-linux/void-packages#38367] opened 2022-07-30 10:20 UTC
### Is this a new report?

Yes

### System Info

Void 5.18.14_1 x86_64 AuthenticAMD uptodate FFF

### Package(s) Affected

kmod-30_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://groups.google.com/g/linux.debian.bugs.dist/c/7hZiQYDXaiI

### Expected behaviour

No errors given after `sudo xbps-reconfigure -fa`

### Actual behaviour

depmod: WARNING: could not open modules.builtin.modinfo at /var/tmp/dracut.../initramfs/lib/modules/5.18.14_1: No such file or directory

### Steps to reproduce

`sudo xbps-install -Su`
`sudo xbps-reconfigure -fa`

**Comment by Haagen-Dazs** [comment] 2022-07-30 13:36
Latest dracut v.056 seems to have this covered, not tested though:

dracut-init.sh line 1001:

`dracut_kernel_post() {
    for _f in modules.builtin modules.builtin.alias modules.builtin.modinfo modules.order; do
        [[ -e $srcmods/$_f ]] && inst_simple "$srcmods/$_f" "/lib/modules/$kernel/$_f"
    done`

**Comment by Haagen-Dazs** [comment] 2022-08-07 02:13
> This output was generated circa 24 hours ago. Feel free to delete this if it's not relevant anymore

It is still relevant, dracut is still not patched for the kmod update.
[mkinitcpio](https://github.com/void-linux/void-packages/commit/ff39c912d412717d17232de9564f659b037e95b5) is already patched though.

**Comment by Haagen-Dazs** [comment] 2022-08-07 20:51
> Honestly, I hope Void devs could eventually join forces with Alpine/Devuan/Gentoo devs and maintain mkinitcpio together, since dracut is going deeper into systemd hard-requirements.

[Booster](https://github.com/void-linux/void-packages/pull/29434) is also a great alternative written in Go, I personally use it on Arch and so far I did not have any issues with it.

**Comment by ahesford** [comment] 2022-08-08 01:34
1. `mkinitcpio` is an Arch project and works fine with Void as is. I personally use `mkinitcpio` on most of my systems, even as the foundation of my ZFSBootMenu images, and have a vested interest in making sure it stays that way. But there's no need to attempt to take ownership over from Arch.
2. Has anybody shown that this warning actually indicates a problem with the initramfs image? It says "WARNING" right in the text, and even before I pulled the `mkinitcpio` patch from upstream, I confirmed that expected kernel modules made their way into initramfs images.
3. Somebody is welcome to PR a backport of the fix to our current dracut pending a full update. (It won't be me because I no longer have installations that will let me meaningfully test the patch.) Otherwise, as I noted when closing an untested PR to bump the dracut package, a full update requires more extensive testing and will hopefully be done once a core member finds some time and interest to take up the matter. (Documenting that this causes a real problem beyond spitting out some warnings will almost certainly increase the sense of urgency there.)

**Comment by MaMiMa81** [comment] 2022-08-12 13:29
> Latest dracut v.056 seems to have this covered, not tested though:
> 
> dracut-init.sh line 1001:
> 
> `dracut_kernel_post() { for _f in modules.builtin modules.builtin.alias modules.builtin.modinfo modules.order; do [[ -e $srcmods/$_f ]] && inst_simple "$srcmods/$_f" "/lib/modules/$kernel/$_f" done`

Good Afternoon
regarding this issue and taking into account what has been mentioned by @ahesford that a full update of dracut to v.56 will require extensive testing - espescially as it appears that it is moving to be more systemd centric - plus this will also alleviate demand upon core devs, would not a simple & sensible course
of action just be to administer a basic patch to the existing dracut v.53:

        985  - for _f in modules.builtin.bin modules.builtin modules.order; do

        985  + for _f in modules.builtin.bin modules.builtin modules.builtin.modinfo modules.order; do

I wouldn't know how to set this up correctly in a patch & submit it for inclusion as a new 'revision'??? - I could hazard a guess by looking around but that's just what it would be. I am no programmer & this is purely a effort to perhaps solve this in the easiest manner. As, how shall we say a 'lay-person', I shouldn't of thought this wouldn't have too much, if any, ramifications on things - but again quite frankly that is pretty much a guess, the much more knowledgable amongst you here will have more of an idea - I merely but it forward as a suggestion to try and help.
Regards

**Comment by MaMiMa81** [comment] 2022-08-17 17:13
Well after what had been mentioned on this thread above by @Haagen-Dazs, @ahesford  & @TeusLollo  about using `mkinitcpio` I thought I'd have a go at replacing `dracut` with it.
Made `dracut` an ignorepkg, removed it, installed `mkinitcpio`, did `xbps-reconfigure -f linux<X.Y>` rebooted & mess - root partitioned would only mount as ro & then it was loop mounted to `/media/<OS_LABEL>` & I was dumped into the rescue console.
I managed to boot in the system, by repeatedly entering exit & found the other 2 partitions plus swap also mounted the /media/ directory.
Spent best part of a day trying to sort it before restoring from a backup.
So what I have done now,after taking a backup of the file, is manually edit the `/usr/lib/dracut/dracut-init.sh`:
  Replacing line 985
                               `for _f in modules.builtin.bin modules.builtin modules.order; do`
        with
                               `for _f in modules.builtin.bin modules.builtin modules.builtin.modinfo modules.order; do`

I the re-upgraded kmod & libkmod from v.29 to v.30, tested it out with a new install of a kernel & works as normal with no:
                        `depmod: WARNING:`

If I find any issues I'll post here - or if anyone has any comment what I've done - good or bad please do likewise.

**Comment by ahesford** [comment] 2022-08-17 17:29
Somebody is welcome to PR a fix. But, again, has anybody demonstrated that these warnings actually lead to a problem with the initramfs image? Problems with Debians test suite for `initramfs-tools` are of no consequence here.

**Comment by MaMiMa81** [comment] 2022-08-18 15:12
@TeusLollo 
> > I managed to boot in the system, by repeatedly entering exit & found the other 2 partitions plus swap also mounted the /media/ directory.
> 
> Would you care to post more info? The fact that system `fstab` was ignored, and partitions were mounted into `/media/` as RO in loopback, would point towards `mkinitcpio` initializing your system as if it were a Live Image. Maybe you have `void-mklive` installed? Maybe there's some other hook at work? Weird.
> 
> Anyway, I'm inclined to believe your problem with `mkinitcpio` was more of a mis-configuration case.


Well wasn't going to stray to much away from the core issue - the dracut depmod warning - but regarding `mkinitcpio` your conclusion may well be right.


Since I did the `mkinitcpio` install I have seen this post here:

[https://reddit.com/r/voidlinux/comments/ql2les/void_console_font/hj07qmo/#c](url)

Specifically @ahesford :

> If you want to use mkinitcpio, we ship a kernel hook to generate the initramfs on kernel upgrades. Just xbps-reconfigure -f linux<X.Y> after installing mkinitcpio. Also, to /etc/default/initramfs-regenerate add INITRAMFS_GENERATOR=mkinitcpio so packages that otherwise trigger initramfs regeneration do the right thing.

While I did `xbps-reconfigure -f linux<X.Y>` I didn't add `INITRAMFS_GENERATOR=mkinitcpio` to `/etc/default/initramfs-regenerate` firstly the file didn't exist & I thought the file `/usr/libexec/xbps-triggers/initramfs-regenerate` had it covered - but on re-reading the file it states that it uses `dracut` by default so it looks like it is necessary to specify `INITRAMFS_GENERATOR=mkinitcpio` at `/etc/default/initramfs-regenerate`. I assume this should be done before `xbps-reconfigure -f linux<X.Y>` & perhaps `xbps-reconfigure -fa` wouldn't hurt actually.
So here I may well of not correctly configured `mkinitcpio` & it lead to the issues I experienced. 

> Maybe you have `void-mklive` installed? Maybe there's some other hook at work?

No I don't have `void-mklive`installed & I am unaware of any other hook at work & from when I checked it appeared that `dracut` was completely uninstalled.

Upon booting as I said it flagged up the issue that the `root` partition was only mounted RO & I was dropped into a rescue console with a message that it was unable to carry out `fsck` on the other partitions (I can't remember whether I stated that the `root` partition had been subjected to `fsck`or not - probably not that's maybe why it was mounted RO).
After a bit of research I booted from a Live Image to fsck the partitions on my HDD & they were all OK. But as I have stated I spent a considerable amount of time trying to sort the issue without success so I just re-installed from a backup.
So it's quite possible that what I have stated above was the issue - maybe @ahesford could add some input here as from what I understand he uses `mkinitcpio` on his systems?


@ahesford 

> Problems with Debians test suite for initramfs-tools are of no consequence here.

OK accept that &

> has anybody demonstrated that these warnings actually lead to a problem with the initramfs image? 

No I haven't - but then again I don't know if it is causing issues I haven't noticed or been subjected to? Or will cause issues going forward.
I have have changes to my system now - initially by downgrading `kmod` to v.29_2 (as it is a similar vintage to `dracut v.53_2`) but subsequently re-upgrading `kmod` to v.30 & amending the `/usr/lib/dracut/dracut-init.sh` file as per posts above - so maybe others may wish to comment here whether or not they have experienced problems?

> Somebody is welcome to PR a fix.

Indeed - but for me - please see my first post in this thread.

**Closed** 2022-08-23 15:49 UTC
Labels: bug
