### ISSUE TITLE
KDE Plasma high memory consume

### ISSUE THREAD

**Issue by gilbertoferreira** [void-linux/void-packages#25737] opened 2020-10-19 11:50 UTC
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
Void 5.8.16-050816-generic x86_64 AuthenticAMD uptodate rrrmFFF
* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``
plasma-desktop-5.20.0_1 
### Expected behavior
Consume less memory
### Actual behavior
plasma-shell and kwin_X11 are consume high memory compare to Kubuntu, for example.

### Steps to reproduce the behavior
Using KDE Plasma 
Hi there...
I am back again using VoidLinux.
Now I had noticed that KDE Plasma consume more RAM than Kubuntu, for instance.
Without nothing open (like chromium) I had saw at least 1.6GB and when checked about what process could consume such ram, I saw plasmashell and kwin_x11 which consume near 1GB.
My laptop is a Aspire A515-41G with 16GB of ram and SSD Samsung EVO 120GB.
Is there some issue with KDE 5.19 runnig on top of VoidLinux?

**Comment by toluschr** [comment] 2020-10-21 08:22
Try to clear the cache `~/.cache/kwin/` `~/.cache/plasmashell/`

**Comment by b1scu1t** [comment] 2020-10-22 16:38
Are you running KDE 5.19 or 5.20?

**Comment by gilbertoferreira** [comment] 2020-10-22 16:45
5.20

**Comment by gilbertoferreira** [comment] 2020-10-22 20:49
Well... It's sad, but I backup do KDE Neon (Ubuntu Focal Based) and everything is nice!
I hope VoidLinux could improve itself and perhaps I could return to this this nice distro.
For now I will continue with Neon.
Thanks

**Comment by pullmoll** [comment] 2020-10-23 09:48
This is obviously something with your setup or environment.
Running 5.20.0 from a Live ISO inside VirtualBox with 8GB memory and 8 CPU cores I see a physical memory usage of 6% which translates to about 492 MiB when running a Terminal and the Info Center. Are you sure your figures were physical and not virtual memory?

**Comment by ericonr** [comment] 2020-12-13 22:09
Not really something we can act on, and I haven't seen any reports of the issue elsewhere.

Closing for now, feel free to reopen if we get some more actionable information.

**Closed by ericonr** 2020-12-13 22:09 UTC

**Comment by Vistaus** [comment] 2022-01-31 13:05
I'm currently running into this issue with Plasma 5.23. Even with no windows open on a cold boot and desktop effects disabled, System Monitor reports that about 18 GB out of 32 is used. That's excessive.

**Comment by Vistaus** [comment] 2022-01-31 15:41
Seems like it's the Virtual Memory usage that's spiking. There's gotta be a solution for this.

**Comment by Vistaus** [comment] 2022-02-01 11:35
My fan is spinning like crazy because of the high memory usage. It would be great if we could find a solution for this.

**Comment by Anachron** [comment] 2022-02-01 13:08
I've heard something similiar on Linux Mint which was caused by buggy GPU drivers.

Maybe you could check out the kernel log and graphic logs?

**Comment by Vistaus** [comment] 2022-02-01 13:47
My GPU is a built-in Radeon GPU (built into the Ryzen 9 5900HX), so I don't know if there's a separate log.

**Comment by q66** [comment] 2022-02-01 13:56
memory usage does not cause fans to spin up though

**Comment by Anachron** [comment] 2022-02-01 14:49
Surely you could at least check the kernel and X11 log to see if something is suspicious.
