### ISSUE TITLE
Wireguard dkms fails on latest 5.4(.28)

### ISSUE THREAD

**Issue by emacsomancer** [void-linux/void-packages#20558] opened 2020-04-01 20:42 UTC
### System

* xuname:  
`Void 5.4.28_1 x86_64 GenuineIntel uptodate hold rrrmDFFFFFFFFFFFFF`

* package:  
  wireguard-dkms, linux5.4

### Expected behavior
Wireguard dkms builds.
### Actual behavior
Wireguard dkms fails to build for linux5.4.28
### Steps to reproduce the behavior
upgrade to latest 5.4 kernel

build log:
```
DKMS make.log for wireguard-1.0.20200330 for kernel 5.4.28_1 (x86_64)
Tue 31 Mar 2020 01:06:24 PM MDT
make: Entering directory '/usr/src/kernel-headers-5.4.28_1'
  AR      /var/lib/dkms/wireguard/1.0.20200330/build/built-in.a
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/main.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/noise.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/device.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/peer.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/timers.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/queueing.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/send.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/receive.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/socket.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/peerlookup.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/allowedips.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/ratelimiter.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/cookie.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/netlink.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/crypto/zinc/chacha20/chacha20.o
  PERLASM /var/lib/dkms/wireguard/1.0.20200330/build/crypto/zinc/chacha20/chacha20-x86_64.S
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "''",
	LC_COLLATE = "C",
	LC_NUMERIC = "C",
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/crypto/zinc/poly1305/poly1305.o
  PERLASM /var/lib/dkms/wireguard/1.0.20200330/build/crypto/zinc/poly1305/poly1305-x86_64.S
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "''",
	LC_COLLATE = "C",
	LC_NUMERIC = "C",
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/crypto/zinc/chacha20poly1305.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/crypto/zinc/blake2s/blake2s.o
  AS [M]  /var/lib/dkms/wireguard/1.0.20200330/build/crypto/zinc/blake2s/blake2s-x86_64.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/crypto/zinc/curve25519/curve25519.o
  AS [M]  /var/lib/dkms/wireguard/1.0.20200330/build/crypto/zinc/chacha20/chacha20-x86_64.o
  AS [M]  /var/lib/dkms/wireguard/1.0.20200330/build/crypto/zinc/poly1305/poly1305-x86_64.o
  LD [M]  /var/lib/dkms/wireguard/1.0.20200330/build/wireguard.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /var/lib/dkms/wireguard/1.0.20200330/build/wireguard.mod.o
  LD [M]  /var/lib/dkms/wireguard/1.0.20200330/build/wireguard.ko
make: Leaving directory '/usr/src/kernel-headers-5.4.28_1'
```

**Comment by Piraty** [comment] 2020-04-02 08:52
fixed in 924f40c056e94f1ec24cf0548f6932830c6586e1

**Comment by michael-keyes** [comment] 2022-02-01 14:45
again

**Comment by paper42** [comment] 2022-02-01 16:59
Actually no, I can't reproduce this, sorry for the confusion. @michael-keyes could you post the logs?

**Closed by paper42** 2022-02-01 16:59 UTC
Labels: bug

**Comment by michael-keyes** [comment] 2022-02-02 13:58
> Actually no, I can't reproduce this, sorry for the confusion. @michael-keyes could you post the logs?

https://i.kym-cdn.com/entries/icons/facebook/000/021/665/DpQ9YJl.jpg
Okay, sure. Log files are not in /var/lib/dkms/ because...Void Linux

**Comment by paper42** [comment] 2022-02-02 14:08
> > Actually no, I can't reproduce this, sorry for the confusion. @michael-keyes could you post the logs?
> 
> [i.kym-cdn.com/entries/icons/facebook/000/021/665/DpQ9YJl.jpg](https://i.kym-cdn.com/entries/icons/facebook/000/021/665/DpQ9YJl.jpg) Okay, sure. Oh wait, log files are not in /var/lib/dkms/ because...Void Linux

Let's keep this professional, no need for this tone. There is nothing Void specific, the logs are in `/var/lib/dkms/wireguard/1.0.20211208/5.4.174_1/x86_64/log/make.log`. It's possible it was not created because the dkms trigger didn't even run. How did you figure out it doesn't work? Please post the xbps-install command you ran and its output.

**Comment by michael-keyes** [comment] 2022-02-02 14:24
No long files exist
openresolv-3.12.0_1: configuring ...
openresolv-3.12.0_1: installed successfully.
wireguard-tools-1.0.20210914_2: configuring ...
wireguard-tools-1.0.20210914_2: installed successfully.
wireguard-dkms-1.0.20211208_1: configuring ...
Added DKMS module 'wireguard-1.0.20211208'.
Skipping kernel-5.13.19_1. kernel-headers package not installed...
Building DKMS module 'wireguard-1.0.20211208' for kernel-5.15.17_1... FAILED!
DKMS module 'wireguard-1.0.20211208' failed to build, please check /var/lib/dkms
for errors in the log file.
Building DKMS module 'wireguard-1.0.20211208' for kernel-5.15.19_1... FAILED!
DKMS module 'wireguard-1.0.20211208' failed to build, please check /var/lib/dkms
for errors in the log file.
wireguard-dkms-1.0.20211208_1: installed successfully.
wireguard-0.0.20191226_1: configuring ...
wireguard-0.0.20191226_1: installed successfully.

**Comment by paper42** [comment] 2022-02-02 14:33
You didn't mention it was "failing" for 5.15, so I assumed it was failing for 5.4 (this issue is about 5.4).

This is the description of wireguard-dkms:

> Fast, modern, secure VPN tunnel (DKMS module for Linux <= 5.5)

Newer versions don't need a separate module for wireguard because wireguard is already built into the kernel. The error message could be better though.

Next time, don't say "again" on an old issue that's different from your problem, open a new one, fill the template, provide details and we will immediately know what is wrong.
