### ISSUE TITLE
FreeCAD 0.18.3 crashing on wayland

### ISSUE THREAD

**Issue by no2spam** [void-linux/void-packages#14626] opened 2019-09-21 10:44 UTC
### System

* xuname:  
Void 5.2.16_1 x86_64 GenuineIntel uptodate rrrmFFF
* package:  
FreeCAD 0.18.3

kwayland-5.62.0_1                   
kwayland-integration-5.16.5_1      
qt5-wayland-5.13.0_4              
wayland-1.17.0_1                    
xorg-server-xwayland-1.20.5_2       

### Expected behavior
Start FreeCAD -> Create new document (File->New) ->start sketching as it works on X server
### Actual behavior
Start FreeCAD -> Create new document (File->New) -> app crashes with the following error:

FreeCAD 0.18.3, Libs: 0.18.3R1_voidlinux

FreeCAD: gl.cpp:2344: const cc_glglue* cc_glglue_instance(int): Assertion `current_ctx && "Must have a current GL context when instantiating cc_glglue!! (Note: if you are using an old Mesa GL version, set the environment variable COIN_GL_NO_CURRENT_CONTEXT_CHECK to get around what may be a Mesa bug.)"' failed.

### Steps to reproduce the behavior

Run FreeCAD 0.18 on wayland

**Comment by yopito** [comment] 2019-10-01 04:29
As a workaround, does forcing Qt5 to use X11 backend works within the wayland context ? 
```
$ QT_QPA_PLATFORM=xcb /usr/bin/FreeCAD
```
Others indicate that Coin3D might be the problem. I need a deeper look:
https://forum.freecadweb.org/viewtopic.php?t=33359

**Comment by hobbes1069** [comment] 2019-11-13 20:55
Seeing the same thing on Fedora... still searching for a fix.

https://bugzilla.redhat.com/show_bug.cgi?id=1768480

**Comment by elliotclee** [comment] 2019-12-02 23:33
One helpful data point is that running as FreeCAD as root seems to make the symptoms disappear. Dunno if there is a permissions issue.

**Comment by luzpaz** [comment] 2019-12-29 13:27
Looks like a patch for the issue: https://forum.freecadweb.org/viewtopic.php?t=33359#p354412

**Comment by foopub** [comment] 2021-11-23 00:39
I've tested the patch from that website on coin3 package and it seems to work so far. 
`./xbps-src pkg -j24 coin3`
`doas xbps-install -fR hostdir/binpkgs/ coin3`

I'll be using FreeCAD the next few days and if something seemingly relevant breaks, I'll update. @yopito how do you recon this should be handled? 

I don't know what this functionality that's being removed does, but if it's important in general, we can patch it only when a `wayland` option is passed. Otherwise patch it normally, and add back the functionality with a `glx` option.

**Comment by yopito** [comment] 2021-11-29 12:21
sorry for late reply and thanks for your tests.
I don't feel confident enough about it, especially the patch's impact on X11 based system.
Let's discuss with upstream's first : see https://github.com/coin3d/coin/issues/451

**Comment by luzpaz** [comment] 2022-03-02 19:20
v0.18.x is obsolete.  
Ticket should probably be closed.

**Comment by SammyTheSnake** [comment] 2022-03-02 21:17
Don't close the issue, the behaviour still continues with the latest versions.

As I understand it, the issue is with Wayland support in the Coin library used for 3d rendering. Coin can be hacked to just not link with GLX, but that's not a plan that works for most users of Coin so it hasn't been implemented.

reference: https://forum.freecadweb.org/viewtopic.php?t=33359

**Comment by gmelikov** [comment] 2023-10-22 13:34
[code]
OS: Debian GNU/Linux trixie/sid (X-Generic/plasmawayland)
Word size of FreeCAD: 64-bit
Version: 0.20.2.
Build type: Release
Python 3.11.5, Qt 5.15.10, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
[/code]

Still reproducible.

**Comment by sgn** [comment] 2023-10-23 04:07
#41425

**Closed** 2023-10-23 04:07 UTC
Labels: bug
