### ISSUE TITLE
qt5-webengine: audio playback does not always use PulseAudio, instead capturing raw ALSA devices

### ISSUE THREAD

**Issue by klardotsh** [void-linux/void-packages#25906] opened 2020-10-26 23:38 UTC
### System

* xuname:  `Void 5.8.16_1 x86_64-musl GenuineIntel notuptodate rFFFF`
* package:  `qt5-webengine-5.15.1_1`

### Expected behavior

qutebrowser (or other QT WebEngine-based browsers, eg. Falkon, though I did not test that one) routes all audio through PulseAudio (including respecting device choices - eg. a bluetooth headset over onboard audio, if the headset is the default). Failing that, it should play through the ALSA `default` device, which in my setup is also PulseAudio, via alsa-plugins-pulseaudido.

### Actual behavior

qutebrowser's QT WebEngine processes skip PulseAudio entirely an overwhelming majority of the time (however, seemingly not 100% of the time, for reasons I couldn't determine a pattern to) and instead [open their own locks on /dev/dsp/ cards](https://gist.github.com/klardotsh/e2c1cd165a30c4b72e5cef6a35ee21e4), seemingly always whatever is `sysdefault`. This cascades into a few undesired behaviors:

- The wrong audio device is used (in my case, Jitsi and YouTube playback routed through my laptop speakers instead of my Bluetooth headphones, the latter being the PulseAudio default)
- No PulseAudio-using applications can play audio at the same time over that soundcard. After disconnecting my BT headset (making Pulse fall back to the onboard card), I attempted to `mpv -ao=pulse audiofile.wav` from a terminal, and couldn't because the resource was busy (or something to that effect - I don't have the logs anymore) until the YouTube tab was closed.
- Only one tab can play audio at a time, which has been reported in Qutebrowser upstream as https://github.com/qutebrowser/qutebrowser/issues/5815. There is a similar issue open here, https://github.com/void-linux/void-packages/issues/25852, that I'm not sure is identical because I haven't looked into it.

### Steps to reproduce the behavior

Using the current stable release of QT WebEngine and PulseAudio, try to play a YouTube video, or test your audio settings in [Jitsi](https://meet.jit.si). While doing so, have `pulsemixer` or `pavucontrol` running and keep an eye on the audio sources - you _likely_ won't see `qtwebengine` in the list. This bug does not always repro reliably - you may need to restart qutebrowser and/or your machine and/or PulseAudio and/or attached soundcards to repro it.

### More Context

I already linked https://github.com/qutebrowser/qutebrowser/issues/5815 which is full of Void users with similar classes of errors (some manifesting in slightly different manners, but the same underlying issues with the same log output). There's also https://old.reddit.com/r/qutebrowser/comments/iy00k6/suddenly_no_sound_in_qutebrowser/ and https://www.reddit.com/r/voidlinux/comments/j2re7n/issues_getting_pulseaudio_to_work_correctly/ which each have instances of spurious audio reliability in `qutebrowser` that started some time recently, and seem to manifest similarly to this issue in all appreciable ways. Further, https://github.com/void-linux/void-packages/issues/25766 discusses `sndio` support itself being funky in recent QT WebEngine, which, while a different bug than I'm currently reporting, may share the same resolution. I'm linking here for completeness.

Further, I was able to change `build_options_default="sndio"` to `build_options_default=""` in the build template, compile my own `qt5-webengine-5.15.1_2`, install it, and can no longer repro the issue. In `#voidlinux` IRC, we've isolated that this is likely related to the conditional `sndio` patching applied, but as I don't use `sndio`, I don't entirely feel useful attempting to fix that patchset if anyone more qualified/with more context is available. If not, I can try to take a look.

cc @The-Compiler, @ericonr, and @Johnnynator

**Comment by minikN** [comment] 2020-10-27 09:18
Thanks @klardotsh I can confirm that bug with qutebrowser.

**Comment by travankor** [comment] 2020-10-28 06:31
I've also ran into this issue (reported on IRC a while ago), but didn't really look into it at the time (although I guessed that the sndio patches were the culprit).

Should sndio be part of the default build? How many people actively use and test sndio?

**Comment by Johnnynator** [comment] 2020-10-28 18:20
> I've also ran into this issue (reported on IRC a while ago), but didn't really look into it at the time (although I guessed that the sndio patches were the culprit).
> 
> Should sndio be part of the default build? How many people actively use and test sndio?

I do use qt5-webengine  with sndio, but if I can't figure out what causes the problem with pulse, I will hide sndio behind an env var (I don't want to fully disable it).

**Comment by Johnnynator** [comment] 2020-11-21 20:55
Can you test if this still happens with qt5.15.2? I have a PR open for testing #26574

**Comment by travankor** [comment] 2020-12-07 04:53
I've been running QT5.12.2-sndio and haven't noticed any issues with it so far. That said, I don't use qutebrowser that much now due to memory leaks in the main process.

Would prefer if a more frequent qt-webengine user chimes in though.

**Comment by travankor** [comment] 2020-12-20 13:01
Actually ran into the previous issue issue where mpv wouldn't work while qtwebengine was playing audio

```
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
[ao/alsa] Playback open error: Device or resource busy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[ao/jack] cannot open server
[ao] Failed to initialize audio driver 'jack'
Could not open/initialize audio device -> no sound.
Audio: no audio
```

Will give the non-sndio version a shot later.

**Comment by pbui** [comment] 2020-12-20 21:42
Using the qt5.15.2 that I built from #26574, qutebrowser is able to play audio normally via pulseaudio (it does not go to ALSA).  I also tested playing audio with mpv, mpd, and qutebrowser at the same time and it behaved normally.  Therefore, this problem looks resolved with that update (especially since it appears that sndio is now OFF by default).

Just a few notes: 1. I had to rebase and remove `srcpkgs/qt5-webengine/patches/0200-nullptr-rtcpeerconnectionhandler.patch`, 2. the build for qt5-webengine warned about `use_sndio=true` not being recognized (by default the build option is OFF, but the configuration arguments still specify it).

**Comment by ericonr** [comment] 2021-01-20 20:52
Is this still an issue?

**Comment by pbui** [comment] 2021-01-20 20:57
No, it appears to be working fine now.

**Comment by ericonr** [comment] 2021-01-20 20:57
Thanks.

**Closed by ericonr** 2021-01-20 20:57 UTC
