### ISSUE TITLE
geoip-data: build failure

### ISSUE THREAD

**Issue by xtraeme** [void-linux/void-packages#12879] opened 2019-07-07 08:26 UTC
```
=> geoip-data-20171002_2: building ...
=> geoip-data-20171002_2: running do_fetch ...
http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz: Not Found
=> ERROR: geoip-data-20171002_2: do_fetch: '$XBPS_FETCH_CMD http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz' exited with 1
=> ERROR:   in do_fetch() at srcpkgs/geoip-data/template:13
```

**Comment by biopsin** [comment] 2019-07-07 10:53
legacy db 20180403 could be acquired from (link nicked from transmission-gui issue)
GeoLiteURL = 'https://dl.miyuru.lk/geoip/maxmind/country/maxmind4.dat.gz'
... temporary ...

**Comment by ndowens** [comment] 2019-11-28 01:01
Duplicate of #9151 and proposed PR #16216

**Closed** 2020-04-23 16:50 UTC
Labels: bug
