### ISSUE TITLE
Pipewire screensharing not working in KDE

### ISSUE THREAD

**Issue by Konata390** [void-linux/void-packages#31274] opened 2021-06-03 12:33 UTC
### System

* xuname:  Void 5.12.8_1 x86_64 AuthenticAMD uptodate rrrmFFFFF
* packages:  kwin-5.21.5_1 plasma-workspace-5.21.5_1

### Expected behavior
Screensharing in KDE should work under wayland in applications such as firefox and obs.
### Actual behavior
Screensharing doesn't work
### Steps to reproduce the behavior
- Build plasma-workspace and kwin with the pipewire build option enabled
- Restart KDE
- Open firefox, navigate to https://mozilla.github.io/webrtc-landing/gum_test.html and click on "Screen capture"

### Additional info
- I know that pipewire is working *somewhat* because after enabling the build options I have working window previews (previously they were just empty boxes when I hovered over them).
- Pipewire works fine for me as an audio Server
- I have pipewire, pipewire-pulse, pipewire-media-session and xdg-desktop-portal-kde running
- when running "xdg-desktop-portal-kde -v" in a terminal I get the output `zkde_screencast_unstable_v1 does not seem to be available` when triggering screensharing in obs or firefox.

**Comment by HadetTheUndying** [comment] 2021-06-23 01:46
You may want to test https://github.com/void-linux/void-packages/pull/31549

I'll test on Gnome tomorrow.

**Comment by paper42** [comment] 2021-06-23 10:29
> Build plasma-workspace and kwin with the pipewire build option enabled

what does this mean? pipewire should be enabled by default

> You may want to test #31549

That PR doesn't change anything with screen sharing.

Do you have the latest obs version? Are you sure it's not running under xwayland?

**Comment by Johnnynator** [comment] 2021-06-23 11:03
> > Build plasma-workspace and kwin with the pipewire build option enabled
> 
> what does this mean? pipewire should be enabled by default

No, I initially didn't enable it by default, since it made Plasma rather unstable under wayland. Most of the probmles are kinda resolved in regards of stability and I will enable it again with the next update (if I won't forget it).

But this only fixes one issue. Plasma under Void does seem to have a problem noticing that pipe wire is running/available and I wasn't able yet to figure out yet what the cause is.

**Comment by paper42** [comment] 2021-06-24 10:53
> Also no Xwayland isn't the issue.

obs doesn't show a pipewire screen sharing option when not running with the wayland backend.

**Comment by JaceHensley** [comment] 2021-09-14 19:55
I'm hitting this as well.

pipewire: 0.3.35
firefox: 92
kde: 5.22.5
xdg-desktop-portal-kde: 5.22.5

I can't figure out what's going on. In firefox in the gUM test page I click "Use operating system setting" and then "Allow" but nothing happens, I do see "zkde_screencast_unstable_v1 does not seem to be available" when I run `xdg-desktop-portal-kde` in the terminal. But in Chromium it lets me select a screen (without a preview of the screen) but then after sharing the gUM page just displays a black screen with no cursor or anything. 

Does that have to do with Plasma under void not knowing when pipewire is running? I've added `pipewire` to "Login Scripts" in KDE

**Comment by Johnnynator** [comment] 2021-09-15 23:11
I'm not sure yet where the issue is. `xdg-desktop-portal-kde` does not motivate kf.wayland.client enough to announce `zkde_screencast_unstable_v1`. so the ` m_screencasting = new Screencasting(m_registry, name, version, this);` line will never be called.

The autotest `testScreencastV1Interface` from `kwayland-server` on the other hand does manage to get the kwayland lib to announce screencast and does not fail. I need to check where the two differ and (except the obvious parts).

Another note for myself `QT_LOGGING_RULES="*.debug=true"` is pretty useful to get more verbose log, we want to see a line containing `kf.wayland.client: Unknown interface announced:  zkde_screencast_unstable_v1` in the output

**Comment by JaceHensley** [comment] 2021-09-15 23:28
lmk if I can be of any help, getting logs or whatever else

**Comment by JaceHensley** [comment] 2021-11-09 18:33
any updates on this? it's like the only thing that doesn't work for me with my current setup haha. Totally happy to dig in too just don't know where to start looking

**Comment by bakuhatu** [comment] 2022-01-23 20:13
I just tried this:
`export QT_LOGGING_RULES="*.debug=true"
xdg-desktop-portal-kde -v`

And the output shows `xdp-kde-screencast: zkde_screencast_unstable_v1 does not seem to be available` among all the other stuff.

Then I run `obs --verbose` in a new terminal (excluded the stuff that didn't look weird):
```
...
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
...
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
...
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
error: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: cannot open shared object file: No such file or directory
...
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
warning: [pipewire] Failed to create session, denied or cancelled by user
warning: [pipewire] Failed to create session, denied or cancelled by user

```
Then, if I try to select a window from window capture:

```
xdp-kde-screencast: CreateSession called with parameters:
xdp-kde-screencast:     handle:  "/org/freedesktop/portal/desktop/request/1_100/obs8"
xdp-kde-screencast:     session_handle:  "/org/freedesktop/portal/desktop/session/1_100/obs8"
xdp-kde-screencast:     app_id:  ""
xdp-kde-screencast:     options:  QMap()
xdp-kde-screencast: zkde_screencast_unstable_v1 does not seem to be available
xdp-kde-session: "org.freedesktop.impl.portal.Session"
xdp-kde-session: "Close"
xdp-kde-session: "/org/freedesktop/portal/desktop/session/1_100/obs8"
```

If there's anything I can do to help, please tell me.

**Comment by bakuhatu** [comment] 2022-01-23 22:14
I might have done the `QT_LOGGING_RULES` thing wrong last time.

I tried again with `QT_LOGGING_RULES="*.debug=true" /usr/lib64/libexec/xdg-desktop-portal-kde -v`

saw this: 
`kf.crash: Could not find drkonqi in search paths: ("/usr/lib/libexec", "/usr/lib/qt5/libexec", "/usr/lib64/libexec")` 

but no  `kf.wayland.client: Unknown interface announced: zkde_screencast_unstable_v1`

Also, I tried looking at [waylandintegration.cpp](https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/blob/master/src/waylandintegration.cpp):

```
connect(m_registry, &KWayland::Client::Registry::interfaceAnnounced, this, [this](const QByteArray &interfaceName, quint32 name, quint32 version) {
        if (interfaceName != "zkde_screencast_unstable_v1")
            return;
        m_screencasting = new Screencasting(m_registry, name, version, this);
    });
```
This is the part @Johnnynator was talking about I guess. 
I think it's connecting an interfaceAnnounced signal to m_registry, but I don't understand what the last two parameters are for and I can't find what `connect` is. My C++ knowledge is pretty basic so idk.

I couldn't find the `interfaceAnnounced` implementation, though I found the declaration in [kwayland/registry.h](https://github.com/KDE/kwayland/blob/10e3d60ab413e4389b9ecf88909f854f6eddbf1c/src/client/registry.h). I guess the implementation is the 4th argument to connect, but I don't know how to find where it calls that function/emits that signal to see what it's using as `interfaceName`.

**Comment by JaceHensley** [comment] 2022-01-24 18:54
So I saw the interface name being used here https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/blob/master/data/org.freedesktop.impl.portal.desktop.kde.desktop.in#L36 would `X-KDE-Wayland-Interfaces=zkde_screencast_unstable_v1` need to be added to .desktop files of the applications?

**Comment by bakuhatu** [comment] 2022-01-24 19:21
Adding that line to the .desktop file fixed OBS for me.

**Comment by russnes** [comment] 2022-02-06 18:41
I have the same issue, no windows to select in OBS in Window Capture (PipeWire) sources, and getting warning 

    warning: [pipewire] Failed to create session, denied or cancelled by user.

I have the package `xdg-desktop-portal-kde` installed, but I don't have the command in my PATH apparently. I see it running in `ps aux | grep xdg` though, not sure what started it, but could have been OBS. It doesn't go away if I close OBS.

pipewire 0.3.45
OBS 27.1.3
kde5 5.23.0
xdg-desktop-portal-kde 5.23.5
linux 5.15.19

**Comment by bakuhatu** [comment] 2022-02-07 23:34
After I updated pipewire (0.3.45) and other packages today, Select Window in OBS no longer shows the wayland window selector although my .desktop file was unchanged.

**Comment by JaceHensley** [comment] 2022-02-11 17:05
interesting, I was never able to get it working even with that line added to the `.desktop`

**Comment by Johnnynator** [comment] 2022-02-11 17:58
Finally found some time to finish digging into this.
The issue lies in kservice not being able to find the needed desktop files of xdg-desktop-portal-kde
`KWIN_UTILS: Could not find the desktop file for "/usr/lib/libexec/xdg-desktop-portal-kde"`, which is due to our `.desktop` files referring to `lib64` and not just `lib`.
Will take a look how to fix this issue, but I will put a fix in together with the plasma 5.24 update, hopefully this weekend, if not somewhen next week.

Until then you can just edit the `/usr/share/applications/org.freedesktop.impl.portal.desktop.kde.desktop` to point to `/usr/lib/libexec/xdg-desktop-portal-kde`

**Comment by JaceHensley** [comment] 2022-02-11 20:12
Editing that .desktop file worked, I can share my screens and windows from Firefox now!! :tada:

**Comment by Johnnynator** [comment] 2022-02-11 23:45
I do have a test repo up for plasma 5.24, kde framework 5.90 and some app updates.
Repo: https://void.johnnynator.dev/plasma-5.24/
Fingerprint: `f2:92:af:af:25:e5:9b:5f:8d:c4:c1:7d:90:2e:2d:19`

Build from this branch: https://github.com/Johnnynator/void-packages/tree/kde-stuff

I will finish it up and push to master once kde frameowkr 5.91 is released, hopefully later today.

**Closed** 2022-02-15 20:48 UTC
Labels: bug
