### ISSUE TITLE
[Package Request] PowerShell

### ISSUE THREAD

**Issue by smorimoto** [void-linux/void-packages#31014] opened 2021-05-20 15:10 UTC
Homepage: https://docs.microsoft.com/en-us/powershell
Download page: https://github.com/PowerShell/PowerShell

**Comment by ericonr** [comment] 2021-05-20 15:16
Duplicate of #11993

**Closed by ericonr** 2021-05-20 15:16 UTC
Labels: request

**Comment by smorimoto** [comment] 2021-05-20 16:58
Oops, sorry for the disturbance!
