### ISSUE TITLE
qutebrowser renders a black screen

### ISSUE THREAD

**Issue by non-Jedi** [void-linux/void-packages#1033] opened 2018-07-19 13:18 UTC
### System

* xuname:  
  * Void 4.17.6_1 x86_64 GenuineIntel uptodate rrFF
* package:  
  * qutebrowser-1.4.1_1

### Expected behavior

qutebrowser is started and shows my homescreen as normal.

### Actual behavior

qutebrowser is started and shows a blank, black screen; no errors are raised by qutebrowser. Other than not displaying anything, qutebrowser seems to be functioning normally. I can navigate to websites and see the window name change.

### Steps to reproduce the behavior

qutebrowser was working fine even with 1.4.1_1, but after updating yesterday it no longer works, so it's some change in the graphics stack or qt5 I think (I know next to nothing about either of those areas)? If qutebrowser is started with `QT_QUICK_backend=software`, everything works as expected.

If it's helpful, here's the output of `qtdiag-qt5`. This problem occurs no matter what monitor I'm hooked up to, so please ignore that part.

```
Qt 5.10.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.3.0) on "xcb" 
OS: void [linux version 4.17.6_1]

Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 RTM HLE

Environment:

Features: QT_NO_EXCEPTIONS

Library info:
  PrefixPath: /usr
  DocumentationPath: /usr/share/doc/qt5
  HeadersPath: /usr/include/qt5
  LibrariesPath: /usr/lib
  LibraryExecutablesPath: /usr/lib/qt5/libexec
  BinariesPath: /usr/lib/qt5/bin
  PluginsPath: /usr/lib/qt5/plugins
  ImportsPath: /usr/lib/qt5/imports
  Qml2ImportsPath: /usr/lib/qt5/qml
  ArchDataPath: /usr/lib/qt5
  DataPath: /usr/share/qt5
  TranslationsPath: /usr/share/qt5/translations
  ExamplesPath: /usr/share/qt5/examples
  TestsPath: /usr/tests
  SettingsPath: /etc/xdg

Standard paths [*...* denote writable entry]:
  DesktopLocation: "Desktop" */home/adam/Desktop*
  DocumentsLocation: "Documents" */home/adam/Documents*
  FontsLocation: "Fonts" */home/adam/.local/share/fonts* /home/adam/.fonts
  ApplicationsLocation: "Applications" */home/adam/.local/share/applications* /usr/local/share/applications /usr/share/applications
  MusicLocation: "Music" */home/adam/Music*
  MoviesLocation: "Movies" */home/adam/Videos*
  PicturesLocation: "Pictures" */home/adam/Pictures*
  TempLocation: "Temporary Directory" */tmp*
  HomeLocation: "Home" */home/adam*
  AppLocalDataLocation: "Application Data" */home/adam/.local/share/QtProject/qtdiag* /usr/local/share/QtProject/qtdiag /usr/share/QtProject/qtdiag
  CacheLocation: "Cache" */home/adam/.cache/QtProject/qtdiag*
  GenericDataLocation: "Shared Data" */home/adam/.local/share* /usr/local/share /usr/share
  RuntimeLocation: "Runtime" */run/user/1000*
  ConfigLocation: "Configuration" */home/adam/.config* /etc/xdg
  DownloadLocation: "Download" */home/adam/Downloads*
  GenericCacheLocation: "Shared Cache" */home/adam/.cache*
  GenericConfigLocation: "Shared Configuration" */home/adam/.config* /etc/xdg
  AppDataLocation: "Application Data" */home/adam/.local/share/QtProject/qtdiag* /usr/local/share/QtProject/qtdiag /usr/share/QtProject/qtdiag
  AppConfigLocation: "Application Configuration" */home/adam/.config/QtProject/qtdiag* /etc/xdg/QtProject/qtdiag

File selectors (increasing order of precedence):
  en_US unix linux void

Network:
  Using "LibreSSL 2.7.4", version: 0x20000000

Platform capabilities: ThreadedPixmaps OpenGL WindowMasks MultipleWindows ForeignWindows NonFullScreenWindows NativeWidgets WindowManagement SyncState RasterGLSurface SwitchableWidgetComposition

Style hints:
  mouseDoubleClickInterval: 400
  mousePressAndHoldInterval: 800
  startDragDistance: 12
  startDragTime: 500
  startDragVelocity: 0
  keyboardInputInterval: 400
  keyboardAutoRepeatRate: 30
  cursorFlashTime: 1000
  showIsFullScreen: 0
  showIsMaximized: 0
  passwordMaskDelay: 0
  passwordMaskCharacter: U+25CF
  fontSmoothingGamma: 1.7
  useRtlExtensions: 0
  setFocusOnTouchRelease: 0
  tabFocusBehavior: Qt::TabFocusBehavior(TabFocusAllControls) 
  singleClickActivation: 0

Additional style hints (QPlatformIntegration):
  ReplayMousePressOutsidePopup: 0

Theme:
  Platforms requested : unknown,generic
            available : gtk3
  Styles requested    : Fusion,Windows
         available    : Windows,Fusion
  System font         : "Sans Serif" 9

Fonts:
  General font : "Sans Serif" 9
  Fixed font   : "monospace" 9
  Title font   : "DejaVu Sans" 12
  Smallest font: "DejaVu Sans" 12

Palette:
  WindowText: #ff000000
  Button: #ffefefef
  Light: #ffffffff
  Midlight: #ffcbcbcb
  Dark: #ff9f9f9f
  Mid: #ffb8b8b8
  Text: #ff000000
  BrightText: #ffffffff
  ButtonText: #ff000000
  Base: #ffffffff
  Window: #ffefefef
  Shadow: #ff767676
  Highlight: #ff308cc6
  HighlightedText: #ffffffff
  Link: #ff0000ff
  LinkVisited: #ffff00ff
  AlternateBase: #fff7f7f7
  NoRole: #ff000000
  ToolTipBase: #ffffffdc
  ToolTipText: #ff000000

Screens: 2, High DPI scaling: inactive
# 0 "DP2" Depth: 24 Primary: yes
  Manufacturer: Hewlett Packard
  Model: HP LA2306
  Serial number: CNC14102NB
  Geometry: 1920x1080+0+0 Available: 1920x1080+0+0
  Virtual geometry: 3286x1080+0+0 Available: 3286x1080+0+0
  2 virtual siblings
  Physical size: 510x290 mm  Refresh: 60 Hz Power state: 0
  Physical DPI: 95.6235,94.5931 Logical DPI: 118,118 Subpixel_None
  DevicePixelRatio: 1 Pixel density: 1
  Primary orientation: 2 Orientation: 2 Native orientation: 0 OrientationUpdateMask: 0

# 1 "eDP1" Depth: 24 Primary: no
  Manufacturer: SDC
  Model: 
  Serial number: 
  Geometry: 1366x768+1920+312 Available: 1366x768+1920+312
  Virtual geometry: 3286x1080+0+0 Available: 3286x1080+0+0
  2 virtual siblings
  Physical size: 310x170 mm  Refresh: 59 Hz Power state: 0
  Physical DPI: 111.924,114.748 Logical DPI: 118,118 Subpixel_None
  DevicePixelRatio: 1 Pixel density: 1
  Primary orientation: 2 Orientation: 2 Native orientation: 0 OrientationUpdateMask: 0

LibGL Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
Version: 3.0 Mesa 18.1.4
Shading language: 1.30
Format: Version: 3.0 Profile: 0 Swap behavior: 0 Buffer size (RGB): 8,8,8
Profile: None (QOpenGLFunctions_3_0)
```

**Comment by TeddyDD** [comment] 2018-07-19 13:29
I can confirm. I goggled a bit and it seems to be some incompability between QtWebEngine and graphics drivers???

Anyway, I can run qutebrowser with ` env QT_QUICK_BACKEND=software qutebrowser` but it somethimes freeze when switching tabs

**Comment by non-Jedi** [comment] 2018-07-19 13:40
The linked issue was specifically a problem with the llvmpipe driver. This is something else though it's got the same symptoms.

**Comment by xYuusha** [comment] 2018-07-20 06:08
I had the same problem and solved it downgrading mesa to 18.1.4_1.
This looks like Qt and mesa incompatibility problem as sddm was also broken.

**Comment by Gottox** [comment] 2018-07-20 07:47
It might be interesting which graphics card is used.

**Comment by Gottox** [comment] 2018-07-20 08:02
can reproduce the blackscreen issue with `falkon`.

**Comment by Gottox** [comment] 2018-07-20 08:03
@pullmoll @maxice8 This could be caused by either qt or mesa update/rebuild. Can you help to find the issue here?

**Comment by pullmoll** [comment] 2018-07-20 11:04
qutebrowser works for me, except it crashes in the renderer when trying to render very large input like `https://build.voidlinux.eu/builders/x86_64_builder/builds/10317/steps/shell_3/logs/stdio`. Trying to go to the end of the page there first displays garbled tiles, then black tiles, and finally the crash is reported.

**Comment by Gottox** [comment] 2018-07-20 13:29
![screenshot from 2018-07-20 15-28-52](https://user-images.githubusercontent.com/1056976/43004961-a162848e-8c31-11e8-99e8-1f0eca7fc7a0.png)

Same issue with falkon

**Comment by non-Jedi** [comment] 2018-07-20 13:37
For what it's worth I'm on Intel integrated graphics (Intel Corporation HD Graphics 5500). On machine at home with dedicated AMD card, I see no issues.

**Comment by newbluemoon** [comment] 2018-07-20 14:09
I’m testing qutebrowser and falkon on my RPi 3 (which should be CXX11 ABI only) right now and have no issues whatsoever. However, the linked build log is a bit too heavy for the RPi. ;)

**Comment by TeddyDD** [comment] 2018-07-20 16:06
I have intel integrated graphics and I see black screen

**Comment by The-Compiler** [comment] 2018-07-21 19:44
FWIW `:set qt.force_software_rendering software-opengl` (or starting with `-s ...`) might work as a workaround.

**Comment by Follpvosten** [comment] 2018-07-26 06:34
Can confirm; sddm gives me a white screen (interestingly, I can still log in just fine, I just can't see anything).
KDE5 does not work at all, all it shows is a black screen with a white square in the upper right quarter of the screen. Qt programs generally work fine tho (on EXWM as well as on XFCE).

**Comment by Gottox** [comment] 2018-07-31 17:44
This issue still persists after the c++ rebuild. @The-Compiler any idea what could cause the issue?

**Comment by The-Compiler** [comment] 2018-07-31 17:46
No clue I'm afraid, but I've only heard of void users having this issue so far...

**Comment by maxice8** [comment] 2018-07-31 17:52
@Gottox works fine here with https://github.com/void-linux/void-packages/pull/1242

**Comment by Hoshpak** [comment] 2018-08-20 08:28
fixed by the Mesa update.

**Closed by Hoshpak** 2018-08-20 08:28 UTC

**Comment by non-Jedi** [comment] 2018-08-25 17:07
Confirm that this issue is fixed on my system.
