### ISSUE TITLE
Stripped .so files in mesa-*-dri-dbg

### ISSUE THREAD

**Issue by blah1** [void-linux/void-packages#15104] opened 2019-10-05 02:17 UTC
### System

* xuname:  
  `Void 5.2.18_1 x86_64-musl GenuineIntel uptodate rrrnFFFFFF`
* package:  
  `mesa-intel-dri-dbg-19.1.7_3`
possibly also:
  `mesa-ati-dri-dbg-19.1.7_3`
  `mesa-nouveau-dri-dbg-19.1.7_3`
  `mesa-vmwgfx-dri-dbg-19.1.7_3`

### Expected behavior
Using gdb to debug a crash in /usr/lib/xorg/modules/drivers/i915_dri.so shows the relevant functions where the crash occured.
/usr/lib/debug/usr/lib/xorg/modules/i915_dri.so is more than a megabyte in size and not stripped

### Actual behavior
gdb shows "#0  0x00007ffff6d86cd9 in ?? () from /usr/lib/xorg/modules/drivers/i915_dri.so" and similar lines for relevant functions
`file /usr/lib/debug/usr/lib/xorg/modules/drivers/i915_dri.so` says that the file is stripped
`ls -l /usr/lib/debug/usr/lib/xorg/modules/drivers/i915_dri.so` says that the file is only 2768 bytes

### Steps to reproduce the behavior
Run `file /usr/lib/debug/usr/lib/xorg/modules/drivers/i915_dri.so` and see if the file is stripped of debugging symbols
A list of stripped files in mesa-\*-dri-dbg packages can be acquired with `for j in ati nouveau intel vmwgfx ; do xbps-query -f mesa-"$j"-dri-dbg ; done |while read -r i ; do ls -l "$i" ; file "$i" ; done |grep -B1 ', stripped' |grep -v '^--$' |sed '2~2d'`
These are the mesa-*-dri-dbg files that I found that are stripped:
  `/usr/lib/debug/usr/lib/dri/nouveau_drv_video.so`
  `/usr/lib/debug/usr/lib/libXvMCnouveau.so.1.0.0`
  `/usr/lib/debug/usr/lib/vdpau/libvdpau_nouveau.so.1.0.0`
  `/usr/lib/debug/usr/lib/xorg/modules/drivers/nouveau_dri.so`
  `/usr/lib/debug/usr/lib/xorg/modules/drivers/nouveau_vieux_dri.so`
  `/usr/lib/debug/usr/lib/dri/r600_drv_video.so`
  `/usr/lib/debug/usr/lib/vdpau/libvdpau_r300.so.1.0.0`
  `/usr/lib/debug/usr/lib/vdpau/libvdpau_r600.so.1.0.0`
  `/usr/lib/debug/usr/lib/xorg/modules/drivers/r200_dri.so`
  `/usr/lib/debug/usr/lib/xorg/modules/drivers/r300_dri.so`
  `/usr/lib/debug/usr/lib/xorg/modules/drivers/r600_dri.so`
  `/usr/lib/debug/usr/lib/xorg/modules/drivers/i915_dri.so`
  `/usr/lib/debug/usr/lib/xorg/modules/drivers/i965_dri.so`
  `/usr/lib/debug/usr/lib/xorg/modules/drivers/vmwgfx_dri.so`
Take this with a grain of salt because I'm a novice at debugging and for all I know some of those are supposed to be stripped.

### Workaround(?)
In testing mesa-ati-dri-dbg for completeness, I found that using gdb to debug the same crash as before gave the message `warning: the debug information found in "/usr/lib/xorg/modules/drivers/radeon_dri.so" does not match "/usr/lib/xorg/modules/drivers/i915_dri.so" (CRC mismatch).`
gdb then gives backtrace lines such as `#0  0x00007ffff6d86cd9 in _mesa_reallocate_registers (prog=prog@entry=0x55555590b230) at ..src/mesa/program/prog_optimize.c:1103`
I don't know if these are the right function names and line numbers exactly, but it seems like installing mesa-ati-dri-dbg is a workaround?

I think my bug still stands, you shouldn't need to install mesa-ati-dri-dbg and mesa-ati-dri in order to debug mesa-intel-dri. It also seems suspicious that a number of debug object files are stripped.

**Comment by st3r4g** [comment] 2019-10-07 23:20
I think this is due to the fact that the `xorg/modules/drivers/*.so` are created as hard links by Mesa. Output of `ls masterdir/usr/lib/xorg/modules/drivers/ -i`:
> 394315 i915_dri.so
394315 i965_dri.so
394316 kms_swrast_dri.so
394316 nouveau_dri.so
394315 nouveau_vieux_dri.so
394315 r200_dri.so
394316 r300_dri.so
394316 r600_dri.so
394315 radeon_dri.so
394316 radeonsi_dri.so
394316 swrast_dri.so
394316 virtio_gpu_dri.so
394316 vmwgfx_dri.so

They probably result from https://gitlab.freedesktop.org/mesa/mesa/blob/master/bin/install_megadrivers.py.

**Comment by st3r4g** [comment] 2019-10-08 08:19
Duplicate of #12760

**Comment by xtraeme** [comment] 2019-12-27 22:19
This is now in master

**Closed by xtraeme** 2019-12-27 22:19 UTC
Labels: bug
