### ISSUE TITLE
2048-qt seg fault

### ISSUE THREAD

**Issue by chriscamacho** [void-linux/void-packages#13727] opened 2019-08-17 12:28 UTC
### System

* xuname:  
  Void 4.19.58-v7l+ armv7l  uptodate rFFF
* package:  
  2048-qt-0.1.6_1
### Expected behavior
it should work.
### Actual behavior
see below
### Steps to reproduce the behavior
$ 2048-qt 
qml: Started a new game
No available targets are compatible with triple "i386-unknown-linux-gnu"
Segmentation fault

**Comment by q66** [comment] 2020-08-01 01:35
duplicate of #13896

**Closed by q66** 2020-08-01 01:35 UTC
Labels: bug
