### ISSUE TITLE
After standard upgrade (to kernel 6.6.1) the nvidia driver didnt compile

### ISSUE THREAD

**Issue by c-pointer** [void-linux/void-packages#48551] opened 2024-02-05 22:00 UTC
After standard upgrade to kernel 6.6.1, nvidia failed to compile.
Now I am using LTS kernel, to report the bug
Void 6.1.71_1 x86_64 AuthenticAMD uptodate rrmFFFFFFFF

Please include a fast issue report, in this case you have to stop it now.

**Comment by c-pointer** [comment] 2024-02-05 22:03
Issue #48504 exactly the same... just now on the default upgrade (non-mainline)

**Comment by classabbyamp** [comment] 2024-02-05 22:07
duplicate of #48504

**Closed by classabbyamp** 2024-02-05 22:07 UTC
