### ISSUE TITLE
miss in packages.  inaction of the maintainers.

### ISSUE THREAD

**Issue by IT-DEVS-Group** [void-linux/void-packages#37140] opened 2022-05-15 08:48 UTC
due to the inaction of the maintainers, there is no way to clean up the packages. Missing XFCE plugins, outdated software versions, slow review of commits. Void was my favorite distro, but due to the inactivity of the maintainers, it looks like one should look for distros with more serious maintainers.

**Comment by jrigg** [comment] 2022-05-15 09:21
Your pull request was made two days before you posted this. People (unpaid volunteers in this case) have lives.

**Comment by paper42** [comment] 2022-05-15 10:43
Feel free to fix them, one by one, with a clear description what and why are you doing. This is not a bug report, so closing.

**Closed by paper42** 2022-05-15 10:43 UTC

**Comment by IT-DEVS-Group** [comment] 2022-05-17 19:42
> Your pull request was made two days before you posted this. People (unpaid volunteers in this case) have lives.

I sent a commit 4 days ago. Today this commit is long forgotten and ignored

**Comment by paper42** [comment] 2022-05-17 23:49
> > Your pull request was made two days before you posted this. People (unpaid volunteers in this case) have lives.
> 
> I sent a commit 4 days ago. Today this commit is long forgotten and ignored

Which PR are we talking about? You made 4, 3 different people made 8 comments on them and you closed 3 of them.

**Comment by IT-DEVS-Group** [comment] 2022-05-18 17:08
> > > Ваш запрос на включение был сделан за два дня до того, как вы опубликовали это.  У людей (в данном случае неоплачиваемых волонтеров) есть жизни.
> > 
> > 
> > Я отправил коммит 4 дня назад.  Сегодня этот коммит давно забыт и игнорируется
> 
> О каком пиаре идет речь? Вы сделали 4, 3 разных человека оставили к ним 8 комментариев, и вы закрыли 3 из них.

https://github.com/void-linux/void-packages/pull/37101

> > > Your pull request was made two days before you posted this. People (unpaid volunteers in this case) have lives.
> > 
> > 
> > I sent a commit 4 days ago. Today this commit is long forgotten and ignored
> 
> Which PR are we talking about? You made 4, 3 different people made 8 comments on them and you closed 3 of them.

https://github.com/void-linux/void-packages/pull/37101
