### ISSUE TITLE
No Ethernet detected on Raspberry Pi after updates.

### ISSUE THREAD

**Issue by foldfree** [void-linux/void-packages#6293] opened 2018-12-28 16:46 UTC
Linux void-live 4.14.90_1 aarch64 musl

Running on the live version of 20181111, it works fine, however after update and reboot, no more ethernet. This is what I got from dmesg.

[    2.775190] lan78xx 1-1.1.1:1.0 (unnamed net_device) (uninitialized): can't register MDIO bus
[    2.775392] lan78xx 1-1.1.1:1.0 (unnamed net_device) (uninitialized): MDIO INIT FAILED.....
[    2.775442] lan78xx 1-1.1.1:1.0 (unnamed net_device) (uninitialized): Bind routine FAILED

ifconfig show no ethernet interface, so the kernel failed to load it.

I encounter one another person with the same issue on IRC.
any help kindly appreciated.

**Comment by foldfree** [comment] 2018-12-28 20:58
https://github.com/raspberrypi/firmware/issues/957

I think it's this issue, any chance this gets patched locally?

**Comment by newbluemoon** [comment] 2018-12-29 15:14
Just wanted to state that my RPi 3 is on armv7l-musl, up-to-date, and there everything works fine. Cannot test aarch64* (yet).

**Comment by Arcturus615** [comment] 2019-01-14 17:54
Figured I would add to this. I'm also having the same issue following updating on a fresh install. The image used was the `void-rpi3-20181111` image, and dmesg is reporting the same error. It seems to have been reported almost nowhere, though I was able to find someone on [Alpine](https://bugs.alpinelinux.org/issues/9732)  that was having same issue in december. Does anyone know either how to solve this, or whats going on here?
```
[    2.779263] lan78xx 1-1.1.1:1.0 (unnamed net_device) (uninitialized): can't register MDIO bus
[    2.779569] lan78xx 1-1.1.1:1.0 (unnamed net_device) (uninitialized): MDIO INIT FAILED.....
[    2.779640] lan78xx 1-1.1.1:1.0 (unnamed net_device) (uninitialized): Bind routine FAILED
```

**Comment by Hoshpak** [comment] 2019-01-19 17:57
Please install the new version of the rpi-firmware package and check if it improves the situation.

**Comment by foldfree** [comment] 2019-01-25 16:48
I've tried raspbian, the official raspberry foundation image, and encountered the same issue.

**Comment by kervel** [comment] 2019-01-25 19:38
Update: I built the 4.19 kernel from raspberry GitHub and the issue is gone here.

**Comment by Hoshpak** [comment] 2019-01-25 19:55
so it's not about the firmware files. Maybe one of you who has an actual device to be able to possibly provide further pieces of information could report the issue upstream? If it's reproducable with raspbian, it should be much easier for upstream developers to debug. I don't know when we will be switching to the 4.19 kernel and if we don't know where the issue lies, there's no way to patch it for us.

**Comment by lpvm** [comment] 2019-01-25 22:20
My aarch64 installation on a RPi3B+ is also affected, using 4.14.93_1.   Hope it gets fixed soon.

**Comment by Hoshpak** [comment] 2019-02-23 22:04
Can anyone confirm that this is resolved with the update to 4.19?

**Comment by stewpend0us** [comment] 2019-02-24 02:12
Worked for me

**Closed** 2019-02-24 10:19 UTC
Labels: bug
