### ISSUE TITLE
Package request: Tiled

### ISSUE THREAD

**Issue by Nathan-MV** [void-linux/void-packages#38303] opened 2022-07-27 05:49 UTC
### Package name

tiled

### Package homepage

https://github.com/mapeditor/tiled

### Description

A general purpose tile map editor, used when doing games without a full featured engine or because the map editor of n engine is bad

### Does the requested package meet the quality requirements?

Compiled

### Is the requested package released?

Yes

**Comment by paper42** [comment] 2022-07-27 07:53
duplicate of #10595

**Closed by paper42** 2022-07-27 07:53 UTC
Labels: request
