### ISSUE TITLE
[Package request] Whalebird

### ISSUE THREAD

**Issue by FollieHiyuki** [void-linux/void-packages#28244] opened 2021-01-26 16:17 UTC
Homepage: https://whalebird.social/
Source: https://github.com/h3poteto/whalebird-desktop
Description: Electron based Mastodon client
License: MIT

**Comment by FollieHiyuki** [comment] 2021-01-26 16:36
Please add the Electron label as well xD

**Comment by classabbyamp** [comment] 2022-06-25 07:20
duplicate of #21083

**Closed by classabbyamp** 2022-06-25 07:20 UTC
Labels: request, electron 🤮
