### ISSUE TITLE
[Tracking] linux 5.3 dkms status

### ISSUE THREAD

**Issue by jnbr** [void-linux/void-packages#15615] opened 2019-10-19 11:56 UTC
linux5.2 is EOL, we should consider upgrading to 5.3

DKMS modules to check:

- [x] nvidia
- [x] nvidia390
- [x] nvidia 340
- [x] zfs
- [x] virtualbox-ose

If you are using any of these modules, please consider contributing to this issue by installing `linux5.3` and `linux5.3-headers` and report if everything still works for you.

**Comment by steinex** [comment] 2019-10-19 14:27
virtualbox-ose doesn't work, updating it to 6.0.14 should fix it.

**Comment by leahneukirchen** [comment] 2019-10-19 17:41
zfs 0.8.2 works on 5.3.

**Comment by Hoshpak** [comment] 2019-10-19 17:41
virtualbox-ose can't be updated right now because it needs gcc-multilib to build and that one is broken right now. I think we should ignore it this time and change the main kernel once the other modules are good to go.

**Comment by q66** [comment] 2019-10-19 18:00
Pretty sure gcc-multilib can be updated since the latest relevant xbps-src changes

**Comment by q66** [comment] 2019-10-19 18:02
Actually, nevermind. Seems like that change wasn't merged yet

**Comment by Hoshpak** [comment] 2019-10-19 18:02
Not yet at least:

```
=> gcc-multilib-9.1.0_1: building ...
   [host] perl-5.30.0_1: found (https://alpha.de.repo.voidlinux.org/current)
   [host] flex-2.6.4_3: found (https://alpha.de.repo.voidlinux.org/current)
   [host] zip-3.0_5: found (https://alpha.de.repo.voidlinux.org/current)
   [host] unzip-6.0_12: found (https://alpha.de.repo.voidlinux.org/current)
=> ERROR: gcc-multilib-9.1.0_1: target dependency 'glibc-32bit' does not exist!
```

#14822 might be a solution but I don't know if that is ready to merge.

**Comment by q66** [comment] 2019-10-19 18:03
Yes, that's the one I meant. It looks ready to me, but best ask @Duncaen

**Comment by Hoshpak** [comment] 2019-10-19 18:30
nvidia340 works now after patching.

**Comment by fosslinux** [comment] 2019-10-21 08:15
I can confirm that virtualbox-ose does not work for me.

**Comment by q66** [comment] 2019-10-22 00:20
Since the multilib stuff has finally been merged, someone should try if virtualbox still fails

**Comment by Hoshpak** [comment] 2019-10-22 07:52
I will do so however I don't have the time to build qt5 myself right now so I will wait until the build servers have done it.

**Comment by fosslinux** [comment] 2019-10-22 08:28
I installed `linux5.3{,-headers}`, the virtualbox-ose build still fails. I installed gcc-multilib, it still fails.

@steinex said

> virtualbox-ose doesn't work, updating it to 6.0.14 should fix it.

That may still be true.

**Comment by fosslinux** [comment] 2019-10-22 08:31
Actually

https://www.virtualbox.org/wiki/Changelog

>  VirtualBox 6.0.14 (released October 15 2019)
> ...
> Linux host: support Linux 5.3, thank you Larry Finger (see also bug #18911) 

So we need to update to 6.0.14. I try to build the new version but got 3 of these messages:

```
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/9.2.0/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
```

in the build.

**Comment by Hoshpak** [comment] 2019-10-22 09:07
Before virtualbox can be updated, the current pile of builds need to finish and that one is huge, so give it at least 1-2 days. To test the update, gcc-multilib and qt5 need to be finished and the repository needs to be unstaged. This could happen in a few hours in the best case and not before all builds are finished in the worst.

**Comment by Hoshpak** [comment] 2019-10-24 06:43
I can confirm now that virtualbox-ose 6.0.14 works with linux 5.3. PR open at #15748

**Comment by ErsatzErmine** [comment] 2019-10-25 17:21
nvidia390 builds and loads with 5.3.7 on x86_64 without issues

**Comment by jnbr** [comment] 2019-10-25 18:04
Thanks for reporting.

**Comment by surafel911** [comment] 2019-10-27 01:55
I'm having issues getting the current Nvidia drivers working on Void. The nouveau drivers work fine. Any ideas? Here is a reddit post I made about it: https://www.reddit.com/r/voidlinux/comments/decns9/help_on_some_issues_switching_to_void/?utm_source=share&utm_medium=web2x

**Comment by jnbr** [comment] 2019-10-27 06:51
This is completlely unrelated. Please open a new issue or try to get help on IRC in #voidlinux.

**Closed** 2019-10-28 19:31 UTC
