### ISSUE TITLE
Package request: gnome-console

### ISSUE THREAD

**Issue by Nathan-MV** [void-linux/void-packages#38263] opened 2022-07-25 03:12 UTC
### Package name

gnome-console

### Package homepage

https://gitlab.gnome.org/GNOME/console

### Description

A simple user-friendly terminal emulator for the GNOME desktop supposed to substitute gnome-terminal.

### Does the requested package meet the quality requirements?

Compiled

### Is the requested package released?

Yes

**Comment by oreo639** [comment] 2022-07-25 04:36
Duplicate of: https://github.com/void-linux/void-packages/issues/37975

**Closed** 2022-07-25 05:16 UTC
Labels: request
